// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/types/action.proto

package iotextypes

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StakeUpdateType int32

const (
	StakeUpdateType_Unstake  StakeUpdateType = 0
	StakeUpdateType_Withdraw StakeUpdateType = 1
)

var StakeUpdateType_name = map[int32]string{
	0: "Unstake",
	1: "Withdraw",
}

var StakeUpdateType_value = map[string]int32{
	"Unstake":  0,
	"Withdraw": 1,
}

func (x StakeUpdateType) String() string {
	return proto.EnumName(StakeUpdateType_name, int32(x))
}

func (StakeUpdateType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d4dd5ed50f883f28, []int{0}
}

type StakeMoveType int32

const (
	StakeMoveType_ChangeCandidate   StakeMoveType = 0
	StakeMoveType_TransferOwnership StakeMoveType = 1
)

var StakeMoveType_name = map[int32]string{
	0: "ChangeCandidate",
	1: "TransferOwnership",
}

var StakeMoveType_value = map[string]int32{
	"ChangeCandidate":   0,
	"TransferOwnership": 1,
}

func (x StakeMoveType) String() string {
	return proto.EnumName(StakeMoveType_name, int32(x))
}

func (StakeMoveType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d4dd5ed50f883f28, []int{1}
}

type RewardType int32

const (
	RewardType_BlockReward RewardType = 0
	RewardType_EpochReward RewardType = 1
)

var RewardType_name = map[int32]string{
	0: "BlockReward",
	1: "EpochReward",
}

var RewardType_value = map[string]int32{
	"BlockReward": 0,
	"EpochReward": 1,
}

func (x RewardType) String() string {
	return proto.EnumName(RewardType_name, int32(x))
}

func (RewardType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d4dd5ed50f883f28, []int{2}
}

type Transfer struct {
	// used by state-based model
	Amount               string   `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Recipient            string   `protobuf:"bytes,2,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Payload              []byte   `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transfer) Reset()         { *m = Transfer{} }
func (m *Transfer) String() string { return proto.CompactTextString(m) }
func (*Transfer) ProtoMessage()    {}
func (*Transfer) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4dd5ed50f883f28, []int{0}
}

func (m *Transfer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transfer.Unmarshal(m, b)
}
func (m *Transfer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transfer.Marshal(b, m, deterministic)
}
func (m *Transfer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transfer.Merge(m, src)
}
func (m *Transfer) XXX_Size() int {
	return xxx_messageInfo_Transfer.Size(m)
}
func (m *Transfer) XXX_DiscardUnknown() {
	xxx_messageInfo_Transfer.DiscardUnknown(m)
}

var xxx_messageInfo_Transfer proto.InternalMessageInfo

func (m *Transfer) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *Transfer) GetRecipient() string {
	if m != nil {
		return m.Recipient
	}
	return ""
}

func (m *Transfer) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

// Candidates and list of candidates
type Candidate struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Votes                []byte   `protobuf:"bytes,2,opt,name=votes,proto3" json:"votes,omitempty"`
	PubKey               []byte   `protobuf:"bytes,3,opt,name=pubKey,proto3" json:"pubKey,omitempty"`
	RewardAddress        string   `protobuf:"bytes,4,opt,name=rewardAddress,proto3" json:"rewardAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Candidate) Reset()         { *m = Candidate{} }
func (m *Candidate) String() string { return proto.CompactTextString(m) }
func (*Candidate) ProtoMessage()    {}
func (*Candidate) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4dd5ed50f883f28, []int{1}
}

func (m *Candidate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Candidate.Unmarshal(m, b)
}
func (m *Candidate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Candidate.Marshal(b, m, deterministic)
}
func (m *Candidate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Candidate.Merge(m, src)
}
func (m *Candidate) XXX_Size() int {
	return xxx_messageInfo_Candidate.Size(m)
}
func (m *Candidate) XXX_DiscardUnknown() {
	xxx_messageInfo_Candidate.DiscardUnknown(m)
}

var xxx_messageInfo_Candidate proto.InternalMessageInfo

func (m *Candidate) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Candidate) GetVotes() []byte {
	if m != nil {
		return m.Votes
	}
	return nil
}

func (m *Candidate) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *Candidate) GetRewardAddress() string {
	if m != nil {
		return m.RewardAddress
	}
	return ""
}

type CandidateList struct {
	Candidates           []*Candidate `protobuf:"bytes,1,rep,name=candidates,proto3" json:"candidates,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CandidateList) Reset()         { *m = CandidateList{} }
func (m *CandidateList) String() string { return proto.CompactTextString(m) }
func (*CandidateList) ProtoMessage()    {}
func (*CandidateList) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4dd5ed50f883f28, []int{2}
}

func (m *CandidateList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CandidateList.Unmarshal(m, b)
}
func (m *CandidateList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CandidateList.Marshal(b, m, deterministic)
}
func (m *CandidateList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CandidateList.Merge(m, src)
}
func (m *CandidateList) XXX_Size() int {
	return xxx_messageInfo_CandidateList.Size(m)
}
func (m *CandidateList) XXX_DiscardUnknown() {
	xxx_messageInfo_CandidateList.DiscardUnknown(m)
}

var xxx_messageInfo_CandidateList proto.InternalMessageInfo

func (m *CandidateList) GetCandidates() []*Candidate {
	if m != nil {
		return m.Candidates
	}
	return nil
}

// KickoutInfo and list of KickoutCandidateList
type KickoutCandidateList struct {
	Blacklists           []*KickoutInfo `protobuf:"bytes,1,rep,name=blacklists,proto3" json:"blacklists,omitempty"`
	IntensityRate        uint32         `protobuf:"varint,2,opt,name=intensityRate,proto3" json:"intensityRate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *KickoutCandidateList) Reset()         { *m = KickoutCandidateList{} }
func (m *KickoutCandidateList) String() string { return proto.CompactTextString(m) }
func (*KickoutCandidateList) ProtoMessage()    {}
func (*KickoutCandidateList) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4dd5ed50f883f28, []int{3}
}

func (m *KickoutCandidateList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KickoutCandidateList.Unmarshal(m, b)
}
func (m *KickoutCandidateList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KickoutCandidateList.Marshal(b, m, deterministic)
}
func (m *KickoutCandidateList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KickoutCandidateList.Merge(m, src)
}
func (m *KickoutCandidateList) XXX_Size() int {
	return xxx_messageInfo_KickoutCandidateList.Size(m)
}
func (m *KickoutCandidateList) XXX_DiscardUnknown() {
	xxx_messageInfo_KickoutCandidateList.DiscardUnknown(m)
}

var xxx_messageInfo_KickoutCandidateList proto.InternalMessageInfo

func (m *KickoutCandidateList) GetBlacklists() []*KickoutInfo {
	if m != nil {
		return m.Blacklists
	}
	return nil
}

func (m *KickoutCandidateList) GetIntensityRate() uint32 {
	if m != nil {
		return m.IntensityRate
	}
	return 0
}

type KickoutInfo struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Count                uint32   `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KickoutInfo) Reset()         { *m = KickoutInfo{} }
func (m *KickoutInfo) String() string { return proto.CompactTextString(m) }
func (*KickoutInfo) ProtoMessage()    {}
func (*KickoutInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4dd5ed50f883f28, []int{4}
}

func (m *KickoutInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KickoutInfo.Unmarshal(m, b)
}
func (m *KickoutInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KickoutInfo.Marshal(b, m, deterministic)
}
func (m *KickoutInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KickoutInfo.Merge(m, src)
}
func (m *KickoutInfo) XXX_Size() int {
	return xxx_messageInfo_KickoutInfo.Size(m)
}
func (m *KickoutInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_KickoutInfo.DiscardUnknown(m)
}

var xxx_messageInfo_KickoutInfo proto.InternalMessageInfo

func (m *KickoutInfo) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *KickoutInfo) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type PutPollResult struct {
	Height               uint64         `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Candidates           *CandidateList `protobuf:"bytes,2,opt,name=candidates,proto3" json:"candidates,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PutPollResult) Reset()         { *m = PutPollResult{} }
func (m *PutPollResult) String() string { return proto.CompactTextString(m) }
func (*PutPollResult) ProtoMessage()    {}
func (*PutPollResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4dd5ed50f883f28, []int{5}
}

func (m *PutPollResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutPollResult.Unmarshal(m, b)
}
func (m *PutPollResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutPollResult.Marshal(b, m, deterministic)
}
func (m *PutPollResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutPollResult.Merge(m, src)
}
func (m *PutPollResult) XXX_Size() int {
	return xxx_messageInfo_PutPollResult.Size(m)
}
func (m *PutPollResult) XXX_DiscardUnknown() {
	xxx_messageInfo_PutPollResult.DiscardUnknown(m)
}

var xxx_messageInfo_PutPollResult proto.InternalMessageInfo

func (m *PutPollResult) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *PutPollResult) GetCandidates() *CandidateList {
	if m != nil {
		return m.Candidates
	}
	return nil
}

type Execution struct {
	Amount               string   `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Contract             string   `protobuf:"bytes,2,opt,name=contract,proto3" json:"contract,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Execution) Reset()         { *m = Execution{} }
func (m *Execution) String() string { return proto.CompactTextString(m) }
func (*Execution) ProtoMessage()    {}
func (*Execution) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4dd5ed50f883f28, []int{6}
}

func (m *Execution) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Execution.Unmarshal(m, b)
}
func (m *Execution) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Execution.Marshal(b, m, deterministic)
}
func (m *Execution) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Execution.Merge(m, src)
}
func (m *Execution) XXX_Size() int {
	return xxx_messageInfo_Execution.Size(m)
}
func (m *Execution) XXX_DiscardUnknown() {
	xxx_messageInfo_Execution.DiscardUnknown(m)
}

var xxx_messageInfo_Execution proto.InternalMessageInfo

func (m *Execution) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *Execution) GetContract() string {
	if m != nil {
		return m.Contract
	}
	return ""
}

func (m *Execution) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Bucket struct {
	CandidateName        string               `protobuf:"bytes,1,opt,name=candidateName,proto3" json:"candidateName,omitempty"`
	StakedAmount         string               `protobuf:"bytes,2,opt,name=stakedAmount,proto3" json:"stakedAmount,omitempty"`
	StakedDuration       uint32               `protobuf:"varint,3,opt,name=stakedDuration,proto3" json:"stakedDuration,omitempty"`
	CreateTime           *timestamp.Timestamp `protobuf:"bytes,4,opt,name=createTime,proto3" json:"createTime,omitempty"`
	StakeStartTime       *timestamp.Timestamp `protobuf:"bytes,5,opt,name=stakeStartTime,proto3" json:"stakeStartTime,omitempty"`
	UnstakeStartTime     *timestamp.Timestamp `protobuf:"bytes,6,opt,name=unstakeStartTime,proto3" json:"unstakeStartTime,omitempty"`
	AutoStake            bool                 `protobuf:"varint,7,opt,name=autoStake,proto3" json:"autoStake,omitempty"`
	Owner                string               `protobuf:"bytes,8,opt,name=owner,proto3" json:"owner,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Bucket) Reset()         { *m = Bucket{} }
func (m *Bucket) String() string { return proto.CompactTextString(m) }
func (*Bucket) ProtoMessage()    {}
func (*Bucket) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4dd5ed50f883f28, []int{7}
}

func (m *Bucket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bucket.Unmarshal(m, b)
}
func (m *Bucket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bucket.Marshal(b, m, deterministic)
}
func (m *Bucket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bucket.Merge(m, src)
}
func (m *Bucket) XXX_Size() int {
	return xxx_messageInfo_Bucket.Size(m)
}
func (m *Bucket) XXX_DiscardUnknown() {
	xxx_messageInfo_Bucket.DiscardUnknown(m)
}

var xxx_messageInfo_Bucket proto.InternalMessageInfo

func (m *Bucket) GetCandidateName() string {
	if m != nil {
		return m.CandidateName
	}
	return ""
}

func (m *Bucket) GetStakedAmount() string {
	if m != nil {
		return m.StakedAmount
	}
	return ""
}

func (m *Bucket) GetStakedDuration() uint32 {
	if m != nil {
		return m.StakedDuration
	}
	return 0
}

func (m *Bucket) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *Bucket) GetStakeStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.StakeStartTime
	}
	return nil
}

func (m *Bucket) GetUnstakeStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.UnstakeStartTime
	}
	return nil
}

func (m *Bucket) GetAutoStake() bool {
	if m != nil {
		return m.AutoStake
	}
	return false
}

func (m *Bucket) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

type StakeCreate struct {
	CandidateName        string   `protobuf:"bytes,1,opt,name=candidateName,proto3" json:"candidateName,omitempty"`
	StakedAmount         string   `protobuf:"bytes,2,opt,name=stakedAmount,proto3" json:"stakedAmount,omitempty"`
	StakedDuration       uint32   `protobuf:"varint,3,opt,name=stakedDuration,proto3" json:"stakedDuration,omitempty"`
	AutoStake            bool     `protobuf:"varint,4,opt,name=autoStake,proto3" json:"autoStake,omitempty"`
	Payload              []byte   `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StakeCreate) Reset()         { *m = StakeCreate{} }
func (m *StakeCreate) String() string { return proto.CompactTextString(m) }
func (*StakeCreate) ProtoMessage()    {}
func (*StakeCreate) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4dd5ed50f883f28, []int{8}
}

func (m *StakeCreate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StakeCreate.Unmarshal(m, b)
}
func (m *StakeCreate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StakeCreate.Marshal(b, m, deterministic)
}
func (m *StakeCreate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StakeCreate.Merge(m, src)
}
func (m *StakeCreate) XXX_Size() int {
	return xxx_messageInfo_StakeCreate.Size(m)
}
func (m *StakeCreate) XXX_DiscardUnknown() {
	xxx_messageInfo_StakeCreate.DiscardUnknown(m)
}

var xxx_messageInfo_StakeCreate proto.InternalMessageInfo

func (m *StakeCreate) GetCandidateName() string {
	if m != nil {
		return m.CandidateName
	}
	return ""
}

func (m *StakeCreate) GetStakedAmount() string {
	if m != nil {
		return m.StakedAmount
	}
	return ""
}

func (m *StakeCreate) GetStakedDuration() uint32 {
	if m != nil {
		return m.StakedDuration
	}
	return 0
}

func (m *StakeCreate) GetAutoStake() bool {
	if m != nil {
		return m.AutoStake
	}
	return false
}

func (m *StakeCreate) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

// unstake or withdraw
type StakeUpdate struct {
	Type                 StakeUpdateType `protobuf:"varint,1,opt,name=type,proto3,enum=iotextypes.StakeUpdateType" json:"type,omitempty"`
	BucketIndex          uint64          `protobuf:"varint,2,opt,name=bucketIndex,proto3" json:"bucketIndex,omitempty"`
	Payload              []byte          `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *StakeUpdate) Reset()         { *m = StakeUpdate{} }
func (m *StakeUpdate) String() string { return proto.CompactTextString(m) }
func (*StakeUpdate) ProtoMessage()    {}
func (*StakeUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4dd5ed50f883f28, []int{9}
}

func (m *StakeUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StakeUpdate.Unmarshal(m, b)
}
func (m *StakeUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StakeUpdate.Marshal(b, m, deterministic)
}
func (m *StakeUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StakeUpdate.Merge(m, src)
}
func (m *StakeUpdate) XXX_Size() int {
	return xxx_messageInfo_StakeUpdate.Size(m)
}
func (m *StakeUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_StakeUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_StakeUpdate proto.InternalMessageInfo

func (m *StakeUpdate) GetType() StakeUpdateType {
	if m != nil {
		return m.Type
	}
	return StakeUpdateType_Unstake
}

func (m *StakeUpdate) GetBucketIndex() uint64 {
	if m != nil {
		return m.BucketIndex
	}
	return 0
}

func (m *StakeUpdate) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

// add the amount of bucket
type StakeAddDeposit struct {
	BucketIndex          uint64   `protobuf:"varint,1,opt,name=bucketIndex,proto3" json:"bucketIndex,omitempty"`
	Amount               string   `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Payload              []byte   `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StakeAddDeposit) Reset()         { *m = StakeAddDeposit{} }
func (m *StakeAddDeposit) String() string { return proto.CompactTextString(m) }
func (*StakeAddDeposit) ProtoMessage()    {}
func (*StakeAddDeposit) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4dd5ed50f883f28, []int{10}
}

func (m *StakeAddDeposit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StakeAddDeposit.Unmarshal(m, b)
}
func (m *StakeAddDeposit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StakeAddDeposit.Marshal(b, m, deterministic)
}
func (m *StakeAddDeposit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StakeAddDeposit.Merge(m, src)
}
func (m *StakeAddDeposit) XXX_Size() int {
	return xxx_messageInfo_StakeAddDeposit.Size(m)
}
func (m *StakeAddDeposit) XXX_DiscardUnknown() {
	xxx_messageInfo_StakeAddDeposit.DiscardUnknown(m)
}

var xxx_messageInfo_StakeAddDeposit proto.InternalMessageInfo

func (m *StakeAddDeposit) GetBucketIndex() uint64 {
	if m != nil {
		return m.BucketIndex
	}
	return 0
}

func (m *StakeAddDeposit) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *StakeAddDeposit) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

// restake the duration and autoStake flag of bucket
type StakeAgain struct {
	BucketIndex          uint64   `protobuf:"varint,1,opt,name=bucketIndex,proto3" json:"bucketIndex,omitempty"`
	StakedDuration       uint32   `protobuf:"varint,2,opt,name=stakedDuration,proto3" json:"stakedDuration,omitempty"`
	AutoStake            bool     `protobuf:"varint,3,opt,name=autoStake,proto3" json:"autoStake,omitempty"`
	Payload              []byte   `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StakeAgain) Reset()         { *m = StakeAgain{} }
func (m *StakeAgain) String() string { return proto.CompactTextString(m) }
func (*StakeAgain) ProtoMessage()    {}
func (*StakeAgain) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4dd5ed50f883f28, []int{11}
}

func (m *StakeAgain) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StakeAgain.Unmarshal(m, b)
}
func (m *StakeAgain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StakeAgain.Marshal(b, m, deterministic)
}
func (m *StakeAgain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StakeAgain.Merge(m, src)
}
func (m *StakeAgain) XXX_Size() int {
	return xxx_messageInfo_StakeAgain.Size(m)
}
func (m *StakeAgain) XXX_DiscardUnknown() {
	xxx_messageInfo_StakeAgain.DiscardUnknown(m)
}

var xxx_messageInfo_StakeAgain proto.InternalMessageInfo

func (m *StakeAgain) GetBucketIndex() uint64 {
	if m != nil {
		return m.BucketIndex
	}
	return 0
}

func (m *StakeAgain) GetStakedDuration() uint32 {
	if m != nil {
		return m.StakedDuration
	}
	return 0
}

func (m *StakeAgain) GetAutoStake() bool {
	if m != nil {
		return m.AutoStake
	}
	return false
}

func (m *StakeAgain) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

// move the bucket for another candidate or transfer the ownership of bucket to another voter
type StakeMove struct {
	Type                 StakeMoveType `protobuf:"varint,1,opt,name=type,proto3,enum=iotextypes.StakeMoveType" json:"type,omitempty"`
	Name                 string        `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	BucketIndex          uint64        `protobuf:"varint,3,opt,name=bucketIndex,proto3" json:"bucketIndex,omitempty"`
	Payload              []byte        `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *StakeMove) Reset()         { *m = StakeMove{} }
func (m *StakeMove) String() string { return proto.CompactTextString(m) }
func (*StakeMove) ProtoMessage()    {}
func (*StakeMove) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4dd5ed50f883f28, []int{12}
}

func (m *StakeMove) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StakeMove.Unmarshal(m, b)
}
func (m *StakeMove) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StakeMove.Marshal(b, m, deterministic)
}
func (m *StakeMove) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StakeMove.Merge(m, src)
}
func (m *StakeMove) XXX_Size() int {
	return xxx_messageInfo_StakeMove.Size(m)
}
func (m *StakeMove) XXX_DiscardUnknown() {
	xxx_messageInfo_StakeMove.DiscardUnknown(m)
}

var xxx_messageInfo_StakeMove proto.InternalMessageInfo

func (m *StakeMove) GetType() StakeMoveType {
	if m != nil {
		return m.Type
	}
	return StakeMoveType_ChangeCandidate
}

func (m *StakeMove) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StakeMove) GetBucketIndex() uint64 {
	if m != nil {
		return m.BucketIndex
	}
	return 0
}

func (m *StakeMove) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type StartSubChain struct {
	// TODO: chainID chould be assigned by system and returned via a receipt
	ChainID              uint32   `protobuf:"varint,1,opt,name=chainID,proto3" json:"chainID,omitempty"`
	SecurityDeposit      string   `protobuf:"bytes,2,opt,name=securityDeposit,proto3" json:"securityDeposit,omitempty"`
	OperationDeposit     string   `protobuf:"bytes,3,opt,name=operationDeposit,proto3" json:"operationDeposit,omitempty"`
	StartHeight          uint64   `protobuf:"varint,4,opt,name=startHeight,proto3" json:"startHeight,omitempty"`
	ParentHeightOffset   uint64   `protobuf:"varint,5,opt,name=parentHeightOffset,proto3" json:"parentHeightOffset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartSubChain) Reset()         { *m = StartSubChain{} }
func (m *StartSubChain) String() string { return proto.CompactTextString(m) }
func (*StartSubChain) ProtoMessage()    {}
func (*StartSubChain) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4dd5ed50f883f28, []int{13}
}

func (m *StartSubChain) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartSubChain.Unmarshal(m, b)
}
func (m *StartSubChain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartSubChain.Marshal(b, m, deterministic)
}
func (m *StartSubChain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartSubChain.Merge(m, src)
}
func (m *StartSubChain) XXX_Size() int {
	return xxx_messageInfo_StartSubChain.Size(m)
}
func (m *StartSubChain) XXX_DiscardUnknown() {
	xxx_messageInfo_StartSubChain.DiscardUnknown(m)
}

var xxx_messageInfo_StartSubChain proto.InternalMessageInfo

func (m *StartSubChain) GetChainID() uint32 {
	if m != nil {
		return m.ChainID
	}
	return 0
}

func (m *StartSubChain) GetSecurityDeposit() string {
	if m != nil {
		return m.SecurityDeposit
	}
	return ""
}

func (m *StartSubChain) GetOperationDeposit() string {
	if m != nil {
		return m.OperationDeposit
	}
	return ""
}

func (m *StartSubChain) GetStartHeight() uint64 {
	if m != nil {
		return m.StartHeight
	}
	return 0
}

func (m *StartSubChain) GetParentHeightOffset() uint64 {
	if m != nil {
		return m.ParentHeightOffset
	}
	return 0
}

type StopSubChain struct {
	ChainID              uint32   `protobuf:"varint,1,opt,name=chainID,proto3" json:"chainID,omitempty"`
	StopHeight           uint64   `protobuf:"varint,2,opt,name=stopHeight,proto3" json:"stopHeight,omitempty"`
	SubChainAddress      string   `protobuf:"bytes,3,opt,name=subChainAddress,proto3" json:"subChainAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopSubChain) Reset()         { *m = StopSubChain{} }
func (m *StopSubChain) String() string { return proto.CompactTextString(m) }
func (*StopSubChain) ProtoMessage()    {}
func (*StopSubChain) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4dd5ed50f883f28, []int{14}
}

func (m *StopSubChain) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopSubChain.Unmarshal(m, b)
}
func (m *StopSubChain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopSubChain.Marshal(b, m, deterministic)
}
func (m *StopSubChain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopSubChain.Merge(m, src)
}
func (m *StopSubChain) XXX_Size() int {
	return xxx_messageInfo_StopSubChain.Size(m)
}
func (m *StopSubChain) XXX_DiscardUnknown() {
	xxx_messageInfo_StopSubChain.DiscardUnknown(m)
}

var xxx_messageInfo_StopSubChain proto.InternalMessageInfo

func (m *StopSubChain) GetChainID() uint32 {
	if m != nil {
		return m.ChainID
	}
	return 0
}

func (m *StopSubChain) GetStopHeight() uint64 {
	if m != nil {
		return m.StopHeight
	}
	return 0
}

func (m *StopSubChain) GetSubChainAddress() string {
	if m != nil {
		return m.SubChainAddress
	}
	return ""
}

type MerkleRoot struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MerkleRoot) Reset()         { *m = MerkleRoot{} }
func (m *MerkleRoot) String() string { return proto.CompactTextString(m) }
func (*MerkleRoot) ProtoMessage()    {}
func (*MerkleRoot) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4dd5ed50f883f28, []int{15}
}

func (m *MerkleRoot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerkleRoot.Unmarshal(m, b)
}
func (m *MerkleRoot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerkleRoot.Marshal(b, m, deterministic)
}
func (m *MerkleRoot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerkleRoot.Merge(m, src)
}
func (m *MerkleRoot) XXX_Size() int {
	return xxx_messageInfo_MerkleRoot.Size(m)
}
func (m *MerkleRoot) XXX_DiscardUnknown() {
	xxx_messageInfo_MerkleRoot.DiscardUnknown(m)
}

var xxx_messageInfo_MerkleRoot proto.InternalMessageInfo

func (m *MerkleRoot) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MerkleRoot) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type PutBlock struct {
	SubChainAddress      string        `protobuf:"bytes,1,opt,name=subChainAddress,proto3" json:"subChainAddress,omitempty"`
	Height               uint64        `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Roots                []*MerkleRoot `protobuf:"bytes,3,rep,name=roots,proto3" json:"roots,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *PutBlock) Reset()         { *m = PutBlock{} }
func (m *PutBlock) String() string { return proto.CompactTextString(m) }
func (*PutBlock) ProtoMessage()    {}
func (*PutBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4dd5ed50f883f28, []int{16}
}

func (m *PutBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutBlock.Unmarshal(m, b)
}
func (m *PutBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutBlock.Marshal(b, m, deterministic)
}
func (m *PutBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutBlock.Merge(m, src)
}
func (m *PutBlock) XXX_Size() int {
	return xxx_messageInfo_PutBlock.Size(m)
}
func (m *PutBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_PutBlock.DiscardUnknown(m)
}

var xxx_messageInfo_PutBlock proto.InternalMessageInfo

func (m *PutBlock) GetSubChainAddress() string {
	if m != nil {
		return m.SubChainAddress
	}
	return ""
}

func (m *PutBlock) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *PutBlock) GetRoots() []*MerkleRoot {
	if m != nil {
		return m.Roots
	}
	return nil
}

type CreateDeposit struct {
	ChainID              uint32   `protobuf:"varint,1,opt,name=chainID,proto3" json:"chainID,omitempty"`
	Amount               string   `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Recipient            string   `protobuf:"bytes,3,opt,name=recipient,proto3" json:"recipient,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateDeposit) Reset()         { *m = CreateDeposit{} }
func (m *CreateDeposit) String() string { return proto.CompactTextString(m) }
func (*CreateDeposit) ProtoMessage()    {}
func (*CreateDeposit) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4dd5ed50f883f28, []int{17}
}

func (m *CreateDeposit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDeposit.Unmarshal(m, b)
}
func (m *CreateDeposit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDeposit.Marshal(b, m, deterministic)
}
func (m *CreateDeposit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDeposit.Merge(m, src)
}
func (m *CreateDeposit) XXX_Size() int {
	return xxx_messageInfo_CreateDeposit.Size(m)
}
func (m *CreateDeposit) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDeposit.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDeposit proto.InternalMessageInfo

func (m *CreateDeposit) GetChainID() uint32 {
	if m != nil {
		return m.ChainID
	}
	return 0
}

func (m *CreateDeposit) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *CreateDeposit) GetRecipient() string {
	if m != nil {
		return m.Recipient
	}
	return ""
}

type SettleDeposit struct {
	Amount               string   `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Recipient            string   `protobuf:"bytes,2,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Index                uint64   `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SettleDeposit) Reset()         { *m = SettleDeposit{} }
func (m *SettleDeposit) String() string { return proto.CompactTextString(m) }
func (*SettleDeposit) ProtoMessage()    {}
func (*SettleDeposit) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4dd5ed50f883f28, []int{18}
}

func (m *SettleDeposit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SettleDeposit.Unmarshal(m, b)
}
func (m *SettleDeposit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SettleDeposit.Marshal(b, m, deterministic)
}
func (m *SettleDeposit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SettleDeposit.Merge(m, src)
}
func (m *SettleDeposit) XXX_Size() int {
	return xxx_messageInfo_SettleDeposit.Size(m)
}
func (m *SettleDeposit) XXX_DiscardUnknown() {
	xxx_messageInfo_SettleDeposit.DiscardUnknown(m)
}

var xxx_messageInfo_SettleDeposit proto.InternalMessageInfo

func (m *SettleDeposit) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *SettleDeposit) GetRecipient() string {
	if m != nil {
		return m.Recipient
	}
	return ""
}

func (m *SettleDeposit) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

// plum main chain APIs
type CreatePlumChain struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePlumChain) Reset()         { *m = CreatePlumChain{} }
func (m *CreatePlumChain) String() string { return proto.CompactTextString(m) }
func (*CreatePlumChain) ProtoMessage()    {}
func (*CreatePlumChain) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4dd5ed50f883f28, []int{19}
}

func (m *CreatePlumChain) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePlumChain.Unmarshal(m, b)
}
func (m *CreatePlumChain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePlumChain.Marshal(b, m, deterministic)
}
func (m *CreatePlumChain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePlumChain.Merge(m, src)
}
func (m *CreatePlumChain) XXX_Size() int {
	return xxx_messageInfo_CreatePlumChain.Size(m)
}
func (m *CreatePlumChain) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePlumChain.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePlumChain proto.InternalMessageInfo

type TerminatePlumChain struct {
	SubChainAddress      string   `protobuf:"bytes,1,opt,name=subChainAddress,proto3" json:"subChainAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TerminatePlumChain) Reset()         { *m = TerminatePlumChain{} }
func (m *TerminatePlumChain) String() string { return proto.CompactTextString(m) }
func (*TerminatePlumChain) ProtoMessage()    {}
func (*TerminatePlumChain) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4dd5ed50f883f28, []int{20}
}

func (m *TerminatePlumChain) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TerminatePlumChain.Unmarshal(m, b)
}
func (m *TerminatePlumChain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TerminatePlumChain.Marshal(b, m, deterministic)
}
func (m *TerminatePlumChain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TerminatePlumChain.Merge(m, src)
}
func (m *TerminatePlumChain) XXX_Size() int {
	return xxx_messageInfo_TerminatePlumChain.Size(m)
}
func (m *TerminatePlumChain) XXX_DiscardUnknown() {
	xxx_messageInfo_TerminatePlumChain.DiscardUnknown(m)
}

var xxx_messageInfo_TerminatePlumChain proto.InternalMessageInfo

func (m *TerminatePlumChain) GetSubChainAddress() string {
	if m != nil {
		return m.SubChainAddress
	}
	return ""
}

type PlumPutBlock struct {
	SubChainAddress      string            `protobuf:"bytes,1,opt,name=subChainAddress,proto3" json:"subChainAddress,omitempty"`
	Height               uint64            `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Roots                map[string][]byte `protobuf:"bytes,3,rep,name=roots,proto3" json:"roots,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PlumPutBlock) Reset()         { *m = PlumPutBlock{} }
func (m *PlumPutBlock) String() string { return proto.CompactTextString(m) }
func (*PlumPutBlock) ProtoMessage()    {}
func (*PlumPutBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4dd5ed50f883f28, []int{21}
}

func (m *PlumPutBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlumPutBlock.Unmarshal(m, b)
}
func (m *PlumPutBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlumPutBlock.Marshal(b, m, deterministic)
}
func (m *PlumPutBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlumPutBlock.Merge(m, src)
}
func (m *PlumPutBlock) XXX_Size() int {
	return xxx_messageInfo_PlumPutBlock.Size(m)
}
func (m *PlumPutBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_PlumPutBlock.DiscardUnknown(m)
}

var xxx_messageInfo_PlumPutBlock proto.InternalMessageInfo

func (m *PlumPutBlock) GetSubChainAddress() string {
	if m != nil {
		return m.SubChainAddress
	}
	return ""
}

func (m *PlumPutBlock) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *PlumPutBlock) GetRoots() map[string][]byte {
	if m != nil {
		return m.Roots
	}
	return nil
}

type PlumCreateDeposit struct {
	SubChainAddress      string   `protobuf:"bytes,1,opt,name=subChainAddress,proto3" json:"subChainAddress,omitempty"`
	Amount               string   `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Recipient            string   `protobuf:"bytes,3,opt,name=recipient,proto3" json:"recipient,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlumCreateDeposit) Reset()         { *m = PlumCreateDeposit{} }
func (m *PlumCreateDeposit) String() string { return proto.CompactTextString(m) }
func (*PlumCreateDeposit) ProtoMessage()    {}
func (*PlumCreateDeposit) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4dd5ed50f883f28, []int{22}
}

func (m *PlumCreateDeposit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlumCreateDeposit.Unmarshal(m, b)
}
func (m *PlumCreateDeposit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlumCreateDeposit.Marshal(b, m, deterministic)
}
func (m *PlumCreateDeposit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlumCreateDeposit.Merge(m, src)
}
func (m *PlumCreateDeposit) XXX_Size() int {
	return xxx_messageInfo_PlumCreateDeposit.Size(m)
}
func (m *PlumCreateDeposit) XXX_DiscardUnknown() {
	xxx_messageInfo_PlumCreateDeposit.DiscardUnknown(m)
}

var xxx_messageInfo_PlumCreateDeposit proto.InternalMessageInfo

func (m *PlumCreateDeposit) GetSubChainAddress() string {
	if m != nil {
		return m.SubChainAddress
	}
	return ""
}

func (m *PlumCreateDeposit) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *PlumCreateDeposit) GetRecipient() string {
	if m != nil {
		return m.Recipient
	}
	return ""
}

type PlumStartExit struct {
	SubChainAddress             string   `protobuf:"bytes,1,opt,name=subChainAddress,proto3" json:"subChainAddress,omitempty"`
	PreviousTransfer            []byte   `protobuf:"bytes,2,opt,name=previousTransfer,proto3" json:"previousTransfer,omitempty"`
	PreviousTransferBlockProof  []byte   `protobuf:"bytes,3,opt,name=previousTransferBlockProof,proto3" json:"previousTransferBlockProof,omitempty"`
	PreviousTransferBlockHeight uint64   `protobuf:"varint,4,opt,name=previousTransferBlockHeight,proto3" json:"previousTransferBlockHeight,omitempty"`
	ExitTransfer                []byte   `protobuf:"bytes,5,opt,name=exitTransfer,proto3" json:"exitTransfer,omitempty"`
	ExitTransferBlockProof      []byte   `protobuf:"bytes,6,opt,name=exitTransferBlockProof,proto3" json:"exitTransferBlockProof,omitempty"`
	ExitTransferBlockHeight     uint64   `protobuf:"varint,7,opt,name=exitTransferBlockHeight,proto3" json:"exitTransferBlockHeight,omitempty"`
	XXX_NoUnkeyedLiteral        struct{} `json:"-"`
	XXX_unrecognized            []byte   `json:"-"`
	XXX_sizecache               int32    `json:"-"`
}

func (m *PlumStartExit) Reset()         { *m = PlumStartExit{} }
func (m *PlumStartExit) String() string { return proto.CompactTextString(m) }
func (*PlumStartExit) ProtoMessage()    {}
func (*PlumStartExit) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4dd5ed50f883f28, []int{23}
}

func (m *PlumStartExit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlumStartExit.Unmarshal(m, b)
}
func (m *PlumStartExit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlumStartExit.Marshal(b, m, deterministic)
}
func (m *PlumStartExit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlumStartExit.Merge(m, src)
}
func (m *PlumStartExit) XXX_Size() int {
	return xxx_messageInfo_PlumStartExit.Size(m)
}
func (m *PlumStartExit) XXX_DiscardUnknown() {
	xxx_messageInfo_PlumStartExit.DiscardUnknown(m)
}

var xxx_messageInfo_PlumStartExit proto.InternalMessageInfo

func (m *PlumStartExit) GetSubChainAddress() string {
	if m != nil {
		return m.SubChainAddress
	}
	return ""
}

func (m *PlumStartExit) GetPreviousTransfer() []byte {
	if m != nil {
		return m.PreviousTransfer
	}
	return nil
}

func (m *PlumStartExit) GetPreviousTransferBlockProof() []byte {
	if m != nil {
		return m.PreviousTransferBlockProof
	}
	return nil
}

func (m *PlumStartExit) GetPreviousTransferBlockHeight() uint64 {
	if m != nil {
		return m.PreviousTransferBlockHeight
	}
	return 0
}

func (m *PlumStartExit) GetExitTransfer() []byte {
	if m != nil {
		return m.ExitTransfer
	}
	return nil
}

func (m *PlumStartExit) GetExitTransferBlockProof() []byte {
	if m != nil {
		return m.ExitTransferBlockProof
	}
	return nil
}

func (m *PlumStartExit) GetExitTransferBlockHeight() uint64 {
	if m != nil {
		return m.ExitTransferBlockHeight
	}
	return 0
}

type PlumChallengeExit struct {
	SubChainAddress              string   `protobuf:"bytes,1,opt,name=subChainAddress,proto3" json:"subChainAddress,omitempty"`
	CoinID                       uint64   `protobuf:"varint,2,opt,name=coinID,proto3" json:"coinID,omitempty"`
	ChallengeTransfer            []byte   `protobuf:"bytes,3,opt,name=challengeTransfer,proto3" json:"challengeTransfer,omitempty"`
	ChallengeTransferBlockProof  []byte   `protobuf:"bytes,4,opt,name=challengeTransferBlockProof,proto3" json:"challengeTransferBlockProof,omitempty"`
	ChallengeTransferBlockHeight uint64   `protobuf:"varint,5,opt,name=challengeTransferBlockHeight,proto3" json:"challengeTransferBlockHeight,omitempty"`
	XXX_NoUnkeyedLiteral         struct{} `json:"-"`
	XXX_unrecognized             []byte   `json:"-"`
	XXX_sizecache                int32    `json:"-"`
}

func (m *PlumChallengeExit) Reset()         { *m = PlumChallengeExit{} }
func (m *PlumChallengeExit) String() string { return proto.CompactTextString(m) }
func (*PlumChallengeExit) ProtoMessage()    {}
func (*PlumChallengeExit) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4dd5ed50f883f28, []int{24}
}

func (m *PlumChallengeExit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlumChallengeExit.Unmarshal(m, b)
}
func (m *PlumChallengeExit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlumChallengeExit.Marshal(b, m, deterministic)
}
func (m *PlumChallengeExit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlumChallengeExit.Merge(m, src)
}
func (m *PlumChallengeExit) XXX_Size() int {
	return xxx_messageInfo_PlumChallengeExit.Size(m)
}
func (m *PlumChallengeExit) XXX_DiscardUnknown() {
	xxx_messageInfo_PlumChallengeExit.DiscardUnknown(m)
}

var xxx_messageInfo_PlumChallengeExit proto.InternalMessageInfo

func (m *PlumChallengeExit) GetSubChainAddress() string {
	if m != nil {
		return m.SubChainAddress
	}
	return ""
}

func (m *PlumChallengeExit) GetCoinID() uint64 {
	if m != nil {
		return m.CoinID
	}
	return 0
}

func (m *PlumChallengeExit) GetChallengeTransfer() []byte {
	if m != nil {
		return m.ChallengeTransfer
	}
	return nil
}

func (m *PlumChallengeExit) GetChallengeTransferBlockProof() []byte {
	if m != nil {
		return m.ChallengeTransferBlockProof
	}
	return nil
}

func (m *PlumChallengeExit) GetChallengeTransferBlockHeight() uint64 {
	if m != nil {
		return m.ChallengeTransferBlockHeight
	}
	return 0
}

type PlumResponseChallengeExit struct {
	SubChainAddress             string   `protobuf:"bytes,1,opt,name=subChainAddress,proto3" json:"subChainAddress,omitempty"`
	CoinID                      uint64   `protobuf:"varint,2,opt,name=coinID,proto3" json:"coinID,omitempty"`
	ChallengeTransfer           []byte   `protobuf:"bytes,3,opt,name=challengeTransfer,proto3" json:"challengeTransfer,omitempty"`
	ResponseTransfer            []byte   `protobuf:"bytes,4,opt,name=responseTransfer,proto3" json:"responseTransfer,omitempty"`
	ResponseTransferBlockProof  []byte   `protobuf:"bytes,5,opt,name=responseTransferBlockProof,proto3" json:"responseTransferBlockProof,omitempty"`
	PreviousTransferBlockHeight uint64   `protobuf:"varint,6,opt,name=previousTransferBlockHeight,proto3" json:"previousTransferBlockHeight,omitempty"`
	XXX_NoUnkeyedLiteral        struct{} `json:"-"`
	XXX_unrecognized            []byte   `json:"-"`
	XXX_sizecache               int32    `json:"-"`
}

func (m *PlumResponseChallengeExit) Reset()         { *m = PlumResponseChallengeExit{} }
func (m *PlumResponseChallengeExit) String() string { return proto.CompactTextString(m) }
func (*PlumResponseChallengeExit) ProtoMessage()    {}
func (*PlumResponseChallengeExit) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4dd5ed50f883f28, []int{25}
}

func (m *PlumResponseChallengeExit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlumResponseChallengeExit.Unmarshal(m, b)
}
func (m *PlumResponseChallengeExit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlumResponseChallengeExit.Marshal(b, m, deterministic)
}
func (m *PlumResponseChallengeExit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlumResponseChallengeExit.Merge(m, src)
}
func (m *PlumResponseChallengeExit) XXX_Size() int {
	return xxx_messageInfo_PlumResponseChallengeExit.Size(m)
}
func (m *PlumResponseChallengeExit) XXX_DiscardUnknown() {
	xxx_messageInfo_PlumResponseChallengeExit.DiscardUnknown(m)
}

var xxx_messageInfo_PlumResponseChallengeExit proto.InternalMessageInfo

func (m *PlumResponseChallengeExit) GetSubChainAddress() string {
	if m != nil {
		return m.SubChainAddress
	}
	return ""
}

func (m *PlumResponseChallengeExit) GetCoinID() uint64 {
	if m != nil {
		return m.CoinID
	}
	return 0
}

func (m *PlumResponseChallengeExit) GetChallengeTransfer() []byte {
	if m != nil {
		return m.ChallengeTransfer
	}
	return nil
}

func (m *PlumResponseChallengeExit) GetResponseTransfer() []byte {
	if m != nil {
		return m.ResponseTransfer
	}
	return nil
}

func (m *PlumResponseChallengeExit) GetResponseTransferBlockProof() []byte {
	if m != nil {
		return m.ResponseTransferBlockProof
	}
	return nil
}

func (m *PlumResponseChallengeExit) GetPreviousTransferBlockHeight() uint64 {
	if m != nil {
		return m.PreviousTransferBlockHeight
	}
	return 0
}

type PlumFinalizeExit struct {
	SubChainAddress      string   `protobuf:"bytes,1,opt,name=subChainAddress,proto3" json:"subChainAddress,omitempty"`
	CoinID               uint64   `protobuf:"varint,2,opt,name=coinID,proto3" json:"coinID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlumFinalizeExit) Reset()         { *m = PlumFinalizeExit{} }
func (m *PlumFinalizeExit) String() string { return proto.CompactTextString(m) }
func (*PlumFinalizeExit) ProtoMessage()    {}
func (*PlumFinalizeExit) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4dd5ed50f883f28, []int{26}
}

func (m *PlumFinalizeExit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlumFinalizeExit.Unmarshal(m, b)
}
func (m *PlumFinalizeExit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlumFinalizeExit.Marshal(b, m, deterministic)
}
func (m *PlumFinalizeExit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlumFinalizeExit.Merge(m, src)
}
func (m *PlumFinalizeExit) XXX_Size() int {
	return xxx_messageInfo_PlumFinalizeExit.Size(m)
}
func (m *PlumFinalizeExit) XXX_DiscardUnknown() {
	xxx_messageInfo_PlumFinalizeExit.DiscardUnknown(m)
}

var xxx_messageInfo_PlumFinalizeExit proto.InternalMessageInfo

func (m *PlumFinalizeExit) GetSubChainAddress() string {
	if m != nil {
		return m.SubChainAddress
	}
	return ""
}

func (m *PlumFinalizeExit) GetCoinID() uint64 {
	if m != nil {
		return m.CoinID
	}
	return 0
}

// plum sub chain APIs
type PlumSettleDeposit struct {
	CoinID               uint64   `protobuf:"varint,1,opt,name=coinID,proto3" json:"coinID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlumSettleDeposit) Reset()         { *m = PlumSettleDeposit{} }
func (m *PlumSettleDeposit) String() string { return proto.CompactTextString(m) }
func (*PlumSettleDeposit) ProtoMessage()    {}
func (*PlumSettleDeposit) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4dd5ed50f883f28, []int{27}
}

func (m *PlumSettleDeposit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlumSettleDeposit.Unmarshal(m, b)
}
func (m *PlumSettleDeposit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlumSettleDeposit.Marshal(b, m, deterministic)
}
func (m *PlumSettleDeposit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlumSettleDeposit.Merge(m, src)
}
func (m *PlumSettleDeposit) XXX_Size() int {
	return xxx_messageInfo_PlumSettleDeposit.Size(m)
}
func (m *PlumSettleDeposit) XXX_DiscardUnknown() {
	xxx_messageInfo_PlumSettleDeposit.DiscardUnknown(m)
}

var xxx_messageInfo_PlumSettleDeposit proto.InternalMessageInfo

func (m *PlumSettleDeposit) GetCoinID() uint64 {
	if m != nil {
		return m.CoinID
	}
	return 0
}

type PlumTransfer struct {
	CoinID               uint64   `protobuf:"varint,1,opt,name=coinID,proto3" json:"coinID,omitempty"`
	Denomination         []byte   `protobuf:"bytes,2,opt,name=denomination,proto3" json:"denomination,omitempty"`
	Owner                string   `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	Recipient            string   `protobuf:"bytes,4,opt,name=recipient,proto3" json:"recipient,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlumTransfer) Reset()         { *m = PlumTransfer{} }
func (m *PlumTransfer) String() string { return proto.CompactTextString(m) }
func (*PlumTransfer) ProtoMessage()    {}
func (*PlumTransfer) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4dd5ed50f883f28, []int{28}
}

func (m *PlumTransfer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlumTransfer.Unmarshal(m, b)
}
func (m *PlumTransfer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlumTransfer.Marshal(b, m, deterministic)
}
func (m *PlumTransfer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlumTransfer.Merge(m, src)
}
func (m *PlumTransfer) XXX_Size() int {
	return xxx_messageInfo_PlumTransfer.Size(m)
}
func (m *PlumTransfer) XXX_DiscardUnknown() {
	xxx_messageInfo_PlumTransfer.DiscardUnknown(m)
}

var xxx_messageInfo_PlumTransfer proto.InternalMessageInfo

func (m *PlumTransfer) GetCoinID() uint64 {
	if m != nil {
		return m.CoinID
	}
	return 0
}

func (m *PlumTransfer) GetDenomination() []byte {
	if m != nil {
		return m.Denomination
	}
	return nil
}

func (m *PlumTransfer) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *PlumTransfer) GetRecipient() string {
	if m != nil {
		return m.Recipient
	}
	return ""
}

type ActionCore struct {
	Version  uint32 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Nonce    uint64 `protobuf:"varint,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	GasLimit uint64 `protobuf:"varint,3,opt,name=gasLimit,proto3" json:"gasLimit,omitempty"`
	GasPrice string `protobuf:"bytes,4,opt,name=gasPrice,proto3" json:"gasPrice,omitempty"`
	// Types that are valid to be assigned to Action:
	//	*ActionCore_Transfer
	//	*ActionCore_Execution
	//	*ActionCore_StartSubChain
	//	*ActionCore_StopSubChain
	//	*ActionCore_PutBlock
	//	*ActionCore_CreateDeposit
	//	*ActionCore_SettleDeposit
	//	*ActionCore_CreatePlumChain
	//	*ActionCore_TerminatePlumChain
	//	*ActionCore_PlumPutBlock
	//	*ActionCore_PlumCreateDeposit
	//	*ActionCore_PlumStartExit
	//	*ActionCore_PlumChallengeExit
	//	*ActionCore_PlumResponseChallengeExit
	//	*ActionCore_PlumFinalizeExit
	//	*ActionCore_PlumSettleDeposit
	//	*ActionCore_PlumTransfer
	//	*ActionCore_DepositToRewardingFund
	//	*ActionCore_ClaimFromRewardingFund
	//	*ActionCore_GrantReward
	//	*ActionCore_StakeCreate
	//	*ActionCore_StakeUnstake
	//	*ActionCore_StakeWithdraw
	//	*ActionCore_StakeAddstake
	//	*ActionCore_StakeRestake
	//	*ActionCore_StakeChangeCandidate
	//	*ActionCore_StakeTransferOwnership
	//	*ActionCore_PutPollResult
	Action               isActionCore_Action `protobuf_oneof:"action"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ActionCore) Reset()         { *m = ActionCore{} }
func (m *ActionCore) String() string { return proto.CompactTextString(m) }
func (*ActionCore) ProtoMessage()    {}
func (*ActionCore) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4dd5ed50f883f28, []int{29}
}

func (m *ActionCore) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActionCore.Unmarshal(m, b)
}
func (m *ActionCore) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActionCore.Marshal(b, m, deterministic)
}
func (m *ActionCore) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActionCore.Merge(m, src)
}
func (m *ActionCore) XXX_Size() int {
	return xxx_messageInfo_ActionCore.Size(m)
}
func (m *ActionCore) XXX_DiscardUnknown() {
	xxx_messageInfo_ActionCore.DiscardUnknown(m)
}

var xxx_messageInfo_ActionCore proto.InternalMessageInfo

func (m *ActionCore) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *ActionCore) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *ActionCore) GetGasLimit() uint64 {
	if m != nil {
		return m.GasLimit
	}
	return 0
}

func (m *ActionCore) GetGasPrice() string {
	if m != nil {
		return m.GasPrice
	}
	return ""
}

type isActionCore_Action interface {
	isActionCore_Action()
}

type ActionCore_Transfer struct {
	Transfer *Transfer `protobuf:"bytes,10,opt,name=transfer,proto3,oneof"`
}

type ActionCore_Execution struct {
	Execution *Execution `protobuf:"bytes,12,opt,name=execution,proto3,oneof"`
}

type ActionCore_StartSubChain struct {
	StartSubChain *StartSubChain `protobuf:"bytes,13,opt,name=startSubChain,proto3,oneof"`
}

type ActionCore_StopSubChain struct {
	StopSubChain *StopSubChain `protobuf:"bytes,14,opt,name=stopSubChain,proto3,oneof"`
}

type ActionCore_PutBlock struct {
	PutBlock *PutBlock `protobuf:"bytes,15,opt,name=putBlock,proto3,oneof"`
}

type ActionCore_CreateDeposit struct {
	CreateDeposit *CreateDeposit `protobuf:"bytes,16,opt,name=createDeposit,proto3,oneof"`
}

type ActionCore_SettleDeposit struct {
	SettleDeposit *SettleDeposit `protobuf:"bytes,17,opt,name=settleDeposit,proto3,oneof"`
}

type ActionCore_CreatePlumChain struct {
	CreatePlumChain *CreatePlumChain `protobuf:"bytes,18,opt,name=createPlumChain,proto3,oneof"`
}

type ActionCore_TerminatePlumChain struct {
	TerminatePlumChain *TerminatePlumChain `protobuf:"bytes,19,opt,name=terminatePlumChain,proto3,oneof"`
}

type ActionCore_PlumPutBlock struct {
	PlumPutBlock *PlumPutBlock `protobuf:"bytes,20,opt,name=plumPutBlock,proto3,oneof"`
}

type ActionCore_PlumCreateDeposit struct {
	PlumCreateDeposit *PlumCreateDeposit `protobuf:"bytes,21,opt,name=plumCreateDeposit,proto3,oneof"`
}

type ActionCore_PlumStartExit struct {
	PlumStartExit *PlumStartExit `protobuf:"bytes,22,opt,name=plumStartExit,proto3,oneof"`
}

type ActionCore_PlumChallengeExit struct {
	PlumChallengeExit *PlumChallengeExit `protobuf:"bytes,23,opt,name=plumChallengeExit,proto3,oneof"`
}

type ActionCore_PlumResponseChallengeExit struct {
	PlumResponseChallengeExit *PlumResponseChallengeExit `protobuf:"bytes,24,opt,name=plumResponseChallengeExit,proto3,oneof"`
}

type ActionCore_PlumFinalizeExit struct {
	PlumFinalizeExit *PlumFinalizeExit `protobuf:"bytes,25,opt,name=plumFinalizeExit,proto3,oneof"`
}

type ActionCore_PlumSettleDeposit struct {
	PlumSettleDeposit *PlumSettleDeposit `protobuf:"bytes,26,opt,name=plumSettleDeposit,proto3,oneof"`
}

type ActionCore_PlumTransfer struct {
	PlumTransfer *PlumTransfer `protobuf:"bytes,27,opt,name=plumTransfer,proto3,oneof"`
}

type ActionCore_DepositToRewardingFund struct {
	DepositToRewardingFund *DepositToRewardingFund `protobuf:"bytes,30,opt,name=depositToRewardingFund,proto3,oneof"`
}

type ActionCore_ClaimFromRewardingFund struct {
	ClaimFromRewardingFund *ClaimFromRewardingFund `protobuf:"bytes,31,opt,name=claimFromRewardingFund,proto3,oneof"`
}

type ActionCore_GrantReward struct {
	GrantReward *GrantReward `protobuf:"bytes,32,opt,name=grantReward,proto3,oneof"`
}

type ActionCore_StakeCreate struct {
	StakeCreate *StakeCreate `protobuf:"bytes,40,opt,name=stakeCreate,proto3,oneof"`
}

type ActionCore_StakeUnstake struct {
	StakeUnstake *StakeUpdate `protobuf:"bytes,41,opt,name=stakeUnstake,proto3,oneof"`
}

type ActionCore_StakeWithdraw struct {
	StakeWithdraw *StakeUpdate `protobuf:"bytes,42,opt,name=stakeWithdraw,proto3,oneof"`
}

type ActionCore_StakeAddstake struct {
	StakeAddstake *StakeAddDeposit `protobuf:"bytes,43,opt,name=stakeAddstake,proto3,oneof"`
}

type ActionCore_StakeRestake struct {
	StakeRestake *StakeAgain `protobuf:"bytes,44,opt,name=stakeRestake,proto3,oneof"`
}

type ActionCore_StakeChangeCandidate struct {
	StakeChangeCandidate *StakeMove `protobuf:"bytes,45,opt,name=stakeChangeCandidate,proto3,oneof"`
}

type ActionCore_StakeTransferOwnership struct {
	StakeTransferOwnership *StakeMove `protobuf:"bytes,46,opt,name=stakeTransferOwnership,proto3,oneof"`
}

type ActionCore_PutPollResult struct {
	PutPollResult *PutPollResult `protobuf:"bytes,50,opt,name=putPollResult,proto3,oneof"`
}

func (*ActionCore_Transfer) isActionCore_Action() {}

func (*ActionCore_Execution) isActionCore_Action() {}

func (*ActionCore_StartSubChain) isActionCore_Action() {}

func (*ActionCore_StopSubChain) isActionCore_Action() {}

func (*ActionCore_PutBlock) isActionCore_Action() {}

func (*ActionCore_CreateDeposit) isActionCore_Action() {}

func (*ActionCore_SettleDeposit) isActionCore_Action() {}

func (*ActionCore_CreatePlumChain) isActionCore_Action() {}

func (*ActionCore_TerminatePlumChain) isActionCore_Action() {}

func (*ActionCore_PlumPutBlock) isActionCore_Action() {}

func (*ActionCore_PlumCreateDeposit) isActionCore_Action() {}

func (*ActionCore_PlumStartExit) isActionCore_Action() {}

func (*ActionCore_PlumChallengeExit) isActionCore_Action() {}

func (*ActionCore_PlumResponseChallengeExit) isActionCore_Action() {}

func (*ActionCore_PlumFinalizeExit) isActionCore_Action() {}

func (*ActionCore_PlumSettleDeposit) isActionCore_Action() {}

func (*ActionCore_PlumTransfer) isActionCore_Action() {}

func (*ActionCore_DepositToRewardingFund) isActionCore_Action() {}

func (*ActionCore_ClaimFromRewardingFund) isActionCore_Action() {}

func (*ActionCore_GrantReward) isActionCore_Action() {}

func (*ActionCore_StakeCreate) isActionCore_Action() {}

func (*ActionCore_StakeUnstake) isActionCore_Action() {}

func (*ActionCore_StakeWithdraw) isActionCore_Action() {}

func (*ActionCore_StakeAddstake) isActionCore_Action() {}

func (*ActionCore_StakeRestake) isActionCore_Action() {}

func (*ActionCore_StakeChangeCandidate) isActionCore_Action() {}

func (*ActionCore_StakeTransferOwnership) isActionCore_Action() {}

func (*ActionCore_PutPollResult) isActionCore_Action() {}

func (m *ActionCore) GetAction() isActionCore_Action {
	if m != nil {
		return m.Action
	}
	return nil
}

func (m *ActionCore) GetTransfer() *Transfer {
	if x, ok := m.GetAction().(*ActionCore_Transfer); ok {
		return x.Transfer
	}
	return nil
}

func (m *ActionCore) GetExecution() *Execution {
	if x, ok := m.GetAction().(*ActionCore_Execution); ok {
		return x.Execution
	}
	return nil
}

func (m *ActionCore) GetStartSubChain() *StartSubChain {
	if x, ok := m.GetAction().(*ActionCore_StartSubChain); ok {
		return x.StartSubChain
	}
	return nil
}

func (m *ActionCore) GetStopSubChain() *StopSubChain {
	if x, ok := m.GetAction().(*ActionCore_StopSubChain); ok {
		return x.StopSubChain
	}
	return nil
}

func (m *ActionCore) GetPutBlock() *PutBlock {
	if x, ok := m.GetAction().(*ActionCore_PutBlock); ok {
		return x.PutBlock
	}
	return nil
}

func (m *ActionCore) GetCreateDeposit() *CreateDeposit {
	if x, ok := m.GetAction().(*ActionCore_CreateDeposit); ok {
		return x.CreateDeposit
	}
	return nil
}

func (m *ActionCore) GetSettleDeposit() *SettleDeposit {
	if x, ok := m.GetAction().(*ActionCore_SettleDeposit); ok {
		return x.SettleDeposit
	}
	return nil
}

func (m *ActionCore) GetCreatePlumChain() *CreatePlumChain {
	if x, ok := m.GetAction().(*ActionCore_CreatePlumChain); ok {
		return x.CreatePlumChain
	}
	return nil
}

func (m *ActionCore) GetTerminatePlumChain() *TerminatePlumChain {
	if x, ok := m.GetAction().(*ActionCore_TerminatePlumChain); ok {
		return x.TerminatePlumChain
	}
	return nil
}

func (m *ActionCore) GetPlumPutBlock() *PlumPutBlock {
	if x, ok := m.GetAction().(*ActionCore_PlumPutBlock); ok {
		return x.PlumPutBlock
	}
	return nil
}

func (m *ActionCore) GetPlumCreateDeposit() *PlumCreateDeposit {
	if x, ok := m.GetAction().(*ActionCore_PlumCreateDeposit); ok {
		return x.PlumCreateDeposit
	}
	return nil
}

func (m *ActionCore) GetPlumStartExit() *PlumStartExit {
	if x, ok := m.GetAction().(*ActionCore_PlumStartExit); ok {
		return x.PlumStartExit
	}
	return nil
}

func (m *ActionCore) GetPlumChallengeExit() *PlumChallengeExit {
	if x, ok := m.GetAction().(*ActionCore_PlumChallengeExit); ok {
		return x.PlumChallengeExit
	}
	return nil
}

func (m *ActionCore) GetPlumResponseChallengeExit() *PlumResponseChallengeExit {
	if x, ok := m.GetAction().(*ActionCore_PlumResponseChallengeExit); ok {
		return x.PlumResponseChallengeExit
	}
	return nil
}

func (m *ActionCore) GetPlumFinalizeExit() *PlumFinalizeExit {
	if x, ok := m.GetAction().(*ActionCore_PlumFinalizeExit); ok {
		return x.PlumFinalizeExit
	}
	return nil
}

func (m *ActionCore) GetPlumSettleDeposit() *PlumSettleDeposit {
	if x, ok := m.GetAction().(*ActionCore_PlumSettleDeposit); ok {
		return x.PlumSettleDeposit
	}
	return nil
}

func (m *ActionCore) GetPlumTransfer() *PlumTransfer {
	if x, ok := m.GetAction().(*ActionCore_PlumTransfer); ok {
		return x.PlumTransfer
	}
	return nil
}

func (m *ActionCore) GetDepositToRewardingFund() *DepositToRewardingFund {
	if x, ok := m.GetAction().(*ActionCore_DepositToRewardingFund); ok {
		return x.DepositToRewardingFund
	}
	return nil
}

func (m *ActionCore) GetClaimFromRewardingFund() *ClaimFromRewardingFund {
	if x, ok := m.GetAction().(*ActionCore_ClaimFromRewardingFund); ok {
		return x.ClaimFromRewardingFund
	}
	return nil
}

func (m *ActionCore) GetGrantReward() *GrantReward {
	if x, ok := m.GetAction().(*ActionCore_GrantReward); ok {
		return x.GrantReward
	}
	return nil
}

func (m *ActionCore) GetStakeCreate() *StakeCreate {
	if x, ok := m.GetAction().(*ActionCore_StakeCreate); ok {
		return x.StakeCreate
	}
	return nil
}

func (m *ActionCore) GetStakeUnstake() *StakeUpdate {
	if x, ok := m.GetAction().(*ActionCore_StakeUnstake); ok {
		return x.StakeUnstake
	}
	return nil
}

func (m *ActionCore) GetStakeWithdraw() *StakeUpdate {
	if x, ok := m.GetAction().(*ActionCore_StakeWithdraw); ok {
		return x.StakeWithdraw
	}
	return nil
}

func (m *ActionCore) GetStakeAddstake() *StakeAddDeposit {
	if x, ok := m.GetAction().(*ActionCore_StakeAddstake); ok {
		return x.StakeAddstake
	}
	return nil
}

func (m *ActionCore) GetStakeRestake() *StakeAgain {
	if x, ok := m.GetAction().(*ActionCore_StakeRestake); ok {
		return x.StakeRestake
	}
	return nil
}

func (m *ActionCore) GetStakeChangeCandidate() *StakeMove {
	if x, ok := m.GetAction().(*ActionCore_StakeChangeCandidate); ok {
		return x.StakeChangeCandidate
	}
	return nil
}

func (m *ActionCore) GetStakeTransferOwnership() *StakeMove {
	if x, ok := m.GetAction().(*ActionCore_StakeTransferOwnership); ok {
		return x.StakeTransferOwnership
	}
	return nil
}

func (m *ActionCore) GetPutPollResult() *PutPollResult {
	if x, ok := m.GetAction().(*ActionCore_PutPollResult); ok {
		return x.PutPollResult
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ActionCore) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ActionCore_Transfer)(nil),
		(*ActionCore_Execution)(nil),
		(*ActionCore_StartSubChain)(nil),
		(*ActionCore_StopSubChain)(nil),
		(*ActionCore_PutBlock)(nil),
		(*ActionCore_CreateDeposit)(nil),
		(*ActionCore_SettleDeposit)(nil),
		(*ActionCore_CreatePlumChain)(nil),
		(*ActionCore_TerminatePlumChain)(nil),
		(*ActionCore_PlumPutBlock)(nil),
		(*ActionCore_PlumCreateDeposit)(nil),
		(*ActionCore_PlumStartExit)(nil),
		(*ActionCore_PlumChallengeExit)(nil),
		(*ActionCore_PlumResponseChallengeExit)(nil),
		(*ActionCore_PlumFinalizeExit)(nil),
		(*ActionCore_PlumSettleDeposit)(nil),
		(*ActionCore_PlumTransfer)(nil),
		(*ActionCore_DepositToRewardingFund)(nil),
		(*ActionCore_ClaimFromRewardingFund)(nil),
		(*ActionCore_GrantReward)(nil),
		(*ActionCore_StakeCreate)(nil),
		(*ActionCore_StakeUnstake)(nil),
		(*ActionCore_StakeWithdraw)(nil),
		(*ActionCore_StakeAddstake)(nil),
		(*ActionCore_StakeRestake)(nil),
		(*ActionCore_StakeChangeCandidate)(nil),
		(*ActionCore_StakeTransferOwnership)(nil),
		(*ActionCore_PutPollResult)(nil),
	}
}

type Action struct {
	Core                 *ActionCore `protobuf:"bytes,1,opt,name=core,proto3" json:"core,omitempty"`
	SenderPubKey         []byte      `protobuf:"bytes,2,opt,name=senderPubKey,proto3" json:"senderPubKey,omitempty"`
	Signature            []byte      `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Action) Reset()         { *m = Action{} }
func (m *Action) String() string { return proto.CompactTextString(m) }
func (*Action) ProtoMessage()    {}
func (*Action) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4dd5ed50f883f28, []int{30}
}

func (m *Action) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Action.Unmarshal(m, b)
}
func (m *Action) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Action.Marshal(b, m, deterministic)
}
func (m *Action) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Action.Merge(m, src)
}
func (m *Action) XXX_Size() int {
	return xxx_messageInfo_Action.Size(m)
}
func (m *Action) XXX_DiscardUnknown() {
	xxx_messageInfo_Action.DiscardUnknown(m)
}

var xxx_messageInfo_Action proto.InternalMessageInfo

func (m *Action) GetCore() *ActionCore {
	if m != nil {
		return m.Core
	}
	return nil
}

func (m *Action) GetSenderPubKey() []byte {
	if m != nil {
		return m.SenderPubKey
	}
	return nil
}

func (m *Action) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type Receipt struct {
	Status               uint64   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	BlkHeight            uint64   `protobuf:"varint,2,opt,name=blkHeight,proto3" json:"blkHeight,omitempty"`
	ActHash              []byte   `protobuf:"bytes,3,opt,name=actHash,proto3" json:"actHash,omitempty"`
	GasConsumed          uint64   `protobuf:"varint,4,opt,name=gasConsumed,proto3" json:"gasConsumed,omitempty"`
	ContractAddress      string   `protobuf:"bytes,5,opt,name=contractAddress,proto3" json:"contractAddress,omitempty"`
	Logs                 []*Log   `protobuf:"bytes,6,rep,name=logs,proto3" json:"logs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Receipt) Reset()         { *m = Receipt{} }
func (m *Receipt) String() string { return proto.CompactTextString(m) }
func (*Receipt) ProtoMessage()    {}
func (*Receipt) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4dd5ed50f883f28, []int{31}
}

func (m *Receipt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Receipt.Unmarshal(m, b)
}
func (m *Receipt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Receipt.Marshal(b, m, deterministic)
}
func (m *Receipt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Receipt.Merge(m, src)
}
func (m *Receipt) XXX_Size() int {
	return xxx_messageInfo_Receipt.Size(m)
}
func (m *Receipt) XXX_DiscardUnknown() {
	xxx_messageInfo_Receipt.DiscardUnknown(m)
}

var xxx_messageInfo_Receipt proto.InternalMessageInfo

func (m *Receipt) GetStatus() uint64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Receipt) GetBlkHeight() uint64 {
	if m != nil {
		return m.BlkHeight
	}
	return 0
}

func (m *Receipt) GetActHash() []byte {
	if m != nil {
		return m.ActHash
	}
	return nil
}

func (m *Receipt) GetGasConsumed() uint64 {
	if m != nil {
		return m.GasConsumed
	}
	return 0
}

func (m *Receipt) GetContractAddress() string {
	if m != nil {
		return m.ContractAddress
	}
	return ""
}

func (m *Receipt) GetLogs() []*Log {
	if m != nil {
		return m.Logs
	}
	return nil
}

type Log struct {
	ContractAddress      string   `protobuf:"bytes,1,opt,name=contractAddress,proto3" json:"contractAddress,omitempty"`
	Topics               [][]byte `protobuf:"bytes,2,rep,name=topics,proto3" json:"topics,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	BlkHeight            uint64   `protobuf:"varint,4,opt,name=blkHeight,proto3" json:"blkHeight,omitempty"`
	ActHash              []byte   `protobuf:"bytes,5,opt,name=actHash,proto3" json:"actHash,omitempty"`
	Index                uint32   `protobuf:"varint,6,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Log) Reset()         { *m = Log{} }
func (m *Log) String() string { return proto.CompactTextString(m) }
func (*Log) ProtoMessage()    {}
func (*Log) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4dd5ed50f883f28, []int{32}
}

func (m *Log) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Log.Unmarshal(m, b)
}
func (m *Log) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Log.Marshal(b, m, deterministic)
}
func (m *Log) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Log.Merge(m, src)
}
func (m *Log) XXX_Size() int {
	return xxx_messageInfo_Log.Size(m)
}
func (m *Log) XXX_DiscardUnknown() {
	xxx_messageInfo_Log.DiscardUnknown(m)
}

var xxx_messageInfo_Log proto.InternalMessageInfo

func (m *Log) GetContractAddress() string {
	if m != nil {
		return m.ContractAddress
	}
	return ""
}

func (m *Log) GetTopics() [][]byte {
	if m != nil {
		return m.Topics
	}
	return nil
}

func (m *Log) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Log) GetBlkHeight() uint64 {
	if m != nil {
		return m.BlkHeight
	}
	return 0
}

func (m *Log) GetActHash() []byte {
	if m != nil {
		return m.ActHash
	}
	return nil
}

func (m *Log) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

type DepositToRewardingFund struct {
	Amount               string   `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DepositToRewardingFund) Reset()         { *m = DepositToRewardingFund{} }
func (m *DepositToRewardingFund) String() string { return proto.CompactTextString(m) }
func (*DepositToRewardingFund) ProtoMessage()    {}
func (*DepositToRewardingFund) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4dd5ed50f883f28, []int{33}
}

func (m *DepositToRewardingFund) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DepositToRewardingFund.Unmarshal(m, b)
}
func (m *DepositToRewardingFund) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DepositToRewardingFund.Marshal(b, m, deterministic)
}
func (m *DepositToRewardingFund) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DepositToRewardingFund.Merge(m, src)
}
func (m *DepositToRewardingFund) XXX_Size() int {
	return xxx_messageInfo_DepositToRewardingFund.Size(m)
}
func (m *DepositToRewardingFund) XXX_DiscardUnknown() {
	xxx_messageInfo_DepositToRewardingFund.DiscardUnknown(m)
}

var xxx_messageInfo_DepositToRewardingFund proto.InternalMessageInfo

func (m *DepositToRewardingFund) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *DepositToRewardingFund) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type ClaimFromRewardingFund struct {
	Amount               string   `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClaimFromRewardingFund) Reset()         { *m = ClaimFromRewardingFund{} }
func (m *ClaimFromRewardingFund) String() string { return proto.CompactTextString(m) }
func (*ClaimFromRewardingFund) ProtoMessage()    {}
func (*ClaimFromRewardingFund) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4dd5ed50f883f28, []int{34}
}

func (m *ClaimFromRewardingFund) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClaimFromRewardingFund.Unmarshal(m, b)
}
func (m *ClaimFromRewardingFund) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClaimFromRewardingFund.Marshal(b, m, deterministic)
}
func (m *ClaimFromRewardingFund) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClaimFromRewardingFund.Merge(m, src)
}
func (m *ClaimFromRewardingFund) XXX_Size() int {
	return xxx_messageInfo_ClaimFromRewardingFund.Size(m)
}
func (m *ClaimFromRewardingFund) XXX_DiscardUnknown() {
	xxx_messageInfo_ClaimFromRewardingFund.DiscardUnknown(m)
}

var xxx_messageInfo_ClaimFromRewardingFund proto.InternalMessageInfo

func (m *ClaimFromRewardingFund) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *ClaimFromRewardingFund) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type GrantReward struct {
	Type                 RewardType `protobuf:"varint,1,opt,name=type,proto3,enum=iotextypes.RewardType" json:"type,omitempty"`
	Height               uint64     `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GrantReward) Reset()         { *m = GrantReward{} }
func (m *GrantReward) String() string { return proto.CompactTextString(m) }
func (*GrantReward) ProtoMessage()    {}
func (*GrantReward) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4dd5ed50f883f28, []int{35}
}

func (m *GrantReward) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GrantReward.Unmarshal(m, b)
}
func (m *GrantReward) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GrantReward.Marshal(b, m, deterministic)
}
func (m *GrantReward) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrantReward.Merge(m, src)
}
func (m *GrantReward) XXX_Size() int {
	return xxx_messageInfo_GrantReward.Size(m)
}
func (m *GrantReward) XXX_DiscardUnknown() {
	xxx_messageInfo_GrantReward.DiscardUnknown(m)
}

var xxx_messageInfo_GrantReward proto.InternalMessageInfo

func (m *GrantReward) GetType() RewardType {
	if m != nil {
		return m.Type
	}
	return RewardType_BlockReward
}

func (m *GrantReward) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func init() {
	proto.RegisterEnum("iotextypes.StakeUpdateType", StakeUpdateType_name, StakeUpdateType_value)
	proto.RegisterEnum("iotextypes.StakeMoveType", StakeMoveType_name, StakeMoveType_value)
	proto.RegisterEnum("iotextypes.RewardType", RewardType_name, RewardType_value)
	proto.RegisterType((*Transfer)(nil), "iotextypes.Transfer")
	proto.RegisterType((*Candidate)(nil), "iotextypes.Candidate")
	proto.RegisterType((*CandidateList)(nil), "iotextypes.CandidateList")
	proto.RegisterType((*KickoutCandidateList)(nil), "iotextypes.KickoutCandidateList")
	proto.RegisterType((*KickoutInfo)(nil), "iotextypes.KickoutInfo")
	proto.RegisterType((*PutPollResult)(nil), "iotextypes.PutPollResult")
	proto.RegisterType((*Execution)(nil), "iotextypes.Execution")
	proto.RegisterType((*Bucket)(nil), "iotextypes.Bucket")
	proto.RegisterType((*StakeCreate)(nil), "iotextypes.StakeCreate")
	proto.RegisterType((*StakeUpdate)(nil), "iotextypes.StakeUpdate")
	proto.RegisterType((*StakeAddDeposit)(nil), "iotextypes.StakeAddDeposit")
	proto.RegisterType((*StakeAgain)(nil), "iotextypes.StakeAgain")
	proto.RegisterType((*StakeMove)(nil), "iotextypes.StakeMove")
	proto.RegisterType((*StartSubChain)(nil), "iotextypes.StartSubChain")
	proto.RegisterType((*StopSubChain)(nil), "iotextypes.StopSubChain")
	proto.RegisterType((*MerkleRoot)(nil), "iotextypes.MerkleRoot")
	proto.RegisterType((*PutBlock)(nil), "iotextypes.PutBlock")
	proto.RegisterType((*CreateDeposit)(nil), "iotextypes.CreateDeposit")
	proto.RegisterType((*SettleDeposit)(nil), "iotextypes.SettleDeposit")
	proto.RegisterType((*CreatePlumChain)(nil), "iotextypes.CreatePlumChain")
	proto.RegisterType((*TerminatePlumChain)(nil), "iotextypes.TerminatePlumChain")
	proto.RegisterType((*PlumPutBlock)(nil), "iotextypes.PlumPutBlock")
	proto.RegisterMapType((map[string][]byte)(nil), "iotextypes.PlumPutBlock.RootsEntry")
	proto.RegisterType((*PlumCreateDeposit)(nil), "iotextypes.PlumCreateDeposit")
	proto.RegisterType((*PlumStartExit)(nil), "iotextypes.PlumStartExit")
	proto.RegisterType((*PlumChallengeExit)(nil), "iotextypes.PlumChallengeExit")
	proto.RegisterType((*PlumResponseChallengeExit)(nil), "iotextypes.PlumResponseChallengeExit")
	proto.RegisterType((*PlumFinalizeExit)(nil), "iotextypes.PlumFinalizeExit")
	proto.RegisterType((*PlumSettleDeposit)(nil), "iotextypes.PlumSettleDeposit")
	proto.RegisterType((*PlumTransfer)(nil), "iotextypes.PlumTransfer")
	proto.RegisterType((*ActionCore)(nil), "iotextypes.ActionCore")
	proto.RegisterType((*Action)(nil), "iotextypes.Action")
	proto.RegisterType((*Receipt)(nil), "iotextypes.Receipt")
	proto.RegisterType((*Log)(nil), "iotextypes.Log")
	proto.RegisterType((*DepositToRewardingFund)(nil), "iotextypes.DepositToRewardingFund")
	proto.RegisterType((*ClaimFromRewardingFund)(nil), "iotextypes.ClaimFromRewardingFund")
	proto.RegisterType((*GrantReward)(nil), "iotextypes.GrantReward")
}

func init() { proto.RegisterFile("proto/types/action.proto", fileDescriptor_d4dd5ed50f883f28) }

var fileDescriptor_d4dd5ed50f883f28 = []byte{
	// 2142 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x59, 0x5f, 0x6f, 0xdb, 0xc8,
	0x11, 0x17, 0x25, 0x59, 0xb6, 0x47, 0x56, 0x2c, 0xef, 0x39, 0x0a, 0xe3, 0xa4, 0x39, 0x83, 0xd7,
	0x16, 0xae, 0x2f, 0x91, 0x01, 0x17, 0xb9, 0xcb, 0xdd, 0xf5, 0xd2, 0xfa, 0x4f, 0x7c, 0x4a, 0x93,
	0x34, 0xee, 0xda, 0x87, 0x02, 0xd7, 0x02, 0x05, 0x4d, 0xad, 0x25, 0xd6, 0x12, 0x97, 0x20, 0x97,
	0x8e, 0x9d, 0x87, 0xbe, 0xb7, 0x0f, 0xfd, 0x1e, 0xfd, 0x04, 0x45, 0x5f, 0xfa, 0xd6, 0x97, 0xbe,
	0xf5, 0xcb, 0xf4, 0xad, 0xc0, 0x61, 0xff, 0x90, 0xdc, 0x25, 0x29, 0x39, 0x39, 0x1c, 0x70, 0x6f,
	0x9a, 0xd9, 0x99, 0xdf, 0xce, 0xcc, 0xce, 0xce, 0x0e, 0x47, 0x60, 0x87, 0x11, 0x65, 0x74, 0x87,
	0x5d, 0x87, 0x24, 0xde, 0x71, 0x3d, 0xe6, 0xd3, 0xa0, 0x2f, 0x58, 0x08, 0x7c, 0xca, 0xc8, 0x95,
	0x58, 0xd8, 0xf8, 0x70, 0x44, 0xe9, 0x68, 0x42, 0x76, 0xc4, 0xca, 0x59, 0x72, 0xbe, 0xc3, 0xfc,
	0x29, 0x89, 0x99, 0x3b, 0x0d, 0xa5, 0xb0, 0xf3, 0x0d, 0x2c, 0x9d, 0x46, 0x6e, 0x10, 0x9f, 0x93,
	0x08, 0xf5, 0xa0, 0xe5, 0x4e, 0x69, 0x12, 0x30, 0xdb, 0xda, 0xb4, 0xb6, 0x96, 0xb1, 0xa2, 0xd0,
	0x7d, 0x58, 0x8e, 0x88, 0xe7, 0x87, 0x3e, 0x09, 0x98, 0x5d, 0x17, 0x4b, 0x39, 0x03, 0xd9, 0xb0,
	0x18, 0xba, 0xd7, 0x13, 0xea, 0x0e, 0xed, 0xc6, 0xa6, 0xb5, 0xb5, 0x82, 0x53, 0xd2, 0xb9, 0x86,
	0xe5, 0x03, 0x37, 0x18, 0xfa, 0x43, 0x97, 0x11, 0x2e, 0xe6, 0x0e, 0x87, 0x11, 0x89, 0x63, 0x85,
	0x9e, 0x92, 0x68, 0x1d, 0x16, 0x2e, 0x29, 0x23, 0xb1, 0x80, 0x5e, 0xc1, 0x92, 0xe0, 0xc6, 0x84,
	0xc9, 0xd9, 0x0b, 0x72, 0xad, 0x50, 0x15, 0x85, 0x7e, 0x0c, 0x9d, 0x88, 0xbc, 0x71, 0xa3, 0xe1,
	0x9e, 0x42, 0x6b, 0x0a, 0x34, 0x93, 0xe9, 0x1c, 0x41, 0x27, 0xdb, 0xfa, 0xa5, 0x1f, 0x33, 0xf4,
	0x18, 0xc0, 0x4b, 0x19, 0xdc, 0x82, 0xc6, 0x56, 0x7b, 0xf7, 0x76, 0x3f, 0x8f, 0x54, 0x3f, 0x13,
	0xc7, 0x9a, 0xa0, 0x93, 0xc0, 0xfa, 0x0b, 0xdf, 0xbb, 0xa0, 0x09, 0x33, 0xe1, 0x3e, 0x05, 0x38,
	0x9b, 0xb8, 0xde, 0xc5, 0xc4, 0x8f, 0x59, 0x0a, 0x77, 0x47, 0x87, 0x53, 0x5a, 0xcf, 0x83, 0x73,
	0x8a, 0x35, 0x51, 0x6e, 0xbe, 0x1f, 0x30, 0x12, 0xc4, 0x3e, 0xbb, 0xc6, 0x2e, 0x23, 0xc2, 0xe9,
	0x0e, 0x36, 0x99, 0xce, 0x97, 0xd0, 0xd6, 0x00, 0xe6, 0xc7, 0xce, 0x13, 0x27, 0x26, 0x61, 0x24,
	0xe1, 0x9c, 0x41, 0xe7, 0x38, 0x61, 0xc7, 0x74, 0x32, 0xc1, 0x24, 0x4e, 0x26, 0x8c, 0x07, 0x73,
	0x4c, 0xfc, 0xd1, 0x58, 0x9e, 0x6c, 0x13, 0x2b, 0x0a, 0x7d, 0x66, 0x44, 0x85, 0x63, 0xb4, 0x77,
	0xef, 0x56, 0x46, 0x85, 0x7b, 0x6d, 0x44, 0xe6, 0x04, 0x96, 0x9f, 0x5d, 0x11, 0x2f, 0xe1, 0x89,
	0x37, 0x33, 0x73, 0x36, 0x60, 0xc9, 0xa3, 0x01, 0x8b, 0x5c, 0x2f, 0x4d, 0x9c, 0x8c, 0x46, 0x08,
	0x9a, 0x43, 0x97, 0xb9, 0xea, 0x78, 0xc5, 0x6f, 0xe7, 0x7f, 0x75, 0x68, 0xed, 0x27, 0xde, 0x05,
	0x61, 0x3c, 0x50, 0xd9, 0x6e, 0xbf, 0x71, 0xa7, 0x44, 0x21, 0x9b, 0x4c, 0xe4, 0xc0, 0x4a, 0xcc,
	0xdc, 0x0b, 0x32, 0xdc, 0x9b, 0x66, 0x61, 0x58, 0xc6, 0x06, 0x0f, 0xfd, 0x14, 0x6e, 0x49, 0xfa,
	0x30, 0x89, 0x5c, 0x6e, 0xae, 0xd8, 0xb2, 0x83, 0x0b, 0x5c, 0xf4, 0x39, 0x80, 0x17, 0x11, 0x97,
	0x91, 0x53, 0x7f, 0x4a, 0x44, 0x5a, 0xb5, 0x77, 0x37, 0xfa, 0xf2, 0x02, 0xf5, 0xd3, 0x0b, 0xd4,
	0x3f, 0x4d, 0x2f, 0x10, 0xd6, 0xa4, 0xd1, 0xbe, 0xda, 0xe3, 0x84, 0xb9, 0x11, 0x13, 0xfa, 0x0b,
	0x37, 0xea, 0x17, 0x34, 0xd0, 0x11, 0x74, 0x93, 0xa0, 0x80, 0xd2, 0xba, 0x11, 0xa5, 0xa4, 0xc3,
	0xaf, 0xab, 0x9b, 0x30, 0x7a, 0xc2, 0xb9, 0xf6, 0xe2, 0xa6, 0xb5, 0xb5, 0x84, 0x73, 0x06, 0xcf,
	0x18, 0xfa, 0x26, 0x20, 0x91, 0xbd, 0x24, 0x42, 0x25, 0x09, 0xe7, 0x1f, 0x16, 0xb4, 0xc5, 0xfa,
	0x81, 0xf0, 0xe9, 0x07, 0x88, 0xbe, 0x61, 0x75, 0xb3, 0x68, 0xb5, 0x56, 0x64, 0x16, 0xcc, 0x22,
	0xf3, 0x56, 0x19, 0xfe, 0x75, 0x28, 0xca, 0xcc, 0x0e, 0x34, 0x79, 0xe6, 0x0a, 0x7b, 0x6f, 0xed,
	0xde, 0xd3, 0x73, 0x59, 0x13, 0x3b, 0xbd, 0x0e, 0x09, 0x16, 0x82, 0x68, 0x13, 0xda, 0x67, 0x22,
	0xe3, 0x9e, 0x07, 0x43, 0x72, 0x25, 0x5c, 0x68, 0x62, 0x9d, 0x35, 0xa7, 0xc0, 0x11, 0x58, 0x15,
	0xa0, 0x7b, 0xc3, 0xe1, 0x21, 0x09, 0x69, 0xec, 0xb3, 0x22, 0x9c, 0x55, 0x86, 0xcb, 0xef, 0x4a,
	0xdd, 0xb8, 0x2b, 0xb3, 0xb7, 0xf9, 0x9b, 0x05, 0x20, 0xf7, 0x19, 0xb9, 0x7e, 0xf0, 0x0e, 0x5b,
	0x94, 0x63, 0x5e, 0xbf, 0x39, 0xe6, 0x8d, 0x39, 0x31, 0x6f, 0x9a, 0x06, 0xfd, 0xd5, 0x82, 0x65,
	0x21, 0xf3, 0x8a, 0x5e, 0x12, 0xf4, 0xc8, 0x08, 0xf9, 0xdd, 0x52, 0xc8, 0xb9, 0x90, 0x16, 0x70,
	0x04, 0xcd, 0x80, 0x67, 0x94, 0xf4, 0x5e, 0xfc, 0x2e, 0xba, 0xd4, 0x98, 0x7b, 0x08, 0x05, 0x63,
	0xfe, 0x6b, 0x41, 0x47, 0x24, 0xff, 0x49, 0x72, 0x76, 0x30, 0xe6, 0x01, 0xb2, 0x61, 0xd1, 0xe3,
	0x3f, 0x9e, 0x1f, 0x0a, 0x9b, 0x3a, 0x38, 0x25, 0xd1, 0x16, 0xac, 0xc6, 0xc4, 0x4b, 0x22, 0x9f,
	0x5d, 0xab, 0x03, 0x53, 0x66, 0x14, 0xd9, 0x68, 0x1b, 0xba, 0x34, 0x24, 0x32, 0x4e, 0xa9, 0x68,
	0x43, 0x88, 0x96, 0xf8, 0xdc, 0xfa, 0x98, 0x1b, 0x30, 0x90, 0x25, 0xb6, 0x29, 0xad, 0xd7, 0x58,
	0xa8, 0x0f, 0x28, 0x74, 0x23, 0x12, 0x28, 0xfa, 0xf5, 0xf9, 0x79, 0x4c, 0x98, 0xc8, 0xe4, 0x26,
	0xae, 0x58, 0x71, 0x22, 0x58, 0x39, 0x61, 0x34, 0x7c, 0x07, 0x8f, 0x1e, 0x00, 0xc4, 0x8c, 0x86,
	0x6a, 0x6b, 0x99, 0xbd, 0x1a, 0x47, 0x78, 0xac, 0x50, 0xd2, 0x07, 0xb3, 0xa1, 0x3c, 0x36, 0xd9,
	0xce, 0x27, 0x00, 0xaf, 0x48, 0x74, 0x31, 0x21, 0x98, 0x52, 0x96, 0x9d, 0x92, 0xa5, 0x9d, 0x12,
	0x7f, 0xa8, 0xdd, 0x49, 0x42, 0xb2, 0x87, 0x9a, 0x13, 0xce, 0x5b, 0x58, 0x3a, 0x4e, 0xd8, 0xfe,
	0x84, 0x7a, 0x17, 0x55, 0xbb, 0x59, 0x95, 0xbb, 0x69, 0x2f, 0x52, 0xdd, 0x78, 0x91, 0x1e, 0xc2,
	0x42, 0x44, 0x29, 0xe3, 0x56, 0xf2, 0x37, 0xb5, 0xa7, 0x67, 0x53, 0x6e, 0x1e, 0x96, 0x42, 0xce,
	0x1f, 0xa1, 0x23, 0x0b, 0x56, 0x7a, 0x14, 0xb3, 0x03, 0x35, 0xeb, 0xda, 0x19, 0xcd, 0x4d, 0xa3,
	0xd0, 0xdc, 0x38, 0xbf, 0x87, 0xce, 0x09, 0x61, 0x6c, 0x92, 0x6d, 0xf0, 0xdd, 0x7a, 0xa4, 0x75,
	0x58, 0xf0, 0xb5, 0xcc, 0x96, 0x84, 0xb3, 0x06, 0xab, 0xd2, 0xfa, 0xe3, 0x49, 0x32, 0x15, 0xd1,
	0x71, 0x9e, 0x02, 0x3a, 0x25, 0xd1, 0xd4, 0x0f, 0x74, 0xee, 0xbb, 0x87, 0xd5, 0xf9, 0xb7, 0x05,
	0x2b, 0x5c, 0xef, 0x7b, 0x3c, 0x91, 0xcf, 0xcc, 0x13, 0xf9, 0x48, 0x3f, 0x11, 0x7d, 0xab, 0x3e,
	0x3f, 0x98, 0xf8, 0x59, 0xc0, 0xa2, 0x6b, 0x75, 0x3c, 0x1b, 0x4f, 0x00, 0x72, 0x26, 0xea, 0x42,
	0xe3, 0x82, 0x5c, 0xab, 0xed, 0xf9, 0xcf, 0xea, 0x84, 0xfa, 0xbc, 0xfe, 0xc4, 0x72, 0x62, 0x58,
	0x13, 0xee, 0x1b, 0x87, 0xfb, 0x5e, 0xbe, 0x7c, 0x87, 0xc3, 0xfe, 0x7f, 0x1d, 0x3a, 0x7c, 0x57,
	0x51, 0x4d, 0x9e, 0x5d, 0xbd, 0xd7, 0x8e, 0xdb, 0xd0, 0x0d, 0x23, 0x72, 0xe9, 0xd3, 0x24, 0x4e,
	0xfb, 0x69, 0xe5, 0x55, 0x89, 0x8f, 0x9e, 0xc2, 0x46, 0x91, 0x27, 0x22, 0x78, 0x1c, 0x51, 0x7a,
	0xae, 0x8a, 0xff, 0x1c, 0x09, 0xf4, 0x2b, 0xb8, 0x57, 0xb9, 0x6a, 0xd4, 0x9f, 0x79, 0x22, 0xfc,
	0xe1, 0x26, 0x57, 0x3e, 0xcb, 0x2c, 0x95, 0x6f, 0xaa, 0xc1, 0x43, 0x9f, 0x40, 0x4f, 0xa7, 0x35,
	0x0b, 0x5b, 0x42, 0x7a, 0xc6, 0x2a, 0x7a, 0x02, 0x77, 0x4a, 0x2b, 0xca, 0xb2, 0x45, 0x61, 0xd9,
	0xac, 0x65, 0xe7, 0x2f, 0x75, 0x75, 0xea, 0x63, 0x77, 0x32, 0x21, 0xc1, 0x88, 0xbc, 0xe7, 0x19,
	0xf4, 0xa0, 0xe5, 0x51, 0x71, 0xf7, 0x55, 0x06, 0x4b, 0x0a, 0x3d, 0x84, 0x35, 0x2f, 0x85, 0xcc,
	0x5c, 0x96, 0x61, 0x2e, 0x2f, 0xf0, 0xe8, 0x96, 0x98, 0x9a, 0xf3, 0xf2, 0xf5, 0x99, 0x27, 0x82,
	0xf6, 0xe1, 0x7e, 0xf5, 0xb2, 0x0a, 0x83, 0xac, 0xfb, 0x73, 0x65, 0x9c, 0x7f, 0xd6, 0xe1, 0x2e,
	0x8f, 0x05, 0x26, 0x71, 0x48, 0x83, 0x98, 0xfc, 0xb0, 0x31, 0xd9, 0x86, 0x6e, 0xa4, 0x0c, 0xc9,
	0x84, 0x65, 0x20, 0x4a, 0x7c, 0x9e, 0xdd, 0x45, 0x9e, 0x16, 0x3e, 0x99, 0x69, 0x73, 0x24, 0x6e,
	0xca, 0xee, 0xd6, 0x8d, 0xd9, 0xed, 0x9c, 0x42, 0x97, 0x87, 0xee, 0xc8, 0x0f, 0xdc, 0x89, 0xff,
	0xf6, 0x7b, 0x8a, 0x98, 0xf3, 0xb1, 0x4c, 0xce, 0xd2, 0x73, 0xa0, 0x84, 0x2d, 0x43, 0xf8, 0xcf,
	0xb2, 0x0c, 0xeb, 0x9f, 0xd6, 0x55, 0x72, 0xfc, 0x22, 0x0e, 0x49, 0x40, 0x45, 0xc1, 0x4f, 0xfb,
	0xb4, 0x15, 0x6c, 0xf0, 0xf2, 0x8e, 0xbd, 0xa1, 0x75, 0xec, 0x66, 0x29, 0x6b, 0x16, 0x4b, 0xd9,
	0xbf, 0xba, 0x00, 0x7b, 0x62, 0x28, 0x70, 0x40, 0x23, 0xd1, 0xca, 0x5d, 0x92, 0x28, 0xe6, 0x3b,
	0xa8, 0x67, 0x51, 0x91, 0x1c, 0x3c, 0xa0, 0x81, 0x47, 0x94, 0xb3, 0x92, 0xe0, 0xdf, 0x6d, 0x23,
	0x37, 0x7e, 0xe9, 0x4f, 0x55, 0xd7, 0xd3, 0xc4, 0x19, 0xad, 0xd6, 0x8e, 0x23, 0xdf, 0x23, 0x6a,
	0xdf, 0x8c, 0x46, 0xbb, 0xb0, 0xc4, 0xd2, 0xfc, 0x00, 0xf1, 0xe9, 0xb2, 0xae, 0x3f, 0x17, 0x69,
	0x38, 0x06, 0x35, 0x9c, 0xc9, 0xa1, 0xc7, 0xb0, 0x4c, 0xd2, 0x0f, 0x49, 0x7b, 0x45, 0x28, 0x19,
	0x1f, 0xe6, 0xd9, 0x57, 0xe6, 0xa0, 0x86, 0x73, 0x49, 0xb4, 0x07, 0x9d, 0x58, 0xef, 0xfa, 0xec,
	0x4e, 0xf9, 0xeb, 0xd5, 0x68, 0x0b, 0x07, 0x35, 0x6c, 0x6a, 0xa0, 0xa7, 0xfc, 0xf3, 0x25, 0xef,
	0xb2, 0xec, 0x5b, 0x02, 0xc1, 0x36, 0x11, 0xf2, 0xf5, 0x41, 0x0d, 0x1b, 0xf2, 0xdc, 0xdb, 0x50,
	0x3d, 0x7e, 0xf6, 0x6a, 0xd9, 0xdb, 0xf4, 0x61, 0xe4, 0xde, 0xa6, 0x72, 0xdc, 0x6c, 0x4f, 0x7f,
	0xd4, 0xec, 0x6e, 0xc5, 0x47, 0xb7, 0x2e, 0xc0, 0xcd, 0x36, 0x34, 0x84, 0xe7, 0x7a, 0x12, 0xda,
	0x6b, 0x15, 0x9e, 0xeb, 0x02, 0xc2, 0x73, 0x23, 0x6d, 0xbf, 0x82, 0x55, 0xcf, 0xec, 0x3c, 0x6c,
	0x24, 0x40, 0xee, 0x95, 0xed, 0xc8, 0x44, 0x06, 0x35, 0x5c, 0xd4, 0x42, 0xc7, 0x80, 0x58, 0xa9,
	0x5f, 0xb1, 0x3f, 0x10, 0x58, 0x0f, 0x8c, 0xa3, 0x2f, 0x49, 0x0d, 0x6a, 0xb8, 0x42, 0x97, 0x1f,
	0x4a, 0xa8, 0x75, 0x15, 0xf6, 0x7a, 0xf9, 0x50, 0xf4, 0xae, 0x83, 0x1f, 0x8a, 0x2e, 0x8f, 0x5e,
	0xc1, 0x5a, 0x58, 0xec, 0x1c, 0xec, 0xdb, 0x02, 0xe4, 0x47, 0x45, 0x90, 0x62, 0xa0, 0xcb, 0x9a,
	0x3c, 0xd8, 0xa1, 0xde, 0x12, 0xd8, 0xbd, 0x72, 0xb0, 0x8d, 0x9e, 0x81, 0x07, 0xdb, 0xd0, 0xc8,
	0x2c, 0xd2, 0x2b, 0xb8, 0x7d, 0x67, 0x86, 0x45, 0xba, 0x50, 0x66, 0x91, 0x51, 0xfb, 0x09, 0xdc,
	0x0d, 0x67, 0x3d, 0x0c, 0xb6, 0x2d, 0x60, 0x7f, 0x52, 0x84, 0xad, 0x14, 0x1e, 0xd4, 0xf0, 0x6c,
	0x24, 0xf4, 0x6b, 0xe8, 0x86, 0x85, 0x22, 0x6a, 0xdf, 0x15, 0xe8, 0xf7, 0x8b, 0xe8, 0xba, 0xcc,
	0xa0, 0x86, 0x4b, 0x7a, 0x69, 0x04, 0x8c, 0xa4, 0xb4, 0x37, 0xaa, 0x23, 0x50, 0xcc, 0xdc, 0xb2,
	0x66, 0x9a, 0x22, 0xd9, 0x4b, 0x74, 0xaf, 0x3a, 0x45, 0xb4, 0x6a, 0x63, 0xc8, 0xa3, 0x3f, 0x40,
	0x6f, 0x28, 0xa1, 0x4e, 0x29, 0x16, 0x63, 0x43, 0x3f, 0x18, 0x1d, 0x25, 0xc1, 0xd0, 0x7e, 0x20,
	0x90, 0x1c, 0x1d, 0xe9, 0xb0, 0x52, 0x72, 0x50, 0xc3, 0x33, 0x30, 0x38, 0xba, 0x37, 0x71, 0xfd,
	0xe9, 0x51, 0x44, 0xa7, 0x26, 0xfa, 0x87, 0x65, 0xf4, 0x83, 0x4a, 0x49, 0x8e, 0x5e, 0x8d, 0x81,
	0xbe, 0x80, 0xf6, 0x28, 0x72, 0x03, 0x26, 0xb9, 0xf6, 0xa6, 0x80, 0x34, 0x26, 0x8f, 0x5f, 0xe5,
	0xcb, 0x83, 0x1a, 0xd6, 0xa5, 0xb9, 0x72, 0x9c, 0x0f, 0x79, 0xec, 0xad, 0xb2, 0xb2, 0x36, 0x03,
	0xe2, 0xca, 0x9a, 0x34, 0xfa, 0x52, 0x0d, 0x7b, 0xbe, 0x96, 0xf3, 0x26, 0xfb, 0x67, 0x33, 0xb4,
	0xe5, 0x84, 0x45, 0x16, 0xcb, 0x5c, 0x1c, 0xfd, 0x52, 0xd4, 0xeb, 0x0b, 0xf2, 0x3b, 0x9f, 0x8d,
	0x87, 0x91, 0xfb, 0xc6, 0xde, 0xbe, 0x49, 0xdf, 0x94, 0x47, 0x07, 0x0a, 0x60, 0x6f, 0x38, 0x94,
	0x06, 0x7c, 0x5c, 0xae, 0x58, 0x85, 0x69, 0x4c, 0x06, 0x92, 0xea, 0xa0, 0x5f, 0x28, 0x27, 0x30,
	0x91, 0x18, 0x0f, 0x05, 0x46, 0xaf, 0x8c, 0x31, 0xca, 0x0a, 0x7e, 0x2e, 0x8d, 0x5e, 0xc0, 0xba,
	0x8c, 0xc8, 0xd8, 0x0d, 0x46, 0x24, 0x9b, 0x8d, 0xda, 0x8f, 0xca, 0xaf, 0x56, 0x36, 0xf9, 0x18,
	0xd4, 0x70, 0xa5, 0x12, 0x7a, 0x0d, 0x3d, 0xc1, 0x4f, 0xd3, 0xf2, 0x35, 0x7f, 0xd6, 0xe3, 0xb1,
	0x1f, 0xda, 0xfd, 0xf9, 0x70, 0x33, 0xd4, 0x44, 0xa9, 0xd2, 0xa7, 0xbe, 0xf6, 0x6e, 0x45, 0xa9,
	0xd2, 0x05, 0x44, 0xa9, 0xd2, 0x19, 0xfb, 0x4b, 0xd0, 0x92, 0x7f, 0x25, 0x38, 0x97, 0xd0, 0x92,
	0xfd, 0x03, 0xda, 0x86, 0xa6, 0x47, 0x23, 0x39, 0x09, 0x28, 0x84, 0x2a, 0xef, 0x30, 0xb0, 0x90,
	0x11, 0x03, 0x41, 0x12, 0x0c, 0x49, 0x74, 0x2c, 0x47, 0xf7, 0xaa, 0x9d, 0xd1, 0x79, 0xbc, 0x71,
	0x89, 0xfd, 0x51, 0xe0, 0xb2, 0x24, 0x22, 0xaa, 0xe3, 0xcc, 0x19, 0xce, 0x7f, 0x2c, 0x58, 0xc4,
	0xc4, 0x23, 0x7e, 0x28, 0x9a, 0xab, 0x98, 0xb9, 0x2c, 0x89, 0xd3, 0xa6, 0x49, 0x52, 0x1c, 0xe1,
	0x6c, 0x72, 0x61, 0x8c, 0x3c, 0x72, 0x86, 0x18, 0x96, 0x7b, 0x6c, 0xe0, 0xc6, 0xe3, 0x74, 0x8e,
	0xa6, 0x48, 0xb4, 0x09, 0xed, 0x91, 0x1b, 0x1f, 0xd0, 0x20, 0x4e, 0xa6, 0x64, 0x98, 0xce, 0x69,
	0x34, 0x16, 0xef, 0x12, 0xd3, 0xf9, 0x74, 0xda, 0x25, 0x2e, 0xc8, 0x2e, 0xb1, 0xc0, 0x46, 0x1f,
	0x41, 0x73, 0x42, 0x47, 0xb1, 0xdd, 0x12, 0x1f, 0xc5, 0xab, 0x7a, 0x54, 0x5e, 0xd2, 0x11, 0x16,
	0x8b, 0xce, 0xdf, 0x2d, 0x68, 0xbc, 0xa4, 0xa3, 0x2a, 0x58, 0xab, 0x1a, 0xb6, 0x07, 0x2d, 0x46,
	0x43, 0xdf, 0x8b, 0xed, 0xfa, 0x66, 0x63, 0x6b, 0x05, 0x2b, 0xaa, 0x6a, 0x58, 0x6e, 0x86, 0xa1,
	0x39, 0x27, 0x0c, 0x0b, 0x66, 0x18, 0xb2, 0x61, 0x44, 0x4b, 0xfe, 0x67, 0x20, 0x87, 0x11, 0x87,
	0xd0, 0xab, 0x2e, 0x75, 0x33, 0x47, 0x1e, 0xa9, 0x4d, 0x75, 0x6d, 0x80, 0x7f, 0x08, 0xbd, 0xea,
	0x92, 0xf6, 0x5e, 0x28, 0xbf, 0x85, 0xb6, 0x56, 0xc5, 0x78, 0x06, 0x6a, 0x03, 0x46, 0x23, 0x03,
	0xa5, 0x84, 0x36, 0x5d, 0x9c, 0x31, 0xc5, 0xd8, 0x7e, 0xa8, 0x46, 0xb5, 0xf9, 0xfc, 0x17, 0xb5,
	0x61, 0x51, 0x15, 0xa7, 0x6e, 0x0d, 0xad, 0xc0, 0x52, 0x5a, 0x69, 0xba, 0xd6, 0xf6, 0x17, 0x62,
	0xa4, 0x98, 0x8f, 0x2e, 0xd1, 0x07, 0xb0, 0x5a, 0xb8, 0xbf, 0xdd, 0x1a, 0xba, 0x0d, 0x6b, 0xa5,
	0x5b, 0xd8, 0xb5, 0xb6, 0xfb, 0x00, 0xb9, 0x59, 0x68, 0x15, 0xda, 0xa2, 0x31, 0x91, 0xac, 0x6e,
	0x8d, 0x33, 0x9e, 0x85, 0xd4, 0x1b, 0x2b, 0x86, 0xb5, 0xff, 0xe9, 0x37, 0x8f, 0x47, 0x3e, 0x1b,
	0x27, 0x67, 0x7d, 0x8f, 0x4e, 0x77, 0x84, 0x73, 0x61, 0x44, 0xff, 0x44, 0x3c, 0x26, 0x89, 0x47,
	0xf2, 0x9f, 0xbe, 0x11, 0x9d, 0xb8, 0xc1, 0x68, 0x27, 0x77, 0xfe, 0xac, 0x25, 0x16, 0x7e, 0xfe,
	0x6d, 0x00, 0x00, 0x00, 0xff, 0xff, 0x37, 0x4c, 0x58, 0x4b, 0x0b, 0x1c, 0x00, 0x00,
}
