// Copyright (c) 2019 IoTeX
// This is an alpha (internal) release and is not suitable for production. This source code is provided 'as is' and no
// warranties are given as to title or non-infringement, merchantability or fitness for purpose and, to the extent
// permitted by law, all liability for your use of the code is disclaimed. This source code is governed by Apache
// License 2.0 that can be found in the LICENSE file.

// To compile the proto, run:
//      protoc --go_out=plugins=grpc:$GOPATH/src *.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.23.3
// source: proto/types/genesis.proto

package iotextypes

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Genesis struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blockchain    *GenesisBlockchain     `protobuf:"bytes,1,opt,name=blockchain,proto3" json:"blockchain,omitempty"`
	Account       *GenesisAccount        `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	Poll          *GenesisPoll           `protobuf:"bytes,3,opt,name=poll,proto3" json:"poll,omitempty"`
	Rewarding     *GenesisRewarding      `protobuf:"bytes,4,opt,name=rewarding,proto3" json:"rewarding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Genesis) Reset() {
	*x = Genesis{}
	mi := &file_proto_types_genesis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Genesis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Genesis) ProtoMessage() {}

func (x *Genesis) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_genesis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Genesis.ProtoReflect.Descriptor instead.
func (*Genesis) Descriptor() ([]byte, []int) {
	return file_proto_types_genesis_proto_rawDescGZIP(), []int{0}
}

func (x *Genesis) GetBlockchain() *GenesisBlockchain {
	if x != nil {
		return x.Blockchain
	}
	return nil
}

func (x *Genesis) GetAccount() *GenesisAccount {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *Genesis) GetPoll() *GenesisPoll {
	if x != nil {
		return x.Poll
	}
	return nil
}

func (x *Genesis) GetRewarding() *GenesisRewarding {
	if x != nil {
		return x.Rewarding
	}
	return nil
}

type GenesisBlockchain struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Timestamp             int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	BlockGasLimit         uint64                 `protobuf:"varint,2,opt,name=blockGasLimit,proto3" json:"blockGasLimit,omitempty"`
	ActionGasLimit        uint64                 `protobuf:"varint,3,opt,name=actionGasLimit,proto3" json:"actionGasLimit,omitempty"`
	BlockInterval         int64                  `protobuf:"varint,4,opt,name=blockInterval,proto3" json:"blockInterval,omitempty"`
	NumSubEpochs          uint64                 `protobuf:"varint,5,opt,name=numSubEpochs,proto3" json:"numSubEpochs,omitempty"`
	NumDelegates          uint64                 `protobuf:"varint,6,opt,name=numDelegates,proto3" json:"numDelegates,omitempty"`
	NumCandidateDelegates uint64                 `protobuf:"varint,7,opt,name=numCandidateDelegates,proto3" json:"numCandidateDelegates,omitempty"`
	TimeBasedRotation     bool                   `protobuf:"varint,8,opt,name=timeBasedRotation,proto3" json:"timeBasedRotation,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GenesisBlockchain) Reset() {
	*x = GenesisBlockchain{}
	mi := &file_proto_types_genesis_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenesisBlockchain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenesisBlockchain) ProtoMessage() {}

func (x *GenesisBlockchain) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_genesis_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenesisBlockchain.ProtoReflect.Descriptor instead.
func (*GenesisBlockchain) Descriptor() ([]byte, []int) {
	return file_proto_types_genesis_proto_rawDescGZIP(), []int{1}
}

func (x *GenesisBlockchain) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *GenesisBlockchain) GetBlockGasLimit() uint64 {
	if x != nil {
		return x.BlockGasLimit
	}
	return 0
}

func (x *GenesisBlockchain) GetActionGasLimit() uint64 {
	if x != nil {
		return x.ActionGasLimit
	}
	return 0
}

func (x *GenesisBlockchain) GetBlockInterval() int64 {
	if x != nil {
		return x.BlockInterval
	}
	return 0
}

func (x *GenesisBlockchain) GetNumSubEpochs() uint64 {
	if x != nil {
		return x.NumSubEpochs
	}
	return 0
}

func (x *GenesisBlockchain) GetNumDelegates() uint64 {
	if x != nil {
		return x.NumDelegates
	}
	return 0
}

func (x *GenesisBlockchain) GetNumCandidateDelegates() uint64 {
	if x != nil {
		return x.NumCandidateDelegates
	}
	return 0
}

func (x *GenesisBlockchain) GetTimeBasedRotation() bool {
	if x != nil {
		return x.TimeBasedRotation
	}
	return false
}

type GenesisAccount struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	InitBalanceAddrs []string               `protobuf:"bytes,1,rep,name=initBalanceAddrs,proto3" json:"initBalanceAddrs,omitempty"`
	InitBalances     []string               `protobuf:"bytes,2,rep,name=initBalances,proto3" json:"initBalances,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GenesisAccount) Reset() {
	*x = GenesisAccount{}
	mi := &file_proto_types_genesis_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenesisAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenesisAccount) ProtoMessage() {}

func (x *GenesisAccount) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_genesis_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenesisAccount.ProtoReflect.Descriptor instead.
func (*GenesisAccount) Descriptor() ([]byte, []int) {
	return file_proto_types_genesis_proto_rawDescGZIP(), []int{2}
}

func (x *GenesisAccount) GetInitBalanceAddrs() []string {
	if x != nil {
		return x.InitBalanceAddrs
	}
	return nil
}

func (x *GenesisAccount) GetInitBalances() []string {
	if x != nil {
		return x.InitBalances
	}
	return nil
}

type GenesisPoll struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	EnableGravityChainVoting bool                   `protobuf:"varint,1,opt,name=enableGravityChainVoting,proto3" json:"enableGravityChainVoting,omitempty"`
	GravityChainStartHeight  uint64                 `protobuf:"varint,2,opt,name=gravityChainStartHeight,proto3" json:"gravityChainStartHeight,omitempty"`
	RegisterContractAddress  string                 `protobuf:"bytes,3,opt,name=registerContractAddress,proto3" json:"registerContractAddress,omitempty"`
	StakingContractAddress   string                 `protobuf:"bytes,4,opt,name=stakingContractAddress,proto3" json:"stakingContractAddress,omitempty"`
	VoteThreshold            string                 `protobuf:"bytes,5,opt,name=voteThreshold,proto3" json:"voteThreshold,omitempty"`
	ScoreThreshold           string                 `protobuf:"bytes,6,opt,name=scoreThreshold,proto3" json:"scoreThreshold,omitempty"`
	SelfStakingThreshold     string                 `protobuf:"bytes,7,opt,name=selfStakingThreshold,proto3" json:"selfStakingThreshold,omitempty"`
	Delegates                []*GenesisDelegate     `protobuf:"bytes,8,rep,name=delegates,proto3" json:"delegates,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *GenesisPoll) Reset() {
	*x = GenesisPoll{}
	mi := &file_proto_types_genesis_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenesisPoll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenesisPoll) ProtoMessage() {}

func (x *GenesisPoll) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_genesis_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenesisPoll.ProtoReflect.Descriptor instead.
func (*GenesisPoll) Descriptor() ([]byte, []int) {
	return file_proto_types_genesis_proto_rawDescGZIP(), []int{3}
}

func (x *GenesisPoll) GetEnableGravityChainVoting() bool {
	if x != nil {
		return x.EnableGravityChainVoting
	}
	return false
}

func (x *GenesisPoll) GetGravityChainStartHeight() uint64 {
	if x != nil {
		return x.GravityChainStartHeight
	}
	return 0
}

func (x *GenesisPoll) GetRegisterContractAddress() string {
	if x != nil {
		return x.RegisterContractAddress
	}
	return ""
}

func (x *GenesisPoll) GetStakingContractAddress() string {
	if x != nil {
		return x.StakingContractAddress
	}
	return ""
}

func (x *GenesisPoll) GetVoteThreshold() string {
	if x != nil {
		return x.VoteThreshold
	}
	return ""
}

func (x *GenesisPoll) GetScoreThreshold() string {
	if x != nil {
		return x.ScoreThreshold
	}
	return ""
}

func (x *GenesisPoll) GetSelfStakingThreshold() string {
	if x != nil {
		return x.SelfStakingThreshold
	}
	return ""
}

func (x *GenesisPoll) GetDelegates() []*GenesisDelegate {
	if x != nil {
		return x.Delegates
	}
	return nil
}

type GenesisDelegate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperatorAddr  string                 `protobuf:"bytes,1,opt,name=operatorAddr,proto3" json:"operatorAddr,omitempty"`
	RewardAddr    string                 `protobuf:"bytes,2,opt,name=rewardAddr,proto3" json:"rewardAddr,omitempty"`
	Votes         string                 `protobuf:"bytes,3,opt,name=votes,proto3" json:"votes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenesisDelegate) Reset() {
	*x = GenesisDelegate{}
	mi := &file_proto_types_genesis_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenesisDelegate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenesisDelegate) ProtoMessage() {}

func (x *GenesisDelegate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_genesis_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenesisDelegate.ProtoReflect.Descriptor instead.
func (*GenesisDelegate) Descriptor() ([]byte, []int) {
	return file_proto_types_genesis_proto_rawDescGZIP(), []int{4}
}

func (x *GenesisDelegate) GetOperatorAddr() string {
	if x != nil {
		return x.OperatorAddr
	}
	return ""
}

func (x *GenesisDelegate) GetRewardAddr() string {
	if x != nil {
		return x.RewardAddr
	}
	return ""
}

func (x *GenesisDelegate) GetVotes() string {
	if x != nil {
		return x.Votes
	}
	return ""
}

type GenesisRewarding struct {
	state                          protoimpl.MessageState `protogen:"open.v1"`
	InitAdminAddr                  string                 `protobuf:"bytes,1,opt,name=initAdminAddr,proto3" json:"initAdminAddr,omitempty"`
	InitBalance                    string                 `protobuf:"bytes,2,opt,name=initBalance,proto3" json:"initBalance,omitempty"`
	BlockReward                    string                 `protobuf:"bytes,3,opt,name=blockReward,proto3" json:"blockReward,omitempty"`
	EpochReward                    string                 `protobuf:"bytes,4,opt,name=epochReward,proto3" json:"epochReward,omitempty"`
	NumDelegatesForEpochReward     uint64                 `protobuf:"varint,5,opt,name=numDelegatesForEpochReward,proto3" json:"numDelegatesForEpochReward,omitempty"`
	FoundationBonus                string                 `protobuf:"bytes,6,opt,name=foundationBonus,proto3" json:"foundationBonus,omitempty"`
	NumDelegatesForFoundationBonus uint64                 `protobuf:"varint,7,opt,name=numDelegatesForFoundationBonus,proto3" json:"numDelegatesForFoundationBonus,omitempty"`
	FoundationBonusLastEpoch       uint64                 `protobuf:"varint,8,opt,name=foundationBonusLastEpoch,proto3" json:"foundationBonusLastEpoch,omitempty"`
	ProductivityThreshold          uint64                 `protobuf:"varint,9,opt,name=productivityThreshold,proto3" json:"productivityThreshold,omitempty"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *GenesisRewarding) Reset() {
	*x = GenesisRewarding{}
	mi := &file_proto_types_genesis_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenesisRewarding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenesisRewarding) ProtoMessage() {}

func (x *GenesisRewarding) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_genesis_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenesisRewarding.ProtoReflect.Descriptor instead.
func (*GenesisRewarding) Descriptor() ([]byte, []int) {
	return file_proto_types_genesis_proto_rawDescGZIP(), []int{5}
}

func (x *GenesisRewarding) GetInitAdminAddr() string {
	if x != nil {
		return x.InitAdminAddr
	}
	return ""
}

func (x *GenesisRewarding) GetInitBalance() string {
	if x != nil {
		return x.InitBalance
	}
	return ""
}

func (x *GenesisRewarding) GetBlockReward() string {
	if x != nil {
		return x.BlockReward
	}
	return ""
}

func (x *GenesisRewarding) GetEpochReward() string {
	if x != nil {
		return x.EpochReward
	}
	return ""
}

func (x *GenesisRewarding) GetNumDelegatesForEpochReward() uint64 {
	if x != nil {
		return x.NumDelegatesForEpochReward
	}
	return 0
}

func (x *GenesisRewarding) GetFoundationBonus() string {
	if x != nil {
		return x.FoundationBonus
	}
	return ""
}

func (x *GenesisRewarding) GetNumDelegatesForFoundationBonus() uint64 {
	if x != nil {
		return x.NumDelegatesForFoundationBonus
	}
	return 0
}

func (x *GenesisRewarding) GetFoundationBonusLastEpoch() uint64 {
	if x != nil {
		return x.FoundationBonusLastEpoch
	}
	return 0
}

func (x *GenesisRewarding) GetProductivityThreshold() uint64 {
	if x != nil {
		return x.ProductivityThreshold
	}
	return 0
}

var File_proto_types_genesis_proto protoreflect.FileDescriptor

const file_proto_types_genesis_proto_rawDesc = "" +
	"\n" +
	"\x19proto/types/genesis.proto\x12\n" +
	"iotextypes\"\xe7\x01\n" +
	"\aGenesis\x12=\n" +
	"\n" +
	"blockchain\x18\x01 \x01(\v2\x1d.iotextypes.GenesisBlockchainR\n" +
	"blockchain\x124\n" +
	"\aaccount\x18\x02 \x01(\v2\x1a.iotextypes.GenesisAccountR\aaccount\x12+\n" +
	"\x04poll\x18\x03 \x01(\v2\x17.iotextypes.GenesisPollR\x04poll\x12:\n" +
	"\trewarding\x18\x04 \x01(\v2\x1c.iotextypes.GenesisRewardingR\trewarding\"\xd1\x02\n" +
	"\x11GenesisBlockchain\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12$\n" +
	"\rblockGasLimit\x18\x02 \x01(\x04R\rblockGasLimit\x12&\n" +
	"\x0eactionGasLimit\x18\x03 \x01(\x04R\x0eactionGasLimit\x12$\n" +
	"\rblockInterval\x18\x04 \x01(\x03R\rblockInterval\x12\"\n" +
	"\fnumSubEpochs\x18\x05 \x01(\x04R\fnumSubEpochs\x12\"\n" +
	"\fnumDelegates\x18\x06 \x01(\x04R\fnumDelegates\x124\n" +
	"\x15numCandidateDelegates\x18\a \x01(\x04R\x15numCandidateDelegates\x12,\n" +
	"\x11timeBasedRotation\x18\b \x01(\bR\x11timeBasedRotation\"`\n" +
	"\x0eGenesisAccount\x12*\n" +
	"\x10initBalanceAddrs\x18\x01 \x03(\tR\x10initBalanceAddrs\x12\"\n" +
	"\finitBalances\x18\x02 \x03(\tR\finitBalances\"\xb2\x03\n" +
	"\vGenesisPoll\x12:\n" +
	"\x18enableGravityChainVoting\x18\x01 \x01(\bR\x18enableGravityChainVoting\x128\n" +
	"\x17gravityChainStartHeight\x18\x02 \x01(\x04R\x17gravityChainStartHeight\x128\n" +
	"\x17registerContractAddress\x18\x03 \x01(\tR\x17registerContractAddress\x126\n" +
	"\x16stakingContractAddress\x18\x04 \x01(\tR\x16stakingContractAddress\x12$\n" +
	"\rvoteThreshold\x18\x05 \x01(\tR\rvoteThreshold\x12&\n" +
	"\x0escoreThreshold\x18\x06 \x01(\tR\x0escoreThreshold\x122\n" +
	"\x14selfStakingThreshold\x18\a \x01(\tR\x14selfStakingThreshold\x129\n" +
	"\tdelegates\x18\b \x03(\v2\x1b.iotextypes.GenesisDelegateR\tdelegates\"k\n" +
	"\x0fGenesisDelegate\x12\"\n" +
	"\foperatorAddr\x18\x01 \x01(\tR\foperatorAddr\x12\x1e\n" +
	"\n" +
	"rewardAddr\x18\x02 \x01(\tR\n" +
	"rewardAddr\x12\x14\n" +
	"\x05votes\x18\x03 \x01(\tR\x05votes\"\xc2\x03\n" +
	"\x10GenesisRewarding\x12$\n" +
	"\rinitAdminAddr\x18\x01 \x01(\tR\rinitAdminAddr\x12 \n" +
	"\vinitBalance\x18\x02 \x01(\tR\vinitBalance\x12 \n" +
	"\vblockReward\x18\x03 \x01(\tR\vblockReward\x12 \n" +
	"\vepochReward\x18\x04 \x01(\tR\vepochReward\x12>\n" +
	"\x1anumDelegatesForEpochReward\x18\x05 \x01(\x04R\x1anumDelegatesForEpochReward\x12(\n" +
	"\x0ffoundationBonus\x18\x06 \x01(\tR\x0ffoundationBonus\x12F\n" +
	"\x1enumDelegatesForFoundationBonus\x18\a \x01(\x04R\x1enumDelegatesForFoundationBonus\x12:\n" +
	"\x18foundationBonusLastEpoch\x18\b \x01(\x04R\x18foundationBonusLastEpoch\x124\n" +
	"\x15productivityThreshold\x18\t \x01(\x04R\x15productivityThresholdB]\n" +
	"\"com.github.iotexproject.grpc.typesP\x01Z5github.com/iotexproject/iotex-proto/golang/iotextypesb\x06proto3"

var (
	file_proto_types_genesis_proto_rawDescOnce sync.Once
	file_proto_types_genesis_proto_rawDescData []byte
)

func file_proto_types_genesis_proto_rawDescGZIP() []byte {
	file_proto_types_genesis_proto_rawDescOnce.Do(func() {
		file_proto_types_genesis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_types_genesis_proto_rawDesc), len(file_proto_types_genesis_proto_rawDesc)))
	})
	return file_proto_types_genesis_proto_rawDescData
}

var file_proto_types_genesis_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_types_genesis_proto_goTypes = []any{
	(*Genesis)(nil),           // 0: iotextypes.Genesis
	(*GenesisBlockchain)(nil), // 1: iotextypes.GenesisBlockchain
	(*GenesisAccount)(nil),    // 2: iotextypes.GenesisAccount
	(*GenesisPoll)(nil),       // 3: iotextypes.GenesisPoll
	(*GenesisDelegate)(nil),   // 4: iotextypes.GenesisDelegate
	(*GenesisRewarding)(nil),  // 5: iotextypes.GenesisRewarding
}
var file_proto_types_genesis_proto_depIdxs = []int32{
	1, // 0: iotextypes.Genesis.blockchain:type_name -> iotextypes.GenesisBlockchain
	2, // 1: iotextypes.Genesis.account:type_name -> iotextypes.GenesisAccount
	3, // 2: iotextypes.Genesis.poll:type_name -> iotextypes.GenesisPoll
	5, // 3: iotextypes.Genesis.rewarding:type_name -> iotextypes.GenesisRewarding
	4, // 4: iotextypes.GenesisPoll.delegates:type_name -> iotextypes.GenesisDelegate
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_types_genesis_proto_init() }
func file_proto_types_genesis_proto_init() {
	if File_proto_types_genesis_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_types_genesis_proto_rawDesc), len(file_proto_types_genesis_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_types_genesis_proto_goTypes,
		DependencyIndexes: file_proto_types_genesis_proto_depIdxs,
		MessageInfos:      file_proto_types_genesis_proto_msgTypes,
	}.Build()
	File_proto_types_genesis_proto = out.File
	file_proto_types_genesis_proto_goTypes = nil
	file_proto_types_genesis_proto_depIdxs = nil
}
