// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/types/implicit_log.proto

package iotextypes

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ImplicitTransferLogType int32

const (
	ImplicitTransferLogType_IN_CONTRACT_TRANSFER       ImplicitTransferLogType = 0
	ImplicitTransferLogType_BUCKET_WITHDRAW_AMOUNT     ImplicitTransferLogType = 1
	ImplicitTransferLogType_BUCKET_CREATE_AMOUNT       ImplicitTransferLogType = 2
	ImplicitTransferLogType_BUCKET_DEPOSIT_AMOUNT      ImplicitTransferLogType = 3
	ImplicitTransferLogType_CANDIDATE_SELF_STAKE       ImplicitTransferLogType = 4
	ImplicitTransferLogType_CANDIDATE_REGISTRATION_FEE ImplicitTransferLogType = 5
)

var ImplicitTransferLogType_name = map[int32]string{
	0: "IN_CONTRACT_TRANSFER",
	1: "BUCKET_WITHDRAW_AMOUNT",
	2: "BUCKET_CREATE_AMOUNT",
	3: "BUCKET_DEPOSIT_AMOUNT",
	4: "CANDIDATE_SELF_STAKE",
	5: "CANDIDATE_REGISTRATION_FEE",
}

var ImplicitTransferLogType_value = map[string]int32{
	"IN_CONTRACT_TRANSFER":       0,
	"BUCKET_WITHDRAW_AMOUNT":     1,
	"BUCKET_CREATE_AMOUNT":       2,
	"BUCKET_DEPOSIT_AMOUNT":      3,
	"CANDIDATE_SELF_STAKE":       4,
	"CANDIDATE_REGISTRATION_FEE": 5,
}

func (x ImplicitTransferLogType) String() string {
	return proto.EnumName(ImplicitTransferLogType_name, int32(x))
}

func (ImplicitTransferLogType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ea1533ca3e5146aa, []int{0}
}

// ImplicitTransferLog captures the transfers that are not explicit such as transfer action, which covers:
// 1. IOTX transferred via smart contracts
// 2. Bucket operations for nsv2 protocol
type ImplicitTransferLog struct {
	ActionHash           []byte                             `protobuf:"bytes,1,opt,name=actionHash,proto3" json:"actionHash,omitempty"`
	NumTransactions      uint64                             `protobuf:"varint,2,opt,name=numTransactions,proto3" json:"numTransactions,omitempty"`
	Transactions         []*ImplicitTransferLog_Transaction `protobuf:"bytes,3,rep,name=transactions,proto3" json:"transactions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *ImplicitTransferLog) Reset()         { *m = ImplicitTransferLog{} }
func (m *ImplicitTransferLog) String() string { return proto.CompactTextString(m) }
func (*ImplicitTransferLog) ProtoMessage()    {}
func (*ImplicitTransferLog) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea1533ca3e5146aa, []int{0}
}

func (m *ImplicitTransferLog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImplicitTransferLog.Unmarshal(m, b)
}
func (m *ImplicitTransferLog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImplicitTransferLog.Marshal(b, m, deterministic)
}
func (m *ImplicitTransferLog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImplicitTransferLog.Merge(m, src)
}
func (m *ImplicitTransferLog) XXX_Size() int {
	return xxx_messageInfo_ImplicitTransferLog.Size(m)
}
func (m *ImplicitTransferLog) XXX_DiscardUnknown() {
	xxx_messageInfo_ImplicitTransferLog.DiscardUnknown(m)
}

var xxx_messageInfo_ImplicitTransferLog proto.InternalMessageInfo

func (m *ImplicitTransferLog) GetActionHash() []byte {
	if m != nil {
		return m.ActionHash
	}
	return nil
}

func (m *ImplicitTransferLog) GetNumTransactions() uint64 {
	if m != nil {
		return m.NumTransactions
	}
	return 0
}

func (m *ImplicitTransferLog) GetTransactions() []*ImplicitTransferLog_Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

type ImplicitTransferLog_Transaction struct {
	Topic                []byte   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Amount               string   `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Sender               string   `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty"`
	Recipient            string   `protobuf:"bytes,4,opt,name=recipient,proto3" json:"recipient,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImplicitTransferLog_Transaction) Reset()         { *m = ImplicitTransferLog_Transaction{} }
func (m *ImplicitTransferLog_Transaction) String() string { return proto.CompactTextString(m) }
func (*ImplicitTransferLog_Transaction) ProtoMessage()    {}
func (*ImplicitTransferLog_Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea1533ca3e5146aa, []int{0, 0}
}

func (m *ImplicitTransferLog_Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImplicitTransferLog_Transaction.Unmarshal(m, b)
}
func (m *ImplicitTransferLog_Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImplicitTransferLog_Transaction.Marshal(b, m, deterministic)
}
func (m *ImplicitTransferLog_Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImplicitTransferLog_Transaction.Merge(m, src)
}
func (m *ImplicitTransferLog_Transaction) XXX_Size() int {
	return xxx_messageInfo_ImplicitTransferLog_Transaction.Size(m)
}
func (m *ImplicitTransferLog_Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_ImplicitTransferLog_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_ImplicitTransferLog_Transaction proto.InternalMessageInfo

func (m *ImplicitTransferLog_Transaction) GetTopic() []byte {
	if m != nil {
		return m.Topic
	}
	return nil
}

func (m *ImplicitTransferLog_Transaction) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *ImplicitTransferLog_Transaction) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *ImplicitTransferLog_Transaction) GetRecipient() string {
	if m != nil {
		return m.Recipient
	}
	return ""
}

type BlockImplicitTransferLog struct {
	NumTransactions      uint64                 `protobuf:"varint,1,opt,name=numTransactions,proto3" json:"numTransactions,omitempty"`
	ImplicitTransferLog  []*ImplicitTransferLog `protobuf:"bytes,2,rep,name=implicitTransferLog,proto3" json:"implicitTransferLog,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *BlockImplicitTransferLog) Reset()         { *m = BlockImplicitTransferLog{} }
func (m *BlockImplicitTransferLog) String() string { return proto.CompactTextString(m) }
func (*BlockImplicitTransferLog) ProtoMessage()    {}
func (*BlockImplicitTransferLog) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea1533ca3e5146aa, []int{1}
}

func (m *BlockImplicitTransferLog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockImplicitTransferLog.Unmarshal(m, b)
}
func (m *BlockImplicitTransferLog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockImplicitTransferLog.Marshal(b, m, deterministic)
}
func (m *BlockImplicitTransferLog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockImplicitTransferLog.Merge(m, src)
}
func (m *BlockImplicitTransferLog) XXX_Size() int {
	return xxx_messageInfo_BlockImplicitTransferLog.Size(m)
}
func (m *BlockImplicitTransferLog) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockImplicitTransferLog.DiscardUnknown(m)
}

var xxx_messageInfo_BlockImplicitTransferLog proto.InternalMessageInfo

func (m *BlockImplicitTransferLog) GetNumTransactions() uint64 {
	if m != nil {
		return m.NumTransactions
	}
	return 0
}

func (m *BlockImplicitTransferLog) GetImplicitTransferLog() []*ImplicitTransferLog {
	if m != nil {
		return m.ImplicitTransferLog
	}
	return nil
}

func init() {
	proto.RegisterEnum("iotextypes.ImplicitTransferLogType", ImplicitTransferLogType_name, ImplicitTransferLogType_value)
	proto.RegisterType((*ImplicitTransferLog)(nil), "iotextypes.ImplicitTransferLog")
	proto.RegisterType((*ImplicitTransferLog_Transaction)(nil), "iotextypes.ImplicitTransferLog.Transaction")
	proto.RegisterType((*BlockImplicitTransferLog)(nil), "iotextypes.BlockImplicitTransferLog")
}

func init() { proto.RegisterFile("proto/types/implicit_log.proto", fileDescriptor_ea1533ca3e5146aa) }

var fileDescriptor_ea1533ca3e5146aa = []byte{
	// 433 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x61, 0x6b, 0xd3, 0x40,
	0x1c, 0xc6, 0x4d, 0xdb, 0x0d, 0xf6, 0xdf, 0xc0, 0x72, 0x9b, 0x33, 0x16, 0xa9, 0xa5, 0xaf, 0x8a,
	0x62, 0x0a, 0x8a, 0x1f, 0xe0, 0x9a, 0x5e, 0x5d, 0xd8, 0x4c, 0xe6, 0xe5, 0xc6, 0x40, 0x90, 0x90,
	0x9d, 0x67, 0x76, 0xda, 0xe4, 0xce, 0xe4, 0x0a, 0xee, 0x93, 0xf8, 0x01, 0xfc, 0x1e, 0x7e, 0x36,
	0xe9, 0x25, 0xa3, 0x51, 0x03, 0xbe, 0xfc, 0x3f, 0xbf, 0xe7, 0x39, 0x1e, 0x1e, 0x0e, 0xc6, 0xba,
	0x54, 0x46, 0xcd, 0xcd, 0x9d, 0x16, 0xd5, 0x5c, 0xe6, 0x7a, 0x2d, 0xb9, 0x34, 0xc9, 0x5a, 0x65,
	0x9e, 0x05, 0x08, 0xa4, 0x32, 0xe2, 0xbb, 0xc5, 0xd3, 0x9f, 0x3d, 0x38, 0x0e, 0x1a, 0x0b, 0x2b,
	0xd3, 0xa2, 0xfa, 0x2c, 0xca, 0x0b, 0x95, 0xa1, 0x31, 0x40, 0xca, 0x8d, 0x54, 0xc5, 0x59, 0x5a,
	0xdd, 0xba, 0xce, 0xc4, 0x99, 0x1d, 0xd1, 0x96, 0x82, 0x66, 0xf0, 0xb0, 0xd8, 0xe4, 0x36, 0x51,
	0xab, 0x95, 0xdb, 0x9b, 0x38, 0xb3, 0x01, 0xfd, 0x5b, 0x46, 0x11, 0x1c, 0x99, 0xb6, 0xad, 0x3f,
	0xe9, 0xcf, 0x0e, 0x5f, 0xbd, 0xf0, 0x76, 0x25, 0xbc, 0x8e, 0x02, 0x5e, 0xeb, 0x0d, 0xfa, 0xc7,
	0x03, 0xa3, 0x6f, 0x70, 0xd8, 0x82, 0xe8, 0x04, 0xf6, 0x8c, 0xd2, 0x92, 0x37, 0x25, 0xeb, 0x03,
	0x9d, 0xc2, 0x7e, 0x9a, 0xab, 0x4d, 0x61, 0x6c, 0xad, 0x03, 0xda, 0x5c, 0x5b, 0xbd, 0x12, 0xc5,
	0x27, 0x51, 0xba, 0xfd, 0x5a, 0xaf, 0x2f, 0xf4, 0x14, 0x0e, 0x4a, 0xc1, 0xa5, 0x96, 0xa2, 0x30,
	0xee, 0xc0, 0xa2, 0x9d, 0x30, 0xfd, 0xe1, 0x80, 0xbb, 0x58, 0x2b, 0xfe, 0xb5, 0x6b, 0xaa, 0x8e,
	0x29, 0x9c, 0xee, 0x29, 0xde, 0xc3, 0xb1, 0xfc, 0xf7, 0x01, 0xb7, 0x67, 0x17, 0x79, 0xf6, 0x9f,
	0x45, 0x68, 0x57, 0xf6, 0xf9, 0x2f, 0x07, 0x1e, 0x77, 0x98, 0xd9, 0x9d, 0x16, 0xc8, 0x85, 0x93,
	0x20, 0x4c, 0xfc, 0x28, 0x64, 0x14, 0xfb, 0x2c, 0x61, 0x14, 0x87, 0xf1, 0x8a, 0xd0, 0xe1, 0x03,
	0x34, 0x82, 0xd3, 0xc5, 0x95, 0x7f, 0x4e, 0x58, 0x72, 0x1d, 0xb0, 0xb3, 0x25, 0xc5, 0xd7, 0x09,
	0x7e, 0x17, 0x5d, 0x85, 0x6c, 0xe8, 0x6c, 0x53, 0x0d, 0xf3, 0x29, 0xc1, 0x8c, 0xdc, 0x93, 0x1e,
	0x7a, 0x02, 0x8f, 0x1a, 0xb2, 0x24, 0x97, 0x51, 0x1c, 0xb0, 0x7b, 0xd4, 0xdf, 0x86, 0x7c, 0x1c,
	0x2e, 0x83, 0xe5, 0x36, 0x10, 0x93, 0x8b, 0x55, 0x12, 0x33, 0x7c, 0x4e, 0x86, 0x03, 0x34, 0x86,
	0xd1, 0x8e, 0x50, 0xf2, 0x36, 0x88, 0x19, 0xc5, 0x2c, 0x88, 0xc2, 0x64, 0x45, 0xc8, 0x70, 0x6f,
	0xf1, 0x11, 0xa6, 0x5c, 0xe5, 0x5e, 0x26, 0xcd, 0xed, 0xe6, 0xa6, 0x9e, 0x40, 0x97, 0xea, 0x8b,
	0xe0, 0xc6, 0xcb, 0x4a, 0xcd, 0x3d, 0xbb, 0xc7, 0xa5, 0xf3, 0xe1, 0x4d, 0xe3, 0xe0, 0x2a, 0x9f,
	0xb7, 0x5d, 0xf5, 0xf1, 0xb2, 0xfe, 0xf2, 0x99, 0x5a, 0xa7, 0x45, 0x36, 0xdf, 0x0d, 0x79, 0xb3,
	0x6f, 0xc1, 0xeb, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x5f, 0x31, 0x79, 0xa4, 0x14, 0x03, 0x00,
	0x00,
}
