// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/types/transaction_log.proto

package iotextypes

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TransactionLogType int32

const (
	TransactionLogType_IN_CONTRACT_TRANSFER       TransactionLogType = 0
	TransactionLogType_WITHDRAW_BUCKET            TransactionLogType = 1
	TransactionLogType_CREATE_BUCKET              TransactionLogType = 2
	TransactionLogType_DEPOSIT_TO_BUCKET          TransactionLogType = 3
	TransactionLogType_CANDIDATE_SELF_STAKE       TransactionLogType = 4
	TransactionLogType_CANDIDATE_REGISTRATION_FEE TransactionLogType = 5
	TransactionLogType_GAS_FEE                    TransactionLogType = 6
	TransactionLogType_NATIVE_TRANSFER            TransactionLogType = 7
	TransactionLogType_DEPOSIT_TO_REWARDING_FUND  TransactionLogType = 8
	TransactionLogType_CLAIM_FROM_REWARDING_FUND  TransactionLogType = 9
)

var TransactionLogType_name = map[int32]string{
	0: "IN_CONTRACT_TRANSFER",
	1: "WITHDRAW_BUCKET",
	2: "CREATE_BUCKET",
	3: "DEPOSIT_TO_BUCKET",
	4: "CANDIDATE_SELF_STAKE",
	5: "CANDIDATE_REGISTRATION_FEE",
	6: "GAS_FEE",
	7: "NATIVE_TRANSFER",
	8: "DEPOSIT_TO_REWARDING_FUND",
	9: "CLAIM_FROM_REWARDING_FUND",
}

var TransactionLogType_value = map[string]int32{
	"IN_CONTRACT_TRANSFER":       0,
	"WITHDRAW_BUCKET":            1,
	"CREATE_BUCKET":              2,
	"DEPOSIT_TO_BUCKET":          3,
	"CANDIDATE_SELF_STAKE":       4,
	"CANDIDATE_REGISTRATION_FEE": 5,
	"GAS_FEE":                    6,
	"NATIVE_TRANSFER":            7,
	"DEPOSIT_TO_REWARDING_FUND":  8,
	"CLAIM_FROM_REWARDING_FUND":  9,
}

func (x TransactionLogType) String() string {
	return proto.EnumName(TransactionLogType_name, int32(x))
}

func (TransactionLogType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ce17c7385702f675, []int{0}
}

type TransactionLog struct {
	ActionHash           []byte                        `protobuf:"bytes,1,opt,name=actionHash,proto3" json:"actionHash,omitempty"`
	NumTransactions      uint64                        `protobuf:"varint,2,opt,name=numTransactions,proto3" json:"numTransactions,omitempty"`
	Transactions         []*TransactionLog_Transaction `protobuf:"bytes,3,rep,name=transactions,proto3" json:"transactions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *TransactionLog) Reset()         { *m = TransactionLog{} }
func (m *TransactionLog) String() string { return proto.CompactTextString(m) }
func (*TransactionLog) ProtoMessage()    {}
func (*TransactionLog) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce17c7385702f675, []int{0}
}

func (m *TransactionLog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionLog.Unmarshal(m, b)
}
func (m *TransactionLog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionLog.Marshal(b, m, deterministic)
}
func (m *TransactionLog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionLog.Merge(m, src)
}
func (m *TransactionLog) XXX_Size() int {
	return xxx_messageInfo_TransactionLog.Size(m)
}
func (m *TransactionLog) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionLog.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionLog proto.InternalMessageInfo

func (m *TransactionLog) GetActionHash() []byte {
	if m != nil {
		return m.ActionHash
	}
	return nil
}

func (m *TransactionLog) GetNumTransactions() uint64 {
	if m != nil {
		return m.NumTransactions
	}
	return 0
}

func (m *TransactionLog) GetTransactions() []*TransactionLog_Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

type TransactionLog_Transaction struct {
	Topic                []byte             `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Amount               string             `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Sender               string             `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty"`
	Recipient            string             `protobuf:"bytes,4,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Type                 TransactionLogType `protobuf:"varint,5,opt,name=type,proto3,enum=iotextypes.TransactionLogType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *TransactionLog_Transaction) Reset()         { *m = TransactionLog_Transaction{} }
func (m *TransactionLog_Transaction) String() string { return proto.CompactTextString(m) }
func (*TransactionLog_Transaction) ProtoMessage()    {}
func (*TransactionLog_Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce17c7385702f675, []int{0, 0}
}

func (m *TransactionLog_Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionLog_Transaction.Unmarshal(m, b)
}
func (m *TransactionLog_Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionLog_Transaction.Marshal(b, m, deterministic)
}
func (m *TransactionLog_Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionLog_Transaction.Merge(m, src)
}
func (m *TransactionLog_Transaction) XXX_Size() int {
	return xxx_messageInfo_TransactionLog_Transaction.Size(m)
}
func (m *TransactionLog_Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionLog_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionLog_Transaction proto.InternalMessageInfo

func (m *TransactionLog_Transaction) GetTopic() []byte {
	if m != nil {
		return m.Topic
	}
	return nil
}

func (m *TransactionLog_Transaction) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *TransactionLog_Transaction) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *TransactionLog_Transaction) GetRecipient() string {
	if m != nil {
		return m.Recipient
	}
	return ""
}

func (m *TransactionLog_Transaction) GetType() TransactionLogType {
	if m != nil {
		return m.Type
	}
	return TransactionLogType_IN_CONTRACT_TRANSFER
}

type TransactionLogs struct {
	Logs                 []*TransactionLog `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *TransactionLogs) Reset()         { *m = TransactionLogs{} }
func (m *TransactionLogs) String() string { return proto.CompactTextString(m) }
func (*TransactionLogs) ProtoMessage()    {}
func (*TransactionLogs) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce17c7385702f675, []int{1}
}

func (m *TransactionLogs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionLogs.Unmarshal(m, b)
}
func (m *TransactionLogs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionLogs.Marshal(b, m, deterministic)
}
func (m *TransactionLogs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionLogs.Merge(m, src)
}
func (m *TransactionLogs) XXX_Size() int {
	return xxx_messageInfo_TransactionLogs.Size(m)
}
func (m *TransactionLogs) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionLogs.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionLogs proto.InternalMessageInfo

func (m *TransactionLogs) GetLogs() []*TransactionLog {
	if m != nil {
		return m.Logs
	}
	return nil
}

func init() {
	proto.RegisterEnum("iotextypes.TransactionLogType", TransactionLogType_name, TransactionLogType_value)
	proto.RegisterType((*TransactionLog)(nil), "iotextypes.TransactionLog")
	proto.RegisterType((*TransactionLog_Transaction)(nil), "iotextypes.TransactionLog.Transaction")
	proto.RegisterType((*TransactionLogs)(nil), "iotextypes.TransactionLogs")
}

func init() { proto.RegisterFile("proto/types/transaction_log.proto", fileDescriptor_ce17c7385702f675) }

var fileDescriptor_ce17c7385702f675 = []byte{
	// 475 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x93, 0x5f, 0x6e, 0x9b, 0x4c,
	0x14, 0xc5, 0x3f, 0xfc, 0x2f, 0x9f, 0xaf, 0xd3, 0xd8, 0x99, 0xa6, 0x15, 0xb5, 0x5a, 0xcb, 0xf5,
	0x43, 0x85, 0x2a, 0x15, 0x4b, 0xae, 0xba, 0x80, 0x09, 0x0c, 0x0e, 0x8d, 0x03, 0xd1, 0x30, 0xa9,
	0xa5, 0x4a, 0x15, 0x22, 0x14, 0x11, 0x2a, 0x9b, 0x41, 0x30, 0x96, 0x9a, 0x15, 0x74, 0x25, 0xdd,
	0x4e, 0xd7, 0x54, 0x31, 0x38, 0x02, 0xa7, 0xca, 0xe3, 0x39, 0xe7, 0x37, 0xf7, 0x1e, 0xae, 0x04,
	0xbc, 0xcd, 0x72, 0x2e, 0xf8, 0x5c, 0xdc, 0x67, 0x51, 0x31, 0x17, 0x79, 0x90, 0x16, 0x41, 0x28,
	0x12, 0x9e, 0xfa, 0x1b, 0x1e, 0xeb, 0x32, 0x43, 0x90, 0x70, 0x11, 0xfd, 0x94, 0xc4, 0xec, 0x4f,
	0x0b, 0x4e, 0x58, 0x4d, 0xad, 0x78, 0x8c, 0x26, 0x00, 0x95, 0xb8, 0x08, 0x8a, 0x3b, 0x55, 0x99,
	0x2a, 0xda, 0x31, 0x6d, 0x38, 0x48, 0x83, 0x61, 0xba, 0xdb, 0x36, 0x1e, 0x15, 0x6a, 0x6b, 0xaa,
	0x68, 0x1d, 0xfa, 0xd8, 0x46, 0x9f, 0xe1, 0x58, 0x34, 0xb1, 0xf6, 0xb4, 0xad, 0x0d, 0x16, 0xef,
	0xf4, 0x7a, 0xbf, 0x7e, 0xb8, 0xbb, 0x29, 0xe9, 0xc1, 0xdb, 0xf1, 0x6f, 0x05, 0x06, 0x8d, 0x14,
	0x9d, 0x41, 0x57, 0xf0, 0x2c, 0x09, 0xf7, 0x05, 0x2b, 0x81, 0x5e, 0x42, 0x2f, 0xd8, 0xf2, 0x5d,
	0x2a, 0x64, 0xa5, 0x3e, 0xdd, 0xab, 0xd2, 0x2f, 0xa2, 0xf4, 0x7b, 0x94, 0xab, 0xed, 0xca, 0xaf,
	0x14, 0x7a, 0x0d, 0xfd, 0x3c, 0x0a, 0x93, 0x2c, 0x89, 0x52, 0xa1, 0x76, 0x64, 0x54, 0x1b, 0x68,
	0x01, 0x9d, 0xb2, 0xa5, 0xda, 0x9d, 0x2a, 0xda, 0xc9, 0x62, 0xf2, 0x74, 0x6f, 0x76, 0x9f, 0x45,
	0x54, 0xb2, 0x33, 0x0c, 0xc3, 0xc3, 0xac, 0x40, 0x3a, 0x74, 0x36, 0x3c, 0x2e, 0x54, 0x45, 0x7e,
	0xfe, 0xf8, 0xe9, 0x31, 0x54, 0x72, 0xef, 0x7f, 0xb5, 0x00, 0xfd, 0x3b, 0x1f, 0xa9, 0x70, 0x66,
	0x3b, 0xbe, 0xe1, 0x3a, 0x8c, 0x62, 0x83, 0xf9, 0x8c, 0x62, 0xc7, 0xb3, 0x08, 0x1d, 0xfd, 0x87,
	0x9e, 0xc3, 0x70, 0x6d, 0xb3, 0x0b, 0x93, 0xe2, 0xb5, 0x7f, 0x7e, 0x63, 0x5c, 0x12, 0x36, 0x52,
	0xd0, 0x29, 0x3c, 0x33, 0x28, 0xc1, 0x8c, 0x3c, 0x58, 0x2d, 0xf4, 0x02, 0x4e, 0x4d, 0x72, 0xed,
	0x7a, 0x36, 0xf3, 0x99, 0xfb, 0x60, 0xb7, 0xcb, 0xc1, 0x06, 0x76, 0x4c, 0xdb, 0x2c, 0x61, 0x8f,
	0xac, 0x2c, 0xdf, 0x63, 0xf8, 0x92, 0x8c, 0x3a, 0x68, 0x02, 0xe3, 0x3a, 0xa1, 0x64, 0x69, 0x7b,
	0x8c, 0x62, 0x66, 0xbb, 0x8e, 0x6f, 0x11, 0x32, 0xea, 0xa2, 0x01, 0x1c, 0x2d, 0xb1, 0x27, 0x45,
	0xaf, 0x6c, 0xe1, 0x60, 0x66, 0x7f, 0x21, 0x75, 0xb5, 0x23, 0xf4, 0x06, 0x5e, 0x35, 0x56, 0x52,
	0xb2, 0xc6, 0xd4, 0xb4, 0x9d, 0xa5, 0x6f, 0xdd, 0x38, 0xe6, 0xe8, 0xff, 0x32, 0x36, 0x56, 0xd8,
	0xbe, 0xf2, 0x2d, 0xea, 0x5e, 0x3d, 0x8e, 0xfb, 0xe7, 0xdf, 0x60, 0x16, 0xf2, 0xad, 0x1e, 0x27,
	0xe2, 0x6e, 0x77, 0x5b, 0xdd, 0x2d, 0xcb, 0xf9, 0x8f, 0x28, 0x14, 0x7a, 0x9c, 0x67, 0xa1, 0x2e,
	0x8f, 0x78, 0xad, 0x7c, 0xfd, 0xb4, 0x27, 0x42, 0xbe, 0x9d, 0x37, 0xa9, 0x4a, 0x7c, 0xa8, 0x7e,
	0x89, 0x98, 0x6f, 0x82, 0x34, 0x9e, 0xd7, 0xd7, 0xbf, 0xed, 0xc9, 0xe0, 0xe3, 0xdf, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xc7, 0x17, 0x1a, 0x1b, 0x34, 0x03, 0x00, 0x00,
}
