// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/iotexproject/iotex-proto/golang/iotexapi (interfaces: APIServiceServer,APIServiceClient,BundleAPIServiceServer,BundleAPIServiceClient)
//
// Generated by this command:
//
//	mockgen -destination=./golang/iotexapi/mock_iotexapi/mock_iotexapi.go github.com/iotexproject/iotex-proto/golang/iotexapi APIServiceServer,APIServiceClient,BundleAPIServiceServer,BundleAPIServiceClient
//

// Package mock_iotexapi is a generated GoMock package.
package mock_iotexapi

import (
	context "context"
	reflect "reflect"

	iotexapi "github.com/iotexproject/iotex-proto/golang/iotexapi"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockAPIServiceServer is a mock of APIServiceServer interface.
type MockAPIServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockAPIServiceServerMockRecorder
	isgomock struct{}
}

// MockAPIServiceServerMockRecorder is the mock recorder for MockAPIServiceServer.
type MockAPIServiceServerMockRecorder struct {
	mock *MockAPIServiceServer
}

// NewMockAPIServiceServer creates a new mock instance.
func NewMockAPIServiceServer(ctrl *gomock.Controller) *MockAPIServiceServer {
	mock := &MockAPIServiceServer{ctrl: ctrl}
	mock.recorder = &MockAPIServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPIServiceServer) EXPECT() *MockAPIServiceServerMockRecorder {
	return m.recorder
}

// EstimateActionGasConsumption mocks base method.
func (m *MockAPIServiceServer) EstimateActionGasConsumption(arg0 context.Context, arg1 *iotexapi.EstimateActionGasConsumptionRequest) (*iotexapi.EstimateActionGasConsumptionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EstimateActionGasConsumption", arg0, arg1)
	ret0, _ := ret[0].(*iotexapi.EstimateActionGasConsumptionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EstimateActionGasConsumption indicates an expected call of EstimateActionGasConsumption.
func (mr *MockAPIServiceServerMockRecorder) EstimateActionGasConsumption(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EstimateActionGasConsumption", reflect.TypeOf((*MockAPIServiceServer)(nil).EstimateActionGasConsumption), arg0, arg1)
}

// EstimateGasForAction mocks base method.
func (m *MockAPIServiceServer) EstimateGasForAction(arg0 context.Context, arg1 *iotexapi.EstimateGasForActionRequest) (*iotexapi.EstimateGasForActionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EstimateGasForAction", arg0, arg1)
	ret0, _ := ret[0].(*iotexapi.EstimateGasForActionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EstimateGasForAction indicates an expected call of EstimateGasForAction.
func (mr *MockAPIServiceServerMockRecorder) EstimateGasForAction(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EstimateGasForAction", reflect.TypeOf((*MockAPIServiceServer)(nil).EstimateGasForAction), arg0, arg1)
}

// GetAccount mocks base method.
func (m *MockAPIServiceServer) GetAccount(arg0 context.Context, arg1 *iotexapi.GetAccountRequest) (*iotexapi.GetAccountResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccount", arg0, arg1)
	ret0, _ := ret[0].(*iotexapi.GetAccountResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccount indicates an expected call of GetAccount.
func (mr *MockAPIServiceServerMockRecorder) GetAccount(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccount", reflect.TypeOf((*MockAPIServiceServer)(nil).GetAccount), arg0, arg1)
}

// GetActPoolActions mocks base method.
func (m *MockAPIServiceServer) GetActPoolActions(arg0 context.Context, arg1 *iotexapi.GetActPoolActionsRequest) (*iotexapi.GetActPoolActionsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActPoolActions", arg0, arg1)
	ret0, _ := ret[0].(*iotexapi.GetActPoolActionsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActPoolActions indicates an expected call of GetActPoolActions.
func (mr *MockAPIServiceServerMockRecorder) GetActPoolActions(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActPoolActions", reflect.TypeOf((*MockAPIServiceServer)(nil).GetActPoolActions), arg0, arg1)
}

// GetActions mocks base method.
func (m *MockAPIServiceServer) GetActions(arg0 context.Context, arg1 *iotexapi.GetActionsRequest) (*iotexapi.GetActionsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActions", arg0, arg1)
	ret0, _ := ret[0].(*iotexapi.GetActionsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActions indicates an expected call of GetActions.
func (mr *MockAPIServiceServerMockRecorder) GetActions(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActions", reflect.TypeOf((*MockAPIServiceServer)(nil).GetActions), arg0, arg1)
}

// GetBlockMetas mocks base method.
func (m *MockAPIServiceServer) GetBlockMetas(arg0 context.Context, arg1 *iotexapi.GetBlockMetasRequest) (*iotexapi.GetBlockMetasResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlockMetas", arg0, arg1)
	ret0, _ := ret[0].(*iotexapi.GetBlockMetasResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlockMetas indicates an expected call of GetBlockMetas.
func (mr *MockAPIServiceServerMockRecorder) GetBlockMetas(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockMetas", reflect.TypeOf((*MockAPIServiceServer)(nil).GetBlockMetas), arg0, arg1)
}

// GetChainMeta mocks base method.
func (m *MockAPIServiceServer) GetChainMeta(arg0 context.Context, arg1 *iotexapi.GetChainMetaRequest) (*iotexapi.GetChainMetaResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChainMeta", arg0, arg1)
	ret0, _ := ret[0].(*iotexapi.GetChainMetaResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChainMeta indicates an expected call of GetChainMeta.
func (mr *MockAPIServiceServerMockRecorder) GetChainMeta(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChainMeta", reflect.TypeOf((*MockAPIServiceServer)(nil).GetChainMeta), arg0, arg1)
}

// GetElectionBuckets mocks base method.
func (m *MockAPIServiceServer) GetElectionBuckets(arg0 context.Context, arg1 *iotexapi.GetElectionBucketsRequest) (*iotexapi.GetElectionBucketsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetElectionBuckets", arg0, arg1)
	ret0, _ := ret[0].(*iotexapi.GetElectionBucketsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetElectionBuckets indicates an expected call of GetElectionBuckets.
func (mr *MockAPIServiceServerMockRecorder) GetElectionBuckets(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetElectionBuckets", reflect.TypeOf((*MockAPIServiceServer)(nil).GetElectionBuckets), arg0, arg1)
}

// GetEpochMeta mocks base method.
func (m *MockAPIServiceServer) GetEpochMeta(arg0 context.Context, arg1 *iotexapi.GetEpochMetaRequest) (*iotexapi.GetEpochMetaResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEpochMeta", arg0, arg1)
	ret0, _ := ret[0].(*iotexapi.GetEpochMetaResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEpochMeta indicates an expected call of GetEpochMeta.
func (mr *MockAPIServiceServerMockRecorder) GetEpochMeta(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEpochMeta", reflect.TypeOf((*MockAPIServiceServer)(nil).GetEpochMeta), arg0, arg1)
}

// GetEvmTransfersByActionHash mocks base method.
func (m *MockAPIServiceServer) GetEvmTransfersByActionHash(arg0 context.Context, arg1 *iotexapi.GetEvmTransfersByActionHashRequest) (*iotexapi.GetEvmTransfersByActionHashResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEvmTransfersByActionHash", arg0, arg1)
	ret0, _ := ret[0].(*iotexapi.GetEvmTransfersByActionHashResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEvmTransfersByActionHash indicates an expected call of GetEvmTransfersByActionHash.
func (mr *MockAPIServiceServerMockRecorder) GetEvmTransfersByActionHash(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEvmTransfersByActionHash", reflect.TypeOf((*MockAPIServiceServer)(nil).GetEvmTransfersByActionHash), arg0, arg1)
}

// GetEvmTransfersByBlockHeight mocks base method.
func (m *MockAPIServiceServer) GetEvmTransfersByBlockHeight(arg0 context.Context, arg1 *iotexapi.GetEvmTransfersByBlockHeightRequest) (*iotexapi.GetEvmTransfersByBlockHeightResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEvmTransfersByBlockHeight", arg0, arg1)
	ret0, _ := ret[0].(*iotexapi.GetEvmTransfersByBlockHeightResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEvmTransfersByBlockHeight indicates an expected call of GetEvmTransfersByBlockHeight.
func (mr *MockAPIServiceServerMockRecorder) GetEvmTransfersByBlockHeight(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEvmTransfersByBlockHeight", reflect.TypeOf((*MockAPIServiceServer)(nil).GetEvmTransfersByBlockHeight), arg0, arg1)
}

// GetLogs mocks base method.
func (m *MockAPIServiceServer) GetLogs(arg0 context.Context, arg1 *iotexapi.GetLogsRequest) (*iotexapi.GetLogsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLogs", arg0, arg1)
	ret0, _ := ret[0].(*iotexapi.GetLogsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLogs indicates an expected call of GetLogs.
func (mr *MockAPIServiceServerMockRecorder) GetLogs(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLogs", reflect.TypeOf((*MockAPIServiceServer)(nil).GetLogs), arg0, arg1)
}

// GetRawBlocks mocks base method.
func (m *MockAPIServiceServer) GetRawBlocks(arg0 context.Context, arg1 *iotexapi.GetRawBlocksRequest) (*iotexapi.GetRawBlocksResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRawBlocks", arg0, arg1)
	ret0, _ := ret[0].(*iotexapi.GetRawBlocksResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRawBlocks indicates an expected call of GetRawBlocks.
func (mr *MockAPIServiceServerMockRecorder) GetRawBlocks(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRawBlocks", reflect.TypeOf((*MockAPIServiceServer)(nil).GetRawBlocks), arg0, arg1)
}

// GetReceiptByAction mocks base method.
func (m *MockAPIServiceServer) GetReceiptByAction(arg0 context.Context, arg1 *iotexapi.GetReceiptByActionRequest) (*iotexapi.GetReceiptByActionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReceiptByAction", arg0, arg1)
	ret0, _ := ret[0].(*iotexapi.GetReceiptByActionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReceiptByAction indicates an expected call of GetReceiptByAction.
func (mr *MockAPIServiceServerMockRecorder) GetReceiptByAction(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReceiptByAction", reflect.TypeOf((*MockAPIServiceServer)(nil).GetReceiptByAction), arg0, arg1)
}

// GetServerMeta mocks base method.
func (m *MockAPIServiceServer) GetServerMeta(arg0 context.Context, arg1 *iotexapi.GetServerMetaRequest) (*iotexapi.GetServerMetaResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServerMeta", arg0, arg1)
	ret0, _ := ret[0].(*iotexapi.GetServerMetaResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServerMeta indicates an expected call of GetServerMeta.
func (mr *MockAPIServiceServerMockRecorder) GetServerMeta(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServerMeta", reflect.TypeOf((*MockAPIServiceServer)(nil).GetServerMeta), arg0, arg1)
}

// GetTransactionLogByActionHash mocks base method.
func (m *MockAPIServiceServer) GetTransactionLogByActionHash(arg0 context.Context, arg1 *iotexapi.GetTransactionLogByActionHashRequest) (*iotexapi.GetTransactionLogByActionHashResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionLogByActionHash", arg0, arg1)
	ret0, _ := ret[0].(*iotexapi.GetTransactionLogByActionHashResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactionLogByActionHash indicates an expected call of GetTransactionLogByActionHash.
func (mr *MockAPIServiceServerMockRecorder) GetTransactionLogByActionHash(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionLogByActionHash", reflect.TypeOf((*MockAPIServiceServer)(nil).GetTransactionLogByActionHash), arg0, arg1)
}

// GetTransactionLogByBlockHeight mocks base method.
func (m *MockAPIServiceServer) GetTransactionLogByBlockHeight(arg0 context.Context, arg1 *iotexapi.GetTransactionLogByBlockHeightRequest) (*iotexapi.GetTransactionLogByBlockHeightResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionLogByBlockHeight", arg0, arg1)
	ret0, _ := ret[0].(*iotexapi.GetTransactionLogByBlockHeightResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactionLogByBlockHeight indicates an expected call of GetTransactionLogByBlockHeight.
func (mr *MockAPIServiceServerMockRecorder) GetTransactionLogByBlockHeight(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionLogByBlockHeight", reflect.TypeOf((*MockAPIServiceServer)(nil).GetTransactionLogByBlockHeight), arg0, arg1)
}

// ReadContract mocks base method.
func (m *MockAPIServiceServer) ReadContract(arg0 context.Context, arg1 *iotexapi.ReadContractRequest) (*iotexapi.ReadContractResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadContract", arg0, arg1)
	ret0, _ := ret[0].(*iotexapi.ReadContractResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadContract indicates an expected call of ReadContract.
func (mr *MockAPIServiceServerMockRecorder) ReadContract(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadContract", reflect.TypeOf((*MockAPIServiceServer)(nil).ReadContract), arg0, arg1)
}

// ReadContractStorage mocks base method.
func (m *MockAPIServiceServer) ReadContractStorage(arg0 context.Context, arg1 *iotexapi.ReadContractStorageRequest) (*iotexapi.ReadContractStorageResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadContractStorage", arg0, arg1)
	ret0, _ := ret[0].(*iotexapi.ReadContractStorageResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadContractStorage indicates an expected call of ReadContractStorage.
func (mr *MockAPIServiceServerMockRecorder) ReadContractStorage(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadContractStorage", reflect.TypeOf((*MockAPIServiceServer)(nil).ReadContractStorage), arg0, arg1)
}

// ReadState mocks base method.
func (m *MockAPIServiceServer) ReadState(arg0 context.Context, arg1 *iotexapi.ReadStateRequest) (*iotexapi.ReadStateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadState", arg0, arg1)
	ret0, _ := ret[0].(*iotexapi.ReadStateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadState indicates an expected call of ReadState.
func (mr *MockAPIServiceServerMockRecorder) ReadState(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadState", reflect.TypeOf((*MockAPIServiceServer)(nil).ReadState), arg0, arg1)
}

// SendAction mocks base method.
func (m *MockAPIServiceServer) SendAction(arg0 context.Context, arg1 *iotexapi.SendActionRequest) (*iotexapi.SendActionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendAction", arg0, arg1)
	ret0, _ := ret[0].(*iotexapi.SendActionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendAction indicates an expected call of SendAction.
func (mr *MockAPIServiceServerMockRecorder) SendAction(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendAction", reflect.TypeOf((*MockAPIServiceServer)(nil).SendAction), arg0, arg1)
}

// StreamBlocks mocks base method.
func (m *MockAPIServiceServer) StreamBlocks(arg0 *iotexapi.StreamBlocksRequest, arg1 grpc.ServerStreamingServer[iotexapi.StreamBlocksResponse]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamBlocks", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// StreamBlocks indicates an expected call of StreamBlocks.
func (mr *MockAPIServiceServerMockRecorder) StreamBlocks(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamBlocks", reflect.TypeOf((*MockAPIServiceServer)(nil).StreamBlocks), arg0, arg1)
}

// StreamLogs mocks base method.
func (m *MockAPIServiceServer) StreamLogs(arg0 *iotexapi.StreamLogsRequest, arg1 grpc.ServerStreamingServer[iotexapi.StreamLogsResponse]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamLogs", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// StreamLogs indicates an expected call of StreamLogs.
func (mr *MockAPIServiceServerMockRecorder) StreamLogs(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamLogs", reflect.TypeOf((*MockAPIServiceServer)(nil).StreamLogs), arg0, arg1)
}

// SuggestGasPrice mocks base method.
func (m *MockAPIServiceServer) SuggestGasPrice(arg0 context.Context, arg1 *iotexapi.SuggestGasPriceRequest) (*iotexapi.SuggestGasPriceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SuggestGasPrice", arg0, arg1)
	ret0, _ := ret[0].(*iotexapi.SuggestGasPriceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SuggestGasPrice indicates an expected call of SuggestGasPrice.
func (mr *MockAPIServiceServerMockRecorder) SuggestGasPrice(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SuggestGasPrice", reflect.TypeOf((*MockAPIServiceServer)(nil).SuggestGasPrice), arg0, arg1)
}

// TraceTransactionStructLogs mocks base method.
func (m *MockAPIServiceServer) TraceTransactionStructLogs(arg0 context.Context, arg1 *iotexapi.TraceTransactionStructLogsRequest) (*iotexapi.TraceTransactionStructLogsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TraceTransactionStructLogs", arg0, arg1)
	ret0, _ := ret[0].(*iotexapi.TraceTransactionStructLogsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TraceTransactionStructLogs indicates an expected call of TraceTransactionStructLogs.
func (mr *MockAPIServiceServerMockRecorder) TraceTransactionStructLogs(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TraceTransactionStructLogs", reflect.TypeOf((*MockAPIServiceServer)(nil).TraceTransactionStructLogs), arg0, arg1)
}

// MockAPIServiceClient is a mock of APIServiceClient interface.
type MockAPIServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockAPIServiceClientMockRecorder
	isgomock struct{}
}

// MockAPIServiceClientMockRecorder is the mock recorder for MockAPIServiceClient.
type MockAPIServiceClientMockRecorder struct {
	mock *MockAPIServiceClient
}

// NewMockAPIServiceClient creates a new mock instance.
func NewMockAPIServiceClient(ctrl *gomock.Controller) *MockAPIServiceClient {
	mock := &MockAPIServiceClient{ctrl: ctrl}
	mock.recorder = &MockAPIServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPIServiceClient) EXPECT() *MockAPIServiceClientMockRecorder {
	return m.recorder
}

// EstimateActionGasConsumption mocks base method.
func (m *MockAPIServiceClient) EstimateActionGasConsumption(ctx context.Context, in *iotexapi.EstimateActionGasConsumptionRequest, opts ...grpc.CallOption) (*iotexapi.EstimateActionGasConsumptionResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "EstimateActionGasConsumption", varargs...)
	ret0, _ := ret[0].(*iotexapi.EstimateActionGasConsumptionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EstimateActionGasConsumption indicates an expected call of EstimateActionGasConsumption.
func (mr *MockAPIServiceClientMockRecorder) EstimateActionGasConsumption(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EstimateActionGasConsumption", reflect.TypeOf((*MockAPIServiceClient)(nil).EstimateActionGasConsumption), varargs...)
}

// EstimateGasForAction mocks base method.
func (m *MockAPIServiceClient) EstimateGasForAction(ctx context.Context, in *iotexapi.EstimateGasForActionRequest, opts ...grpc.CallOption) (*iotexapi.EstimateGasForActionResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "EstimateGasForAction", varargs...)
	ret0, _ := ret[0].(*iotexapi.EstimateGasForActionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EstimateGasForAction indicates an expected call of EstimateGasForAction.
func (mr *MockAPIServiceClientMockRecorder) EstimateGasForAction(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EstimateGasForAction", reflect.TypeOf((*MockAPIServiceClient)(nil).EstimateGasForAction), varargs...)
}

// GetAccount mocks base method.
func (m *MockAPIServiceClient) GetAccount(ctx context.Context, in *iotexapi.GetAccountRequest, opts ...grpc.CallOption) (*iotexapi.GetAccountResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAccount", varargs...)
	ret0, _ := ret[0].(*iotexapi.GetAccountResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccount indicates an expected call of GetAccount.
func (mr *MockAPIServiceClientMockRecorder) GetAccount(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccount", reflect.TypeOf((*MockAPIServiceClient)(nil).GetAccount), varargs...)
}

// GetActPoolActions mocks base method.
func (m *MockAPIServiceClient) GetActPoolActions(ctx context.Context, in *iotexapi.GetActPoolActionsRequest, opts ...grpc.CallOption) (*iotexapi.GetActPoolActionsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetActPoolActions", varargs...)
	ret0, _ := ret[0].(*iotexapi.GetActPoolActionsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActPoolActions indicates an expected call of GetActPoolActions.
func (mr *MockAPIServiceClientMockRecorder) GetActPoolActions(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActPoolActions", reflect.TypeOf((*MockAPIServiceClient)(nil).GetActPoolActions), varargs...)
}

// GetActions mocks base method.
func (m *MockAPIServiceClient) GetActions(ctx context.Context, in *iotexapi.GetActionsRequest, opts ...grpc.CallOption) (*iotexapi.GetActionsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetActions", varargs...)
	ret0, _ := ret[0].(*iotexapi.GetActionsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActions indicates an expected call of GetActions.
func (mr *MockAPIServiceClientMockRecorder) GetActions(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActions", reflect.TypeOf((*MockAPIServiceClient)(nil).GetActions), varargs...)
}

// GetBlockMetas mocks base method.
func (m *MockAPIServiceClient) GetBlockMetas(ctx context.Context, in *iotexapi.GetBlockMetasRequest, opts ...grpc.CallOption) (*iotexapi.GetBlockMetasResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetBlockMetas", varargs...)
	ret0, _ := ret[0].(*iotexapi.GetBlockMetasResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlockMetas indicates an expected call of GetBlockMetas.
func (mr *MockAPIServiceClientMockRecorder) GetBlockMetas(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockMetas", reflect.TypeOf((*MockAPIServiceClient)(nil).GetBlockMetas), varargs...)
}

// GetChainMeta mocks base method.
func (m *MockAPIServiceClient) GetChainMeta(ctx context.Context, in *iotexapi.GetChainMetaRequest, opts ...grpc.CallOption) (*iotexapi.GetChainMetaResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetChainMeta", varargs...)
	ret0, _ := ret[0].(*iotexapi.GetChainMetaResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChainMeta indicates an expected call of GetChainMeta.
func (mr *MockAPIServiceClientMockRecorder) GetChainMeta(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChainMeta", reflect.TypeOf((*MockAPIServiceClient)(nil).GetChainMeta), varargs...)
}

// GetElectionBuckets mocks base method.
func (m *MockAPIServiceClient) GetElectionBuckets(ctx context.Context, in *iotexapi.GetElectionBucketsRequest, opts ...grpc.CallOption) (*iotexapi.GetElectionBucketsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetElectionBuckets", varargs...)
	ret0, _ := ret[0].(*iotexapi.GetElectionBucketsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetElectionBuckets indicates an expected call of GetElectionBuckets.
func (mr *MockAPIServiceClientMockRecorder) GetElectionBuckets(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetElectionBuckets", reflect.TypeOf((*MockAPIServiceClient)(nil).GetElectionBuckets), varargs...)
}

// GetEpochMeta mocks base method.
func (m *MockAPIServiceClient) GetEpochMeta(ctx context.Context, in *iotexapi.GetEpochMetaRequest, opts ...grpc.CallOption) (*iotexapi.GetEpochMetaResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetEpochMeta", varargs...)
	ret0, _ := ret[0].(*iotexapi.GetEpochMetaResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEpochMeta indicates an expected call of GetEpochMeta.
func (mr *MockAPIServiceClientMockRecorder) GetEpochMeta(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEpochMeta", reflect.TypeOf((*MockAPIServiceClient)(nil).GetEpochMeta), varargs...)
}

// GetEvmTransfersByActionHash mocks base method.
func (m *MockAPIServiceClient) GetEvmTransfersByActionHash(ctx context.Context, in *iotexapi.GetEvmTransfersByActionHashRequest, opts ...grpc.CallOption) (*iotexapi.GetEvmTransfersByActionHashResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetEvmTransfersByActionHash", varargs...)
	ret0, _ := ret[0].(*iotexapi.GetEvmTransfersByActionHashResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEvmTransfersByActionHash indicates an expected call of GetEvmTransfersByActionHash.
func (mr *MockAPIServiceClientMockRecorder) GetEvmTransfersByActionHash(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEvmTransfersByActionHash", reflect.TypeOf((*MockAPIServiceClient)(nil).GetEvmTransfersByActionHash), varargs...)
}

// GetEvmTransfersByBlockHeight mocks base method.
func (m *MockAPIServiceClient) GetEvmTransfersByBlockHeight(ctx context.Context, in *iotexapi.GetEvmTransfersByBlockHeightRequest, opts ...grpc.CallOption) (*iotexapi.GetEvmTransfersByBlockHeightResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetEvmTransfersByBlockHeight", varargs...)
	ret0, _ := ret[0].(*iotexapi.GetEvmTransfersByBlockHeightResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEvmTransfersByBlockHeight indicates an expected call of GetEvmTransfersByBlockHeight.
func (mr *MockAPIServiceClientMockRecorder) GetEvmTransfersByBlockHeight(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEvmTransfersByBlockHeight", reflect.TypeOf((*MockAPIServiceClient)(nil).GetEvmTransfersByBlockHeight), varargs...)
}

// GetLogs mocks base method.
func (m *MockAPIServiceClient) GetLogs(ctx context.Context, in *iotexapi.GetLogsRequest, opts ...grpc.CallOption) (*iotexapi.GetLogsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetLogs", varargs...)
	ret0, _ := ret[0].(*iotexapi.GetLogsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLogs indicates an expected call of GetLogs.
func (mr *MockAPIServiceClientMockRecorder) GetLogs(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLogs", reflect.TypeOf((*MockAPIServiceClient)(nil).GetLogs), varargs...)
}

// GetRawBlocks mocks base method.
func (m *MockAPIServiceClient) GetRawBlocks(ctx context.Context, in *iotexapi.GetRawBlocksRequest, opts ...grpc.CallOption) (*iotexapi.GetRawBlocksResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetRawBlocks", varargs...)
	ret0, _ := ret[0].(*iotexapi.GetRawBlocksResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRawBlocks indicates an expected call of GetRawBlocks.
func (mr *MockAPIServiceClientMockRecorder) GetRawBlocks(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRawBlocks", reflect.TypeOf((*MockAPIServiceClient)(nil).GetRawBlocks), varargs...)
}

// GetReceiptByAction mocks base method.
func (m *MockAPIServiceClient) GetReceiptByAction(ctx context.Context, in *iotexapi.GetReceiptByActionRequest, opts ...grpc.CallOption) (*iotexapi.GetReceiptByActionResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetReceiptByAction", varargs...)
	ret0, _ := ret[0].(*iotexapi.GetReceiptByActionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReceiptByAction indicates an expected call of GetReceiptByAction.
func (mr *MockAPIServiceClientMockRecorder) GetReceiptByAction(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReceiptByAction", reflect.TypeOf((*MockAPIServiceClient)(nil).GetReceiptByAction), varargs...)
}

// GetServerMeta mocks base method.
func (m *MockAPIServiceClient) GetServerMeta(ctx context.Context, in *iotexapi.GetServerMetaRequest, opts ...grpc.CallOption) (*iotexapi.GetServerMetaResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetServerMeta", varargs...)
	ret0, _ := ret[0].(*iotexapi.GetServerMetaResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServerMeta indicates an expected call of GetServerMeta.
func (mr *MockAPIServiceClientMockRecorder) GetServerMeta(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServerMeta", reflect.TypeOf((*MockAPIServiceClient)(nil).GetServerMeta), varargs...)
}

// GetTransactionLogByActionHash mocks base method.
func (m *MockAPIServiceClient) GetTransactionLogByActionHash(ctx context.Context, in *iotexapi.GetTransactionLogByActionHashRequest, opts ...grpc.CallOption) (*iotexapi.GetTransactionLogByActionHashResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetTransactionLogByActionHash", varargs...)
	ret0, _ := ret[0].(*iotexapi.GetTransactionLogByActionHashResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactionLogByActionHash indicates an expected call of GetTransactionLogByActionHash.
func (mr *MockAPIServiceClientMockRecorder) GetTransactionLogByActionHash(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionLogByActionHash", reflect.TypeOf((*MockAPIServiceClient)(nil).GetTransactionLogByActionHash), varargs...)
}

// GetTransactionLogByBlockHeight mocks base method.
func (m *MockAPIServiceClient) GetTransactionLogByBlockHeight(ctx context.Context, in *iotexapi.GetTransactionLogByBlockHeightRequest, opts ...grpc.CallOption) (*iotexapi.GetTransactionLogByBlockHeightResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetTransactionLogByBlockHeight", varargs...)
	ret0, _ := ret[0].(*iotexapi.GetTransactionLogByBlockHeightResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactionLogByBlockHeight indicates an expected call of GetTransactionLogByBlockHeight.
func (mr *MockAPIServiceClientMockRecorder) GetTransactionLogByBlockHeight(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionLogByBlockHeight", reflect.TypeOf((*MockAPIServiceClient)(nil).GetTransactionLogByBlockHeight), varargs...)
}

// ReadContract mocks base method.
func (m *MockAPIServiceClient) ReadContract(ctx context.Context, in *iotexapi.ReadContractRequest, opts ...grpc.CallOption) (*iotexapi.ReadContractResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ReadContract", varargs...)
	ret0, _ := ret[0].(*iotexapi.ReadContractResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadContract indicates an expected call of ReadContract.
func (mr *MockAPIServiceClientMockRecorder) ReadContract(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadContract", reflect.TypeOf((*MockAPIServiceClient)(nil).ReadContract), varargs...)
}

// ReadContractStorage mocks base method.
func (m *MockAPIServiceClient) ReadContractStorage(ctx context.Context, in *iotexapi.ReadContractStorageRequest, opts ...grpc.CallOption) (*iotexapi.ReadContractStorageResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ReadContractStorage", varargs...)
	ret0, _ := ret[0].(*iotexapi.ReadContractStorageResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadContractStorage indicates an expected call of ReadContractStorage.
func (mr *MockAPIServiceClientMockRecorder) ReadContractStorage(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadContractStorage", reflect.TypeOf((*MockAPIServiceClient)(nil).ReadContractStorage), varargs...)
}

// ReadState mocks base method.
func (m *MockAPIServiceClient) ReadState(ctx context.Context, in *iotexapi.ReadStateRequest, opts ...grpc.CallOption) (*iotexapi.ReadStateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ReadState", varargs...)
	ret0, _ := ret[0].(*iotexapi.ReadStateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadState indicates an expected call of ReadState.
func (mr *MockAPIServiceClientMockRecorder) ReadState(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadState", reflect.TypeOf((*MockAPIServiceClient)(nil).ReadState), varargs...)
}

// SendAction mocks base method.
func (m *MockAPIServiceClient) SendAction(ctx context.Context, in *iotexapi.SendActionRequest, opts ...grpc.CallOption) (*iotexapi.SendActionResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SendAction", varargs...)
	ret0, _ := ret[0].(*iotexapi.SendActionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendAction indicates an expected call of SendAction.
func (mr *MockAPIServiceClientMockRecorder) SendAction(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendAction", reflect.TypeOf((*MockAPIServiceClient)(nil).SendAction), varargs...)
}

// StreamBlocks mocks base method.
func (m *MockAPIServiceClient) StreamBlocks(ctx context.Context, in *iotexapi.StreamBlocksRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[iotexapi.StreamBlocksResponse], error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "StreamBlocks", varargs...)
	ret0, _ := ret[0].(grpc.ServerStreamingClient[iotexapi.StreamBlocksResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StreamBlocks indicates an expected call of StreamBlocks.
func (mr *MockAPIServiceClientMockRecorder) StreamBlocks(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamBlocks", reflect.TypeOf((*MockAPIServiceClient)(nil).StreamBlocks), varargs...)
}

// StreamLogs mocks base method.
func (m *MockAPIServiceClient) StreamLogs(ctx context.Context, in *iotexapi.StreamLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[iotexapi.StreamLogsResponse], error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "StreamLogs", varargs...)
	ret0, _ := ret[0].(grpc.ServerStreamingClient[iotexapi.StreamLogsResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StreamLogs indicates an expected call of StreamLogs.
func (mr *MockAPIServiceClientMockRecorder) StreamLogs(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamLogs", reflect.TypeOf((*MockAPIServiceClient)(nil).StreamLogs), varargs...)
}

// SuggestGasPrice mocks base method.
func (m *MockAPIServiceClient) SuggestGasPrice(ctx context.Context, in *iotexapi.SuggestGasPriceRequest, opts ...grpc.CallOption) (*iotexapi.SuggestGasPriceResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SuggestGasPrice", varargs...)
	ret0, _ := ret[0].(*iotexapi.SuggestGasPriceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SuggestGasPrice indicates an expected call of SuggestGasPrice.
func (mr *MockAPIServiceClientMockRecorder) SuggestGasPrice(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SuggestGasPrice", reflect.TypeOf((*MockAPIServiceClient)(nil).SuggestGasPrice), varargs...)
}

// TraceTransactionStructLogs mocks base method.
func (m *MockAPIServiceClient) TraceTransactionStructLogs(ctx context.Context, in *iotexapi.TraceTransactionStructLogsRequest, opts ...grpc.CallOption) (*iotexapi.TraceTransactionStructLogsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "TraceTransactionStructLogs", varargs...)
	ret0, _ := ret[0].(*iotexapi.TraceTransactionStructLogsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TraceTransactionStructLogs indicates an expected call of TraceTransactionStructLogs.
func (mr *MockAPIServiceClientMockRecorder) TraceTransactionStructLogs(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TraceTransactionStructLogs", reflect.TypeOf((*MockAPIServiceClient)(nil).TraceTransactionStructLogs), varargs...)
}

// MockBundleAPIServiceServer is a mock of BundleAPIServiceServer interface.
type MockBundleAPIServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockBundleAPIServiceServerMockRecorder
	isgomock struct{}
}

// MockBundleAPIServiceServerMockRecorder is the mock recorder for MockBundleAPIServiceServer.
type MockBundleAPIServiceServerMockRecorder struct {
	mock *MockBundleAPIServiceServer
}

// NewMockBundleAPIServiceServer creates a new mock instance.
func NewMockBundleAPIServiceServer(ctrl *gomock.Controller) *MockBundleAPIServiceServer {
	mock := &MockBundleAPIServiceServer{ctrl: ctrl}
	mock.recorder = &MockBundleAPIServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBundleAPIServiceServer) EXPECT() *MockBundleAPIServiceServerMockRecorder {
	return m.recorder
}

// SendBundle mocks base method.
func (m *MockBundleAPIServiceServer) SendBundle(arg0 context.Context, arg1 *iotexapi.SendBundleRequest) (*iotexapi.SendBundleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendBundle", arg0, arg1)
	ret0, _ := ret[0].(*iotexapi.SendBundleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendBundle indicates an expected call of SendBundle.
func (mr *MockBundleAPIServiceServerMockRecorder) SendBundle(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendBundle", reflect.TypeOf((*MockBundleAPIServiceServer)(nil).SendBundle), arg0, arg1)
}

// MockBundleAPIServiceClient is a mock of BundleAPIServiceClient interface.
type MockBundleAPIServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockBundleAPIServiceClientMockRecorder
	isgomock struct{}
}

// MockBundleAPIServiceClientMockRecorder is the mock recorder for MockBundleAPIServiceClient.
type MockBundleAPIServiceClientMockRecorder struct {
	mock *MockBundleAPIServiceClient
}

// NewMockBundleAPIServiceClient creates a new mock instance.
func NewMockBundleAPIServiceClient(ctrl *gomock.Controller) *MockBundleAPIServiceClient {
	mock := &MockBundleAPIServiceClient{ctrl: ctrl}
	mock.recorder = &MockBundleAPIServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBundleAPIServiceClient) EXPECT() *MockBundleAPIServiceClientMockRecorder {
	return m.recorder
}

// SendBundle mocks base method.
func (m *MockBundleAPIServiceClient) SendBundle(ctx context.Context, in *iotexapi.SendBundleRequest, opts ...grpc.CallOption) (*iotexapi.SendBundleResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SendBundle", varargs...)
	ret0, _ := ret[0].(*iotexapi.SendBundleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendBundle indicates an expected call of SendBundle.
func (mr *MockBundleAPIServiceClientMockRecorder) SendBundle(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendBundle", reflect.TypeOf((*MockBundleAPIServiceClient)(nil).SendBundle), varargs...)
}
