// Copyright (c) 2018 IoTeX
// This is an alpha (internal) release and is not suitable for production. This source code is provided 'as is' and no
// warranties are given as to title or non-infringement, merchantability or fitness for purpose and, to the extent
// permitted by law, all liability for your use of the code is disclaimed. This source code is governed by Apache
// License 2.0 that can be found in the LICENSE file.

// To compile the proto, run:
//      protoc -I. -I ./../types --go_out=plugins=grpc:$GOPATH/src *.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.3
// source: proto/rpc/rpc.proto

package iotexrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_UNKNOWN           MessageType = 0
	MessageType_ACTION            MessageType = 1
	MessageType_BLOCK             MessageType = 2
	MessageType_CONSENSUS         MessageType = 3
	MessageType_BLOCK_REQUEST     MessageType = 4
	MessageType_NODE_INFO_REQUEST MessageType = 5
	MessageType_NODE_INFO         MessageType = 6
	MessageType_ACTIONS           MessageType = 7
	MessageType_ACTION_HASH       MessageType = 8
	MessageType_ACTION_REQUEST    MessageType = 9
	MessageType_TEST              MessageType = 10001
	MessageType_BUNDLE            MessageType = 10002
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0:     "UNKNOWN",
		1:     "ACTION",
		2:     "BLOCK",
		3:     "CONSENSUS",
		4:     "BLOCK_REQUEST",
		5:     "NODE_INFO_REQUEST",
		6:     "NODE_INFO",
		7:     "ACTIONS",
		8:     "ACTION_HASH",
		9:     "ACTION_REQUEST",
		10001: "TEST",
		10002: "BUNDLE",
	}
	MessageType_value = map[string]int32{
		"UNKNOWN":           0,
		"ACTION":            1,
		"BLOCK":             2,
		"CONSENSUS":         3,
		"BLOCK_REQUEST":     4,
		"NODE_INFO_REQUEST": 5,
		"NODE_INFO":         6,
		"ACTIONS":           7,
		"ACTION_HASH":       8,
		"ACTION_REQUEST":    9,
		"TEST":              10001,
		"BUNDLE":            10002,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_rpc_rpc_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_proto_rpc_rpc_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_proto_rpc_rpc_proto_rawDescGZIP(), []int{0}
}

type BlockSync struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         uint64                 `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	End           uint64                 `protobuf:"varint,3,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockSync) Reset() {
	*x = BlockSync{}
	mi := &file_proto_rpc_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockSync) ProtoMessage() {}

func (x *BlockSync) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockSync.ProtoReflect.Descriptor instead.
func (*BlockSync) Descriptor() ([]byte, []int) {
	return file_proto_rpc_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *BlockSync) GetStart() uint64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *BlockSync) GetEnd() uint64 {
	if x != nil {
		return x.End
	}
	return 0
}

type ActionSync struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hashes        [][]byte               `protobuf:"bytes,1,rep,name=hashes,proto3" json:"hashes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionSync) Reset() {
	*x = ActionSync{}
	mi := &file_proto_rpc_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionSync) ProtoMessage() {}

func (x *ActionSync) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionSync.ProtoReflect.Descriptor instead.
func (*ActionSync) Descriptor() ([]byte, []int) {
	return file_proto_rpc_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *ActionSync) GetHashes() [][]byte {
	if x != nil {
		return x.Hashes
	}
	return nil
}

type BroadcastMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       uint32                 `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	MsgType       MessageType            `protobuf:"varint,2,opt,name=msg_type,json=msgType,proto3,enum=iotexrpc.MessageType" json:"msg_type,omitempty"`
	MsgBody       []byte                 `protobuf:"bytes,3,opt,name=msg_body,json=msgBody,proto3" json:"msg_body,omitempty"`
	PeerId        string                 `protobuf:"bytes,4,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastMsg) Reset() {
	*x = BroadcastMsg{}
	mi := &file_proto_rpc_rpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastMsg) ProtoMessage() {}

func (x *BroadcastMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_rpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastMsg.ProtoReflect.Descriptor instead.
func (*BroadcastMsg) Descriptor() ([]byte, []int) {
	return file_proto_rpc_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *BroadcastMsg) GetChainId() uint32 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *BroadcastMsg) GetMsgType() MessageType {
	if x != nil {
		return x.MsgType
	}
	return MessageType_UNKNOWN
}

func (x *BroadcastMsg) GetMsgBody() []byte {
	if x != nil {
		return x.MsgBody
	}
	return nil
}

func (x *BroadcastMsg) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *BroadcastMsg) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type UnicastMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       uint32                 `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	MsgType       MessageType            `protobuf:"varint,3,opt,name=msg_type,json=msgType,proto3,enum=iotexrpc.MessageType" json:"msg_type,omitempty"`
	MsgBody       []byte                 `protobuf:"bytes,4,opt,name=msg_body,json=msgBody,proto3" json:"msg_body,omitempty"`
	PeerId        string                 `protobuf:"bytes,5,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnicastMsg) Reset() {
	*x = UnicastMsg{}
	mi := &file_proto_rpc_rpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnicastMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnicastMsg) ProtoMessage() {}

func (x *UnicastMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_rpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnicastMsg.ProtoReflect.Descriptor instead.
func (*UnicastMsg) Descriptor() ([]byte, []int) {
	return file_proto_rpc_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *UnicastMsg) GetChainId() uint32 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *UnicastMsg) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *UnicastMsg) GetMsgType() MessageType {
	if x != nil {
		return x.MsgType
	}
	return MessageType_UNKNOWN
}

func (x *UnicastMsg) GetMsgBody() []byte {
	if x != nil {
		return x.MsgBody
	}
	return nil
}

func (x *UnicastMsg) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *UnicastMsg) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_proto_rpc_rpc_proto protoreflect.FileDescriptor

const file_proto_rpc_rpc_proto_rawDesc = "" +
	"\n" +
	"\x13proto/rpc/rpc.proto\x12\biotexrpc\x1a\x1fgoogle/protobuf/timestamp.proto\"3\n" +
	"\tBlockSync\x12\x14\n" +
	"\x05start\x18\x02 \x01(\x04R\x05start\x12\x10\n" +
	"\x03end\x18\x03 \x01(\x04R\x03end\"$\n" +
	"\n" +
	"ActionSync\x12\x16\n" +
	"\x06hashes\x18\x01 \x03(\fR\x06hashes\"\xc9\x01\n" +
	"\fBroadcastMsg\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\rR\achainId\x120\n" +
	"\bmsg_type\x18\x02 \x01(\x0e2\x15.iotexrpc.MessageTypeR\amsgType\x12\x19\n" +
	"\bmsg_body\x18\x03 \x01(\fR\amsgBody\x12\x17\n" +
	"\apeer_id\x18\x04 \x01(\tR\x06peerId\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xdb\x01\n" +
	"\n" +
	"UnicastMsg\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\rR\achainId\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x120\n" +
	"\bmsg_type\x18\x03 \x01(\x0e2\x15.iotexrpc.MessageTypeR\amsgType\x12\x19\n" +
	"\bmsg_body\x18\x04 \x01(\fR\amsgBody\x12\x17\n" +
	"\apeer_id\x18\x05 \x01(\tR\x06peerId\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp*\xc3\x01\n" +
	"\vMessageType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\n" +
	"\n" +
	"\x06ACTION\x10\x01\x12\t\n" +
	"\x05BLOCK\x10\x02\x12\r\n" +
	"\tCONSENSUS\x10\x03\x12\x11\n" +
	"\rBLOCK_REQUEST\x10\x04\x12\x15\n" +
	"\x11NODE_INFO_REQUEST\x10\x05\x12\r\n" +
	"\tNODE_INFO\x10\x06\x12\v\n" +
	"\aACTIONS\x10\a\x12\x0f\n" +
	"\vACTION_HASH\x10\b\x12\x12\n" +
	"\x0eACTION_REQUEST\x10\t\x12\t\n" +
	"\x04TEST\x10\x91N\x12\v\n" +
	"\x06BUNDLE\x10\x92NBY\n" +
	" com.github.iotexproject.grpc.rpcP\x01Z3github.com/iotexproject/iotex-proto/golang/iotexrpcb\x06proto3"

var (
	file_proto_rpc_rpc_proto_rawDescOnce sync.Once
	file_proto_rpc_rpc_proto_rawDescData []byte
)

func file_proto_rpc_rpc_proto_rawDescGZIP() []byte {
	file_proto_rpc_rpc_proto_rawDescOnce.Do(func() {
		file_proto_rpc_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_rpc_rpc_proto_rawDesc), len(file_proto_rpc_rpc_proto_rawDesc)))
	})
	return file_proto_rpc_rpc_proto_rawDescData
}

var file_proto_rpc_rpc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_rpc_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_rpc_rpc_proto_goTypes = []any{
	(MessageType)(0),              // 0: iotexrpc.MessageType
	(*BlockSync)(nil),             // 1: iotexrpc.BlockSync
	(*ActionSync)(nil),            // 2: iotexrpc.ActionSync
	(*BroadcastMsg)(nil),          // 3: iotexrpc.BroadcastMsg
	(*UnicastMsg)(nil),            // 4: iotexrpc.UnicastMsg
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_proto_rpc_rpc_proto_depIdxs = []int32{
	0, // 0: iotexrpc.BroadcastMsg.msg_type:type_name -> iotexrpc.MessageType
	5, // 1: iotexrpc.BroadcastMsg.timestamp:type_name -> google.protobuf.Timestamp
	0, // 2: iotexrpc.UnicastMsg.msg_type:type_name -> iotexrpc.MessageType
	5, // 3: iotexrpc.UnicastMsg.timestamp:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_rpc_rpc_proto_init() }
func file_proto_rpc_rpc_proto_init() {
	if File_proto_rpc_rpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_rpc_rpc_proto_rawDesc), len(file_proto_rpc_rpc_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_rpc_rpc_proto_goTypes,
		DependencyIndexes: file_proto_rpc_rpc_proto_depIdxs,
		EnumInfos:         file_proto_rpc_rpc_proto_enumTypes,
		MessageInfos:      file_proto_rpc_rpc_proto_msgTypes,
	}.Build()
	File_proto_rpc_rpc_proto = out.File
	file_proto_rpc_rpc_proto_goTypes = nil
	file_proto_rpc_rpc_proto_depIdxs = nil
}
