// Copyright (c) 2018 IoTeX
// This is an alpha (internal) release and is not suitable for production. This source code is provided 'as is' and no
// warranties are given as to title or non-infringement, merchantability or fitness for purpose and, to the extent
// permitted by law, all liability for your use of the code is disclaimed. This source code is governed by Apache
// License 2.0 that can be found in the LICENSE file.

// To compile the proto, run:
//      protoc --go_out=plugins=grpc:$GOPATH/src *.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/testing/testing.proto

package testingpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgBody       []byte                 `protobuf:"bytes,1,opt,name=msg_body,json=msgBody,proto3" json:"msg_body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestPayload) Reset() {
	*x = TestPayload{}
	mi := &file_proto_testing_testing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestPayload) ProtoMessage() {}

func (x *TestPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_testing_testing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestPayload.ProtoReflect.Descriptor instead.
func (*TestPayload) Descriptor() ([]byte, []int) {
	return file_proto_testing_testing_proto_rawDescGZIP(), []int{0}
}

func (x *TestPayload) GetMsgBody() []byte {
	if x != nil {
		return x.MsgBody
	}
	return nil
}

var File_proto_testing_testing_proto protoreflect.FileDescriptor

const file_proto_testing_testing_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/testing/testing.proto\x12\ttestingpb\"(\n" +
	"\vTestPayload\x12\x19\n" +
	"\bmsg_body\x18\x01 \x01(\fR\amsgBodyB^\n" +
	"$com.github.iotexproject.grpc.testingP\x01Z4github.com/iotexproject/iotex-proto/golang/testingpbb\x06proto3"

var (
	file_proto_testing_testing_proto_rawDescOnce sync.Once
	file_proto_testing_testing_proto_rawDescData []byte
)

func file_proto_testing_testing_proto_rawDescGZIP() []byte {
	file_proto_testing_testing_proto_rawDescOnce.Do(func() {
		file_proto_testing_testing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_testing_testing_proto_rawDesc), len(file_proto_testing_testing_proto_rawDesc)))
	})
	return file_proto_testing_testing_proto_rawDescData
}

var file_proto_testing_testing_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_testing_testing_proto_goTypes = []any{
	(*TestPayload)(nil), // 0: testingpb.TestPayload
}
var file_proto_testing_testing_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_testing_testing_proto_init() }
func file_proto_testing_testing_proto_init() {
	if File_proto_testing_testing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_testing_testing_proto_rawDesc), len(file_proto_testing_testing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_testing_testing_proto_goTypes,
		DependencyIndexes: file_proto_testing_testing_proto_depIdxs,
		MessageInfos:      file_proto_testing_testing_proto_msgTypes,
	}.Build()
	File_proto_testing_testing_proto = out.File
	file_proto_testing_testing_proto_goTypes = nil
	file_proto_testing_testing_proto_depIdxs = nil
}
