// Copyright (c) 2020 IoTeX
// This is an alpha (internal) release and is not suitable for production. This source code is provided 'as is' and no
// warranties are given as to title or non-infringement, merchantability or fitness for purpose and, to the extent
// permitted by law, all liability for your use of the code is disclaimed. This source code is governed by Apache
// License 2.0 that can be found in the LICENSE file.

// To compile the proto, run:
//      protoc -I. -I ./../types --go_out=plugins=grpc:$GOPATH/src *.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.23.3
// source: proto/api/read_state.proto

package iotexapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReadStakingDataMethod_Name int32

const (
	ReadStakingDataMethod_INVALID              ReadStakingDataMethod_Name = 0
	ReadStakingDataMethod_BUCKETS              ReadStakingDataMethod_Name = 1
	ReadStakingDataMethod_BUCKETS_BY_VOTER     ReadStakingDataMethod_Name = 2
	ReadStakingDataMethod_BUCKETS_BY_CANDIDATE ReadStakingDataMethod_Name = 3
	ReadStakingDataMethod_CANDIDATES           ReadStakingDataMethod_Name = 4
	ReadStakingDataMethod_CANDIDATE_BY_NAME    ReadStakingDataMethod_Name = 5
	ReadStakingDataMethod_BUCKETS_BY_INDEXES   ReadStakingDataMethod_Name = 6
	ReadStakingDataMethod_CANDIDATE_BY_ADDRESS ReadStakingDataMethod_Name = 7
	ReadStakingDataMethod_TOTAL_STAKING_AMOUNT ReadStakingDataMethod_Name = 8
	ReadStakingDataMethod_BUCKETS_COUNT        ReadStakingDataMethod_Name = 9
	// 10-19 reserved for native staking
	ReadStakingDataMethod_COMPOSITE_BUCKETS              ReadStakingDataMethod_Name = 20
	ReadStakingDataMethod_COMPOSITE_BUCKETS_BY_VOTER     ReadStakingDataMethod_Name = 21
	ReadStakingDataMethod_COMPOSITE_BUCKETS_BY_CANDIDATE ReadStakingDataMethod_Name = 22
	ReadStakingDataMethod_COMPOSITE_BUCKETS_BY_INDEXES   ReadStakingDataMethod_Name = 23
	ReadStakingDataMethod_COMPOSITE_BUCKETS_COUNT        ReadStakingDataMethod_Name = 24
	ReadStakingDataMethod_COMPOSITE_TOTAL_STAKING_AMOUNT ReadStakingDataMethod_Name = 25
	ReadStakingDataMethod_CONTRACT_STAKING_BUCKET_TYPES  ReadStakingDataMethod_Name = 26
)

// Enum value maps for ReadStakingDataMethod_Name.
var (
	ReadStakingDataMethod_Name_name = map[int32]string{
		0:  "INVALID",
		1:  "BUCKETS",
		2:  "BUCKETS_BY_VOTER",
		3:  "BUCKETS_BY_CANDIDATE",
		4:  "CANDIDATES",
		5:  "CANDIDATE_BY_NAME",
		6:  "BUCKETS_BY_INDEXES",
		7:  "CANDIDATE_BY_ADDRESS",
		8:  "TOTAL_STAKING_AMOUNT",
		9:  "BUCKETS_COUNT",
		20: "COMPOSITE_BUCKETS",
		21: "COMPOSITE_BUCKETS_BY_VOTER",
		22: "COMPOSITE_BUCKETS_BY_CANDIDATE",
		23: "COMPOSITE_BUCKETS_BY_INDEXES",
		24: "COMPOSITE_BUCKETS_COUNT",
		25: "COMPOSITE_TOTAL_STAKING_AMOUNT",
		26: "CONTRACT_STAKING_BUCKET_TYPES",
	}
	ReadStakingDataMethod_Name_value = map[string]int32{
		"INVALID":                        0,
		"BUCKETS":                        1,
		"BUCKETS_BY_VOTER":               2,
		"BUCKETS_BY_CANDIDATE":           3,
		"CANDIDATES":                     4,
		"CANDIDATE_BY_NAME":              5,
		"BUCKETS_BY_INDEXES":             6,
		"CANDIDATE_BY_ADDRESS":           7,
		"TOTAL_STAKING_AMOUNT":           8,
		"BUCKETS_COUNT":                  9,
		"COMPOSITE_BUCKETS":              20,
		"COMPOSITE_BUCKETS_BY_VOTER":     21,
		"COMPOSITE_BUCKETS_BY_CANDIDATE": 22,
		"COMPOSITE_BUCKETS_BY_INDEXES":   23,
		"COMPOSITE_BUCKETS_COUNT":        24,
		"COMPOSITE_TOTAL_STAKING_AMOUNT": 25,
		"CONTRACT_STAKING_BUCKET_TYPES":  26,
	}
)

func (x ReadStakingDataMethod_Name) Enum() *ReadStakingDataMethod_Name {
	p := new(ReadStakingDataMethod_Name)
	*p = x
	return p
}

func (x ReadStakingDataMethod_Name) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReadStakingDataMethod_Name) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_api_read_state_proto_enumTypes[0].Descriptor()
}

func (ReadStakingDataMethod_Name) Type() protoreflect.EnumType {
	return &file_proto_api_read_state_proto_enumTypes[0]
}

func (x ReadStakingDataMethod_Name) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReadStakingDataMethod_Name.Descriptor instead.
func (ReadStakingDataMethod_Name) EnumDescriptor() ([]byte, []int) {
	return file_proto_api_read_state_proto_rawDescGZIP(), []int{1, 0}
}

type PaginationParam struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        uint32                 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationParam) Reset() {
	*x = PaginationParam{}
	mi := &file_proto_api_read_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationParam) ProtoMessage() {}

func (x *PaginationParam) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_read_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationParam.ProtoReflect.Descriptor instead.
func (*PaginationParam) Descriptor() ([]byte, []int) {
	return file_proto_api_read_state_proto_rawDescGZIP(), []int{0}
}

func (x *PaginationParam) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *PaginationParam) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ReadStakingDataMethod struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Method        ReadStakingDataMethod_Name `protobuf:"varint,1,opt,name=method,proto3,enum=iotexapi.ReadStakingDataMethod_Name" json:"method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadStakingDataMethod) Reset() {
	*x = ReadStakingDataMethod{}
	mi := &file_proto_api_read_state_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadStakingDataMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadStakingDataMethod) ProtoMessage() {}

func (x *ReadStakingDataMethod) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_read_state_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadStakingDataMethod.ProtoReflect.Descriptor instead.
func (*ReadStakingDataMethod) Descriptor() ([]byte, []int) {
	return file_proto_api_read_state_proto_rawDescGZIP(), []int{1}
}

func (x *ReadStakingDataMethod) GetMethod() ReadStakingDataMethod_Name {
	if x != nil {
		return x.Method
	}
	return ReadStakingDataMethod_INVALID
}

type ReadStakingDataRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*ReadStakingDataRequest_Buckets
	//	*ReadStakingDataRequest_BucketsByVoter
	//	*ReadStakingDataRequest_BucketsByCandidate
	//	*ReadStakingDataRequest_Candidates_
	//	*ReadStakingDataRequest_CandidateByName_
	//	*ReadStakingDataRequest_BucketsByIndexes
	//	*ReadStakingDataRequest_CandidateByAddress_
	//	*ReadStakingDataRequest_TotalStakingAmount_
	//	*ReadStakingDataRequest_BucketsCount_
	//	*ReadStakingDataRequest_ContractStakingBucketTypes_
	Request       isReadStakingDataRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadStakingDataRequest) Reset() {
	*x = ReadStakingDataRequest{}
	mi := &file_proto_api_read_state_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadStakingDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadStakingDataRequest) ProtoMessage() {}

func (x *ReadStakingDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_read_state_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadStakingDataRequest.ProtoReflect.Descriptor instead.
func (*ReadStakingDataRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_read_state_proto_rawDescGZIP(), []int{2}
}

func (x *ReadStakingDataRequest) GetRequest() isReadStakingDataRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *ReadStakingDataRequest) GetBuckets() *ReadStakingDataRequest_VoteBuckets {
	if x != nil {
		if x, ok := x.Request.(*ReadStakingDataRequest_Buckets); ok {
			return x.Buckets
		}
	}
	return nil
}

func (x *ReadStakingDataRequest) GetBucketsByVoter() *ReadStakingDataRequest_VoteBucketsByVoter {
	if x != nil {
		if x, ok := x.Request.(*ReadStakingDataRequest_BucketsByVoter); ok {
			return x.BucketsByVoter
		}
	}
	return nil
}

func (x *ReadStakingDataRequest) GetBucketsByCandidate() *ReadStakingDataRequest_VoteBucketsByCandidate {
	if x != nil {
		if x, ok := x.Request.(*ReadStakingDataRequest_BucketsByCandidate); ok {
			return x.BucketsByCandidate
		}
	}
	return nil
}

func (x *ReadStakingDataRequest) GetCandidates() *ReadStakingDataRequest_Candidates {
	if x != nil {
		if x, ok := x.Request.(*ReadStakingDataRequest_Candidates_); ok {
			return x.Candidates
		}
	}
	return nil
}

func (x *ReadStakingDataRequest) GetCandidateByName() *ReadStakingDataRequest_CandidateByName {
	if x != nil {
		if x, ok := x.Request.(*ReadStakingDataRequest_CandidateByName_); ok {
			return x.CandidateByName
		}
	}
	return nil
}

func (x *ReadStakingDataRequest) GetBucketsByIndexes() *ReadStakingDataRequest_VoteBucketsByIndexes {
	if x != nil {
		if x, ok := x.Request.(*ReadStakingDataRequest_BucketsByIndexes); ok {
			return x.BucketsByIndexes
		}
	}
	return nil
}

func (x *ReadStakingDataRequest) GetCandidateByAddress() *ReadStakingDataRequest_CandidateByAddress {
	if x != nil {
		if x, ok := x.Request.(*ReadStakingDataRequest_CandidateByAddress_); ok {
			return x.CandidateByAddress
		}
	}
	return nil
}

func (x *ReadStakingDataRequest) GetTotalStakingAmount() *ReadStakingDataRequest_TotalStakingAmount {
	if x != nil {
		if x, ok := x.Request.(*ReadStakingDataRequest_TotalStakingAmount_); ok {
			return x.TotalStakingAmount
		}
	}
	return nil
}

func (x *ReadStakingDataRequest) GetBucketsCount() *ReadStakingDataRequest_BucketsCount {
	if x != nil {
		if x, ok := x.Request.(*ReadStakingDataRequest_BucketsCount_); ok {
			return x.BucketsCount
		}
	}
	return nil
}

func (x *ReadStakingDataRequest) GetContractStakingBucketTypes() *ReadStakingDataRequest_ContractStakingBucketTypes {
	if x != nil {
		if x, ok := x.Request.(*ReadStakingDataRequest_ContractStakingBucketTypes_); ok {
			return x.ContractStakingBucketTypes
		}
	}
	return nil
}

type isReadStakingDataRequest_Request interface {
	isReadStakingDataRequest_Request()
}

type ReadStakingDataRequest_Buckets struct {
	Buckets *ReadStakingDataRequest_VoteBuckets `protobuf:"bytes,1,opt,name=buckets,proto3,oneof"`
}

type ReadStakingDataRequest_BucketsByVoter struct {
	BucketsByVoter *ReadStakingDataRequest_VoteBucketsByVoter `protobuf:"bytes,2,opt,name=bucketsByVoter,proto3,oneof"`
}

type ReadStakingDataRequest_BucketsByCandidate struct {
	BucketsByCandidate *ReadStakingDataRequest_VoteBucketsByCandidate `protobuf:"bytes,3,opt,name=bucketsByCandidate,proto3,oneof"`
}

type ReadStakingDataRequest_Candidates_ struct {
	Candidates *ReadStakingDataRequest_Candidates `protobuf:"bytes,4,opt,name=candidates,proto3,oneof"`
}

type ReadStakingDataRequest_CandidateByName_ struct {
	CandidateByName *ReadStakingDataRequest_CandidateByName `protobuf:"bytes,5,opt,name=candidateByName,proto3,oneof"`
}

type ReadStakingDataRequest_BucketsByIndexes struct {
	BucketsByIndexes *ReadStakingDataRequest_VoteBucketsByIndexes `protobuf:"bytes,6,opt,name=bucketsByIndexes,proto3,oneof"`
}

type ReadStakingDataRequest_CandidateByAddress_ struct {
	CandidateByAddress *ReadStakingDataRequest_CandidateByAddress `protobuf:"bytes,7,opt,name=candidateByAddress,proto3,oneof"`
}

type ReadStakingDataRequest_TotalStakingAmount_ struct {
	TotalStakingAmount *ReadStakingDataRequest_TotalStakingAmount `protobuf:"bytes,8,opt,name=totalStakingAmount,proto3,oneof"`
}

type ReadStakingDataRequest_BucketsCount_ struct {
	BucketsCount *ReadStakingDataRequest_BucketsCount `protobuf:"bytes,9,opt,name=bucketsCount,proto3,oneof"`
}

type ReadStakingDataRequest_ContractStakingBucketTypes_ struct {
	ContractStakingBucketTypes *ReadStakingDataRequest_ContractStakingBucketTypes `protobuf:"bytes,10,opt,name=contractStakingBucketTypes,proto3,oneof"`
}

func (*ReadStakingDataRequest_Buckets) isReadStakingDataRequest_Request() {}

func (*ReadStakingDataRequest_BucketsByVoter) isReadStakingDataRequest_Request() {}

func (*ReadStakingDataRequest_BucketsByCandidate) isReadStakingDataRequest_Request() {}

func (*ReadStakingDataRequest_Candidates_) isReadStakingDataRequest_Request() {}

func (*ReadStakingDataRequest_CandidateByName_) isReadStakingDataRequest_Request() {}

func (*ReadStakingDataRequest_BucketsByIndexes) isReadStakingDataRequest_Request() {}

func (*ReadStakingDataRequest_CandidateByAddress_) isReadStakingDataRequest_Request() {}

func (*ReadStakingDataRequest_TotalStakingAmount_) isReadStakingDataRequest_Request() {}

func (*ReadStakingDataRequest_BucketsCount_) isReadStakingDataRequest_Request() {}

func (*ReadStakingDataRequest_ContractStakingBucketTypes_) isReadStakingDataRequest_Request() {}

type ReadStakingDataRequest_VoteBuckets struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *PaginationParam       `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadStakingDataRequest_VoteBuckets) Reset() {
	*x = ReadStakingDataRequest_VoteBuckets{}
	mi := &file_proto_api_read_state_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadStakingDataRequest_VoteBuckets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadStakingDataRequest_VoteBuckets) ProtoMessage() {}

func (x *ReadStakingDataRequest_VoteBuckets) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_read_state_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadStakingDataRequest_VoteBuckets.ProtoReflect.Descriptor instead.
func (*ReadStakingDataRequest_VoteBuckets) Descriptor() ([]byte, []int) {
	return file_proto_api_read_state_proto_rawDescGZIP(), []int{2, 0}
}

func (x *ReadStakingDataRequest_VoteBuckets) GetPagination() *PaginationParam {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ReadStakingDataRequest_VoteBucketsByVoter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VoterAddress  string                 `protobuf:"bytes,1,opt,name=voterAddress,proto3" json:"voterAddress,omitempty"`
	Pagination    *PaginationParam       `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadStakingDataRequest_VoteBucketsByVoter) Reset() {
	*x = ReadStakingDataRequest_VoteBucketsByVoter{}
	mi := &file_proto_api_read_state_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadStakingDataRequest_VoteBucketsByVoter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadStakingDataRequest_VoteBucketsByVoter) ProtoMessage() {}

func (x *ReadStakingDataRequest_VoteBucketsByVoter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_read_state_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadStakingDataRequest_VoteBucketsByVoter.ProtoReflect.Descriptor instead.
func (*ReadStakingDataRequest_VoteBucketsByVoter) Descriptor() ([]byte, []int) {
	return file_proto_api_read_state_proto_rawDescGZIP(), []int{2, 1}
}

func (x *ReadStakingDataRequest_VoteBucketsByVoter) GetVoterAddress() string {
	if x != nil {
		return x.VoterAddress
	}
	return ""
}

func (x *ReadStakingDataRequest_VoteBucketsByVoter) GetPagination() *PaginationParam {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ReadStakingDataRequest_VoteBucketsByCandidate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CandName      string                 `protobuf:"bytes,1,opt,name=candName,proto3" json:"candName,omitempty"`
	Pagination    *PaginationParam       `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadStakingDataRequest_VoteBucketsByCandidate) Reset() {
	*x = ReadStakingDataRequest_VoteBucketsByCandidate{}
	mi := &file_proto_api_read_state_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadStakingDataRequest_VoteBucketsByCandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadStakingDataRequest_VoteBucketsByCandidate) ProtoMessage() {}

func (x *ReadStakingDataRequest_VoteBucketsByCandidate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_read_state_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadStakingDataRequest_VoteBucketsByCandidate.ProtoReflect.Descriptor instead.
func (*ReadStakingDataRequest_VoteBucketsByCandidate) Descriptor() ([]byte, []int) {
	return file_proto_api_read_state_proto_rawDescGZIP(), []int{2, 2}
}

func (x *ReadStakingDataRequest_VoteBucketsByCandidate) GetCandName() string {
	if x != nil {
		return x.CandName
	}
	return ""
}

func (x *ReadStakingDataRequest_VoteBucketsByCandidate) GetPagination() *PaginationParam {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ReadStakingDataRequest_Candidates struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *PaginationParam       `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadStakingDataRequest_Candidates) Reset() {
	*x = ReadStakingDataRequest_Candidates{}
	mi := &file_proto_api_read_state_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadStakingDataRequest_Candidates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadStakingDataRequest_Candidates) ProtoMessage() {}

func (x *ReadStakingDataRequest_Candidates) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_read_state_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadStakingDataRequest_Candidates.ProtoReflect.Descriptor instead.
func (*ReadStakingDataRequest_Candidates) Descriptor() ([]byte, []int) {
	return file_proto_api_read_state_proto_rawDescGZIP(), []int{2, 3}
}

func (x *ReadStakingDataRequest_Candidates) GetPagination() *PaginationParam {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ReadStakingDataRequest_CandidateByName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CandName      string                 `protobuf:"bytes,1,opt,name=candName,proto3" json:"candName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadStakingDataRequest_CandidateByName) Reset() {
	*x = ReadStakingDataRequest_CandidateByName{}
	mi := &file_proto_api_read_state_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadStakingDataRequest_CandidateByName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadStakingDataRequest_CandidateByName) ProtoMessage() {}

func (x *ReadStakingDataRequest_CandidateByName) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_read_state_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadStakingDataRequest_CandidateByName.ProtoReflect.Descriptor instead.
func (*ReadStakingDataRequest_CandidateByName) Descriptor() ([]byte, []int) {
	return file_proto_api_read_state_proto_rawDescGZIP(), []int{2, 4}
}

func (x *ReadStakingDataRequest_CandidateByName) GetCandName() string {
	if x != nil {
		return x.CandName
	}
	return ""
}

type ReadStakingDataRequest_VoteBucketsByIndexes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         []uint64               `protobuf:"varint,1,rep,packed,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadStakingDataRequest_VoteBucketsByIndexes) Reset() {
	*x = ReadStakingDataRequest_VoteBucketsByIndexes{}
	mi := &file_proto_api_read_state_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadStakingDataRequest_VoteBucketsByIndexes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadStakingDataRequest_VoteBucketsByIndexes) ProtoMessage() {}

func (x *ReadStakingDataRequest_VoteBucketsByIndexes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_read_state_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadStakingDataRequest_VoteBucketsByIndexes.ProtoReflect.Descriptor instead.
func (*ReadStakingDataRequest_VoteBucketsByIndexes) Descriptor() ([]byte, []int) {
	return file_proto_api_read_state_proto_rawDescGZIP(), []int{2, 5}
}

func (x *ReadStakingDataRequest_VoteBucketsByIndexes) GetIndex() []uint64 {
	if x != nil {
		return x.Index
	}
	return nil
}

type ReadStakingDataRequest_CandidateByAddress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerAddr     string                 `protobuf:"bytes,1,opt,name=ownerAddr,proto3" json:"ownerAddr,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadStakingDataRequest_CandidateByAddress) Reset() {
	*x = ReadStakingDataRequest_CandidateByAddress{}
	mi := &file_proto_api_read_state_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadStakingDataRequest_CandidateByAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadStakingDataRequest_CandidateByAddress) ProtoMessage() {}

func (x *ReadStakingDataRequest_CandidateByAddress) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_read_state_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadStakingDataRequest_CandidateByAddress.ProtoReflect.Descriptor instead.
func (*ReadStakingDataRequest_CandidateByAddress) Descriptor() ([]byte, []int) {
	return file_proto_api_read_state_proto_rawDescGZIP(), []int{2, 6}
}

func (x *ReadStakingDataRequest_CandidateByAddress) GetOwnerAddr() string {
	if x != nil {
		return x.OwnerAddr
	}
	return ""
}

func (x *ReadStakingDataRequest_CandidateByAddress) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ReadStakingDataRequest_TotalStakingAmount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadStakingDataRequest_TotalStakingAmount) Reset() {
	*x = ReadStakingDataRequest_TotalStakingAmount{}
	mi := &file_proto_api_read_state_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadStakingDataRequest_TotalStakingAmount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadStakingDataRequest_TotalStakingAmount) ProtoMessage() {}

func (x *ReadStakingDataRequest_TotalStakingAmount) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_read_state_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadStakingDataRequest_TotalStakingAmount.ProtoReflect.Descriptor instead.
func (*ReadStakingDataRequest_TotalStakingAmount) Descriptor() ([]byte, []int) {
	return file_proto_api_read_state_proto_rawDescGZIP(), []int{2, 7}
}

type ReadStakingDataRequest_BucketsCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadStakingDataRequest_BucketsCount) Reset() {
	*x = ReadStakingDataRequest_BucketsCount{}
	mi := &file_proto_api_read_state_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadStakingDataRequest_BucketsCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadStakingDataRequest_BucketsCount) ProtoMessage() {}

func (x *ReadStakingDataRequest_BucketsCount) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_read_state_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadStakingDataRequest_BucketsCount.ProtoReflect.Descriptor instead.
func (*ReadStakingDataRequest_BucketsCount) Descriptor() ([]byte, []int) {
	return file_proto_api_read_state_proto_rawDescGZIP(), []int{2, 8}
}

type ReadStakingDataRequest_ContractStakingBucketTypes struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ContractAddress string                 `protobuf:"bytes,1,opt,name=contractAddress,proto3" json:"contractAddress,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReadStakingDataRequest_ContractStakingBucketTypes) Reset() {
	*x = ReadStakingDataRequest_ContractStakingBucketTypes{}
	mi := &file_proto_api_read_state_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadStakingDataRequest_ContractStakingBucketTypes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadStakingDataRequest_ContractStakingBucketTypes) ProtoMessage() {}

func (x *ReadStakingDataRequest_ContractStakingBucketTypes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_read_state_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadStakingDataRequest_ContractStakingBucketTypes.ProtoReflect.Descriptor instead.
func (*ReadStakingDataRequest_ContractStakingBucketTypes) Descriptor() ([]byte, []int) {
	return file_proto_api_read_state_proto_rawDescGZIP(), []int{2, 9}
}

func (x *ReadStakingDataRequest_ContractStakingBucketTypes) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

var File_proto_api_read_state_proto protoreflect.FileDescriptor

const file_proto_api_read_state_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/api/read_state.proto\x12\biotexapi\"?\n" +
	"\x0fPaginationParam\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\rR\x06offset\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\"\x8f\x04\n" +
	"\x15ReadStakingDataMethod\x12<\n" +
	"\x06method\x18\x01 \x01(\x0e2$.iotexapi.ReadStakingDataMethod.NameR\x06method\"\xb7\x03\n" +
	"\x04Name\x12\v\n" +
	"\aINVALID\x10\x00\x12\v\n" +
	"\aBUCKETS\x10\x01\x12\x14\n" +
	"\x10BUCKETS_BY_VOTER\x10\x02\x12\x18\n" +
	"\x14BUCKETS_BY_CANDIDATE\x10\x03\x12\x0e\n" +
	"\n" +
	"CANDIDATES\x10\x04\x12\x15\n" +
	"\x11CANDIDATE_BY_NAME\x10\x05\x12\x16\n" +
	"\x12BUCKETS_BY_INDEXES\x10\x06\x12\x18\n" +
	"\x14CANDIDATE_BY_ADDRESS\x10\a\x12\x18\n" +
	"\x14TOTAL_STAKING_AMOUNT\x10\b\x12\x11\n" +
	"\rBUCKETS_COUNT\x10\t\x12\x15\n" +
	"\x11COMPOSITE_BUCKETS\x10\x14\x12\x1e\n" +
	"\x1aCOMPOSITE_BUCKETS_BY_VOTER\x10\x15\x12\"\n" +
	"\x1eCOMPOSITE_BUCKETS_BY_CANDIDATE\x10\x16\x12 \n" +
	"\x1cCOMPOSITE_BUCKETS_BY_INDEXES\x10\x17\x12\x1b\n" +
	"\x17COMPOSITE_BUCKETS_COUNT\x10\x18\x12\"\n" +
	"\x1eCOMPOSITE_TOTAL_STAKING_AMOUNT\x10\x19\x12!\n" +
	"\x1dCONTRACT_STAKING_BUCKET_TYPES\x10\x1a\"\xf3\f\n" +
	"\x16ReadStakingDataRequest\x12H\n" +
	"\abuckets\x18\x01 \x01(\v2,.iotexapi.ReadStakingDataRequest.VoteBucketsH\x00R\abuckets\x12]\n" +
	"\x0ebucketsByVoter\x18\x02 \x01(\v23.iotexapi.ReadStakingDataRequest.VoteBucketsByVoterH\x00R\x0ebucketsByVoter\x12i\n" +
	"\x12bucketsByCandidate\x18\x03 \x01(\v27.iotexapi.ReadStakingDataRequest.VoteBucketsByCandidateH\x00R\x12bucketsByCandidate\x12M\n" +
	"\n" +
	"candidates\x18\x04 \x01(\v2+.iotexapi.ReadStakingDataRequest.CandidatesH\x00R\n" +
	"candidates\x12\\\n" +
	"\x0fcandidateByName\x18\x05 \x01(\v20.iotexapi.ReadStakingDataRequest.CandidateByNameH\x00R\x0fcandidateByName\x12c\n" +
	"\x10bucketsByIndexes\x18\x06 \x01(\v25.iotexapi.ReadStakingDataRequest.VoteBucketsByIndexesH\x00R\x10bucketsByIndexes\x12e\n" +
	"\x12candidateByAddress\x18\a \x01(\v23.iotexapi.ReadStakingDataRequest.CandidateByAddressH\x00R\x12candidateByAddress\x12e\n" +
	"\x12totalStakingAmount\x18\b \x01(\v23.iotexapi.ReadStakingDataRequest.TotalStakingAmountH\x00R\x12totalStakingAmount\x12S\n" +
	"\fbucketsCount\x18\t \x01(\v2-.iotexapi.ReadStakingDataRequest.BucketsCountH\x00R\fbucketsCount\x12}\n" +
	"\x1acontractStakingBucketTypes\x18\n" +
	" \x01(\v2;.iotexapi.ReadStakingDataRequest.ContractStakingBucketTypesH\x00R\x1acontractStakingBucketTypes\x1aH\n" +
	"\vVoteBuckets\x129\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x19.iotexapi.PaginationParamR\n" +
	"pagination\x1as\n" +
	"\x12VoteBucketsByVoter\x12\"\n" +
	"\fvoterAddress\x18\x01 \x01(\tR\fvoterAddress\x129\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x19.iotexapi.PaginationParamR\n" +
	"pagination\x1ao\n" +
	"\x16VoteBucketsByCandidate\x12\x1a\n" +
	"\bcandName\x18\x01 \x01(\tR\bcandName\x129\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x19.iotexapi.PaginationParamR\n" +
	"pagination\x1aG\n" +
	"\n" +
	"Candidates\x129\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x19.iotexapi.PaginationParamR\n" +
	"pagination\x1a-\n" +
	"\x0fCandidateByName\x12\x1a\n" +
	"\bcandName\x18\x01 \x01(\tR\bcandName\x1a,\n" +
	"\x14VoteBucketsByIndexes\x12\x14\n" +
	"\x05index\x18\x01 \x03(\x04R\x05index\x1aB\n" +
	"\x12CandidateByAddress\x12\x1c\n" +
	"\townerAddr\x18\x01 \x01(\tR\townerAddr\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x1a\x14\n" +
	"\x12TotalStakingAmount\x1a\x0e\n" +
	"\fBucketsCount\x1aF\n" +
	"\x1aContractStakingBucketTypes\x12(\n" +
	"\x0fcontractAddress\x18\x01 \x01(\tR\x0fcontractAddressB\t\n" +
	"\arequestBY\n" +
	" com.github.iotexproject.grpc.apiP\x01Z3github.com/iotexproject/iotex-proto/golang/iotexapib\x06proto3"

var (
	file_proto_api_read_state_proto_rawDescOnce sync.Once
	file_proto_api_read_state_proto_rawDescData []byte
)

func file_proto_api_read_state_proto_rawDescGZIP() []byte {
	file_proto_api_read_state_proto_rawDescOnce.Do(func() {
		file_proto_api_read_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_api_read_state_proto_rawDesc), len(file_proto_api_read_state_proto_rawDesc)))
	})
	return file_proto_api_read_state_proto_rawDescData
}

var file_proto_api_read_state_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_api_read_state_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_api_read_state_proto_goTypes = []any{
	(ReadStakingDataMethod_Name)(0),                           // 0: iotexapi.ReadStakingDataMethod.Name
	(*PaginationParam)(nil),                                   // 1: iotexapi.PaginationParam
	(*ReadStakingDataMethod)(nil),                             // 2: iotexapi.ReadStakingDataMethod
	(*ReadStakingDataRequest)(nil),                            // 3: iotexapi.ReadStakingDataRequest
	(*ReadStakingDataRequest_VoteBuckets)(nil),                // 4: iotexapi.ReadStakingDataRequest.VoteBuckets
	(*ReadStakingDataRequest_VoteBucketsByVoter)(nil),         // 5: iotexapi.ReadStakingDataRequest.VoteBucketsByVoter
	(*ReadStakingDataRequest_VoteBucketsByCandidate)(nil),     // 6: iotexapi.ReadStakingDataRequest.VoteBucketsByCandidate
	(*ReadStakingDataRequest_Candidates)(nil),                 // 7: iotexapi.ReadStakingDataRequest.Candidates
	(*ReadStakingDataRequest_CandidateByName)(nil),            // 8: iotexapi.ReadStakingDataRequest.CandidateByName
	(*ReadStakingDataRequest_VoteBucketsByIndexes)(nil),       // 9: iotexapi.ReadStakingDataRequest.VoteBucketsByIndexes
	(*ReadStakingDataRequest_CandidateByAddress)(nil),         // 10: iotexapi.ReadStakingDataRequest.CandidateByAddress
	(*ReadStakingDataRequest_TotalStakingAmount)(nil),         // 11: iotexapi.ReadStakingDataRequest.TotalStakingAmount
	(*ReadStakingDataRequest_BucketsCount)(nil),               // 12: iotexapi.ReadStakingDataRequest.BucketsCount
	(*ReadStakingDataRequest_ContractStakingBucketTypes)(nil), // 13: iotexapi.ReadStakingDataRequest.ContractStakingBucketTypes
}
var file_proto_api_read_state_proto_depIdxs = []int32{
	0,  // 0: iotexapi.ReadStakingDataMethod.method:type_name -> iotexapi.ReadStakingDataMethod.Name
	4,  // 1: iotexapi.ReadStakingDataRequest.buckets:type_name -> iotexapi.ReadStakingDataRequest.VoteBuckets
	5,  // 2: iotexapi.ReadStakingDataRequest.bucketsByVoter:type_name -> iotexapi.ReadStakingDataRequest.VoteBucketsByVoter
	6,  // 3: iotexapi.ReadStakingDataRequest.bucketsByCandidate:type_name -> iotexapi.ReadStakingDataRequest.VoteBucketsByCandidate
	7,  // 4: iotexapi.ReadStakingDataRequest.candidates:type_name -> iotexapi.ReadStakingDataRequest.Candidates
	8,  // 5: iotexapi.ReadStakingDataRequest.candidateByName:type_name -> iotexapi.ReadStakingDataRequest.CandidateByName
	9,  // 6: iotexapi.ReadStakingDataRequest.bucketsByIndexes:type_name -> iotexapi.ReadStakingDataRequest.VoteBucketsByIndexes
	10, // 7: iotexapi.ReadStakingDataRequest.candidateByAddress:type_name -> iotexapi.ReadStakingDataRequest.CandidateByAddress
	11, // 8: iotexapi.ReadStakingDataRequest.totalStakingAmount:type_name -> iotexapi.ReadStakingDataRequest.TotalStakingAmount
	12, // 9: iotexapi.ReadStakingDataRequest.bucketsCount:type_name -> iotexapi.ReadStakingDataRequest.BucketsCount
	13, // 10: iotexapi.ReadStakingDataRequest.contractStakingBucketTypes:type_name -> iotexapi.ReadStakingDataRequest.ContractStakingBucketTypes
	1,  // 11: iotexapi.ReadStakingDataRequest.VoteBuckets.pagination:type_name -> iotexapi.PaginationParam
	1,  // 12: iotexapi.ReadStakingDataRequest.VoteBucketsByVoter.pagination:type_name -> iotexapi.PaginationParam
	1,  // 13: iotexapi.ReadStakingDataRequest.VoteBucketsByCandidate.pagination:type_name -> iotexapi.PaginationParam
	1,  // 14: iotexapi.ReadStakingDataRequest.Candidates.pagination:type_name -> iotexapi.PaginationParam
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_proto_api_read_state_proto_init() }
func file_proto_api_read_state_proto_init() {
	if File_proto_api_read_state_proto != nil {
		return
	}
	file_proto_api_read_state_proto_msgTypes[2].OneofWrappers = []any{
		(*ReadStakingDataRequest_Buckets)(nil),
		(*ReadStakingDataRequest_BucketsByVoter)(nil),
		(*ReadStakingDataRequest_BucketsByCandidate)(nil),
		(*ReadStakingDataRequest_Candidates_)(nil),
		(*ReadStakingDataRequest_CandidateByName_)(nil),
		(*ReadStakingDataRequest_BucketsByIndexes)(nil),
		(*ReadStakingDataRequest_CandidateByAddress_)(nil),
		(*ReadStakingDataRequest_TotalStakingAmount_)(nil),
		(*ReadStakingDataRequest_BucketsCount_)(nil),
		(*ReadStakingDataRequest_ContractStakingBucketTypes_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_api_read_state_proto_rawDesc), len(file_proto_api_read_state_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_api_read_state_proto_goTypes,
		DependencyIndexes: file_proto_api_read_state_proto_depIdxs,
		EnumInfos:         file_proto_api_read_state_proto_enumTypes,
		MessageInfos:      file_proto_api_read_state_proto_msgTypes,
	}.Build()
	File_proto_api_read_state_proto = out.File
	file_proto_api_read_state_proto_goTypes = nil
	file_proto_api_read_state_proto_depIdxs = nil
}
